"""Data-driven infographic poster built with Vixl.

Run from the repository root:

    python explorations/08-infographic/build.py

Everything is written to explorations/08-infographic/output/ (wiped on every run).
The datasets below are ILLUSTRATIVE ONLY -- plausible-looking numbers invented for a
layout exploration, not real statistics.
"""

import json
import math
import os
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "output"
if OUT.exists():
    shutil.rmtree(OUT)
OUT.mkdir(parents=True)
# Keep every Vixl side effect inside this exploration folder.
os.environ["VIXL_RESOURCES"] = str(OUT / "_resources.json")
os.environ["VIXL_FONT_CACHE"] = str(OUT / "_fontcache")
os.environ.setdefault("VIXL_NO_UPDATE", "1")

from vixl import Project, VixlError  # noqa: E402
from vixl.colors import simulate_vision  # noqa: E402
from vixl.typefaces import install_font, pair_fonts  # noqa: E402

# --------------------------------------------------------------------------------------
# Data (illustrative)
# --------------------------------------------------------------------------------------
YEARS = list(range(2015, 2026))

DATASETS = {
    "world": {
        "slug": "world",
        "eyebrow": "THE ENERGY ISSUE  /  DATA DESK  /  NO. 08",
        "title": "The Great\nGreen Switch",
        "deck": (
            "In ten years renewables went from a quarter of the world's electricity to "
            "more than a third. Solar and wind did most of the lifting, while hydropower "
            "quietly kept the lights on. Here is who moved, how fast, and what the grid "
            "looks like now."
        ),
        "region": "World",
        "kpis": [
            ("34.5%", "of global electricity came\nfrom renewables in 2025"),
            ("+11.2 pts", "rise in the renewable\nshare since 2015"),
            ("6.8×", "growth in solar generation\nover the decade"),
        ],
        "countries": [  # name, 2015 share, 2025 share
            ("Norway", 97.0, 98.4),
            ("Brazil", 75.2, 88.6),
            ("New Zealand", 80.1, 86.9),
            ("Denmark", 64.0, 84.1),
            ("Portugal", 48.5, 71.3),
            ("Spain", 35.2, 56.0),
            ("Germany", 30.1, 54.7),
            ("United Kingdom", 24.6, 49.8),
            ("China", 24.0, 36.2),
            ("United States", 13.8, 25.1),
            ("India", 15.3, 23.9),
            ("Japan", 16.0, 25.8),
        ],
        "renewables": [23.3, 24.1, 24.9, 25.6, 26.6, 28.4, 28.1, 29.6, 30.9, 32.8, 34.5],
        "solar_wind": [4.6, 5.2, 6.0, 6.9, 8.0, 9.4, 10.3, 11.9, 13.4, 15.8, 18.0],
        "notes": [  # year index, series, text
            (5, "renewables", "2020: demand dips during\nlockdowns, share jumps"),
            (8, "solar_wind", "2023: record 450 GW of\nnew solar connected"),
        ],
        "mix": [  # label, share, swatch
            ("Solar", 8.5, "solar"),
            ("Wind", 9.5, "wind"),
            ("Hydro", 14.0, "hydro"),
            ("Bio & other", 2.5, "other"),
            ("Nuclear", 9.0, "nuclear"),
            ("Fossil fuels", 56.5, "fossil"),
        ],
        "reference": ("World average", 34.5),
        "source": (
            "Illustrative dataset created for a Vixl layout exploration; values are invented "
            "and must not be cited. Shares are of electricity generation, not total energy."
        ),
    },
    "europe": {
        "slug": "europe",
        "eyebrow": "THE ENERGY ISSUE  /  DATA DESK  /  NO. 08-B",
        "title": "Europe Turns\nthe Dial",
        "deck": (
            "Across Europe the renewable share climbed by almost twenty points in a decade. "
            "Wind became the continent's workhorse and rooftop solar spread from the south "
            "to the Baltic. A regional edition of the same template, regenerated from data."
        ),
        "region": "Europe",
        "kpis": [
            ("47.2%", "of Europe's electricity came\nfrom renewables in 2025"),
            ("+18.6 pts", "rise in the renewable\nshare since 2015"),
            ("1 in 5", "kilowatt-hours now\ngenerated by wind"),
        ],
        "countries": [
            ("Iceland", 99.9, 99.9),
            ("Austria", 70.3, 81.0),
            ("Sweden", 63.0, 72.4),
            ("Portugal", 48.5, 71.3),
            ("Denmark", 64.0, 84.1),
            ("Spain", 35.2, 56.0),
            ("Germany", 30.1, 54.7),
            ("Netherlands", 11.8, 49.5),
            ("Italy", 38.0, 44.2),
            ("France", 16.4, 28.7),
            ("Poland", 13.4, 29.6),
        ],
        "renewables": [28.6, 29.4, 30.5, 32.1, 33.9, 37.4, 37.0, 38.9, 43.1, 45.3, 47.2],
        "solar_wind": [10.8, 11.6, 13.2, 14.4, 16.1, 18.9, 19.3, 21.8, 26.5, 28.4, 30.6],
        "notes": [
            (3, "renewables", "2018: wind passes coal\nin three big markets"),
            (8, "solar_wind", "2023: storage auctions\nunlock evening solar"),
        ],
        "mix": [
            ("Solar", 10.2, "solar"),
            ("Wind", 20.4, "wind"),
            ("Hydro", 12.4, "hydro"),
            ("Bio & other", 4.2, "other"),
            ("Nuclear", 22.3, "nuclear"),
            ("Fossil fuels", 30.5, "fossil"),
        ],
        "reference": ("Europe average", 47.2),
        "source": (
            "Illustrative regional dataset created for a Vixl layout exploration; values are "
            "invented and must not be cited. Shares are of electricity generation."
        ),
    },
}

# --------------------------------------------------------------------------------------
# Design system
# --------------------------------------------------------------------------------------
W, H = 1600, 4180
M = 96  # outer margin
GUTTER = 32
COLS = 12
ISO_PITCH = 60
COL_W = (W - 2 * M - (COLS - 1) * GUTTER) / COLS  # 88 px


def col_x(n):
    """Left edge of grid column n (1-based)."""
    return M + (n - 1) * (COL_W + GUTTER)


def span(a, b):
    return col_x(b) + COL_W - col_x(a)


# Okabe-Ito -- the reference colour-blind-safe qualitative palette.
OKABE_ITO = ["#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000"]

ROLES = {
    "background": "#F6F3EC",
    "surface": "#ECE7DB",
    "ink": "#16191D",
    "muted": "#585F67",
    "rule": "#CFC8B8",
    "accent": "@oi-6",  # vermillion
    "accent-text": "#A6400A",
    "on-accent": "#FFFFFF",
    "night": "#14181D",
    "night-2": "#20262D",
    "night-ink": "#F4EFE3",
    "night-muted": "#A9B1BA",
    # semantic data swatches, all mapped onto palette slots
    "renewable": "@oi-3",
    "solar": "@oi-1",
    "wind": "@oi-2",
    "hydro": "@oi-5",
    "other": "@oi-4",
    "nuclear": "@oi-7",
    "fossil": "#B3AC9E",
}


class Poster:
    def __init__(self, data, expand_repeats=False):
        self.d = data
        self.expand = expand_repeats
        self.p = Project(W, H, ROLES["background"])
        self.ops = []

    def op(self, **kw):
        self.ops.append(kw)
        return kw

    def repeat(self, target, count, dx=0, dy=0):
        """Live `repeat` (one editable layer) or, for strict-SVG output, explicit duplicates."""
        if not self.expand:
            self.op(type="repeat", target=target, count=count, dx=dx, dy=dy)
            return [target]
        base = next(o for o in self.ops if o.get("name") == target)
        names = [target]
        for k in range(1, count):
            copy = {**base, "name": f"{target}-{k}", "x": base["x"] + k * dx, "y": base["y"] + k * dy}
            self.ops.append(copy)
            names.append(copy["name"])
        return names

    def flush(self):
        if self.ops:
            self.p.apply(self.ops, detail="compact")
            self.ops = []

    def text(self, name, text, style, x=0, y=0, color="@ink", font="body", align="left", spacing=None):
        o = self.op(type="text", name=name, text=text, x=x, y=y, color=color, font=font, align=align)
        if spacing is not None:
            o["spacing"] = spacing
        self.op(type="style-apply", target=name, name=style)
        return name

    def bounds(self, name):
        return self.p.inspect(name)["resolved_bounds"]

    # ---------------------------------------------------------------- setup
    def setup(self):
        p = self.p
        print("  installing fonts (Google Fonts, cached)...")
        pair_fonts(p, "dm-serif-dm-sans")
        install_font(p, "DM Sans", 700)  # registered as dm-sans-700
        install_font(p, "DM Mono", 500)  # registered as dm-mono-500
        self.op(type="palette-define", name="oi", colors=OKABE_ITO)
        self.op(type="palette-apply", name="oi", roles=False)
        for k, v in ROLES.items():
            self.op(type="swatch", name=k, color=v)
        # Modular type scale: caption 15 ... display 136 (perfect fourth from 21 px)
        self.op(type="type-scale", base=21, ratio="perfect-fourth")
        self.op(type="style-define", name="kpi", settings={"size": 92})
        self.op(type="style-define", name="label", settings={"size": 19})
        self.op(type="style-define", name="tick", settings={"size": 16, "color": "@muted"})
        self.op(type="style-define", name="poster-title", settings={"size": 150})
        self.op(type="style-define", name="tight", kind="paragraph", settings={"spacing": 6})
        self.op(type="grid", name="g", columns=COLS, rows=1, margin=M, gutter=GUTTER)
        self.op(type="variable", name="eyebrow", value=self.d["eyebrow"])
        self.op(type="variable", name="title", value=self.d["title"])
        self.op(type="variable", name="region", value=self.d["region"])
        self.flush()

    # ---------------------------------------------------------------- header
    def header(self):
        self.op(type="guide", name="kpi-top", axis="y", position=760)
        self.op(type="guide", name="header-end", axis="y", position=1080)
        self.op(type="solid", name="night-band", width=W, height=1080, x=0, y=0, color="@night")
        # faint decorative sun rays: a repeated thin bar, clipped by a circle
        self.op(type="shape", shape="ellipse", name="sun", width=760, height=760, x=980, y=-260, fill="@night-2")
        self.op(type="shape", shape="rectangle", name="ray", width=800, height=3, x=960, y=-240, fill="alpha(@solar, 0.35)")
        rays = self.repeat("ray", 40, dy=19)
        self.op(type="group", name="rays", targets=rays)
        self.op(type="clip", target="rays", base="sun")

        self.text("eyebrow", "${eyebrow}", "caption", color="@solar", font="dm-mono-500")
        self.op(type="constrain", target="eyebrow", constraints={"left": "guide:g-x1-start.left", "top": "canvas.top+104"})
        self.text("title", "${title}", "poster-title", color="@night-ink", font="heading", spacing=0)
        self.op(type="constrain", target="title", constraints={"left": "guide:g-x1-start.left-6", "top": "eyebrow.bottom+28"})
        self.text("deck", self.d["deck"], "lead", color="@night-muted")
        self.op(type="style-apply", target="deck", name="tight", kind="paragraph")
        self.op(type="text-layout", target="deck", width=round(span(1, 8)), height=200)
        self.op(type="constrain", target="deck", constraints={"left": "guide:g-x1-start.left", "top": "title.bottom+40"})
        self.flush()

        # KPI cards: three 4-column cards with a 32 px gutter
        accents = ["@renewable", "@solar", "@wind"]
        cards = []
        for i, (num, cap) in enumerate(self.d["kpis"]):
            x = col_x(1 + 4 * i)
            cw = span(1, 4)
            self.op(type="shape", shape="rounded-rectangle", name=f"kpi{i}-card", width=round(cw), height=236,
                    x=round(x), y=760, radius=14, fill="@night-2")
            self.op(type="shape", shape="rectangle", name=f"kpi{i}-bar", width=56, height=6, x=round(x) + 32, y=792,
                    fill=accents[i])
            self.text(f"kpi{i}-num", num, "kpi", x=round(x) + 28, y=806, color="@night-ink", font="heading")
            self.text(f"kpi{i}-cap", cap, "body", color="@night-muted")
            self.op(type="style-apply", target=f"kpi{i}-cap", name="tight", kind="paragraph")
            self.op(type="constrain", target=f"kpi{i}-cap",
                    constraints={"left": f"kpi{i}-card.left+32", "bottom": f"kpi{i}-card.bottom-30"})
            self.op(type="group", name=f"kpi{i}", targets=[f"kpi{i}-card", f"kpi{i}-bar", f"kpi{i}-num", f"kpi{i}-cap"])
            cards.append(f"kpi{i}")
        self.op(type="distribute", targets=cards, axis="horizontal", gap=GUTTER)
        self.op(type="group", name="kpis", targets=cards)
        self.op(type="constrain", target="kpis", constraints={"left": "guide:g-x1-start.left", "top": "guide:kpi-top.top"})
        self.flush()

    # ---------------------------------------------------------------- section heading helper
    def section_head(self, key, number, title, sub, guide_y, col_from=1, col_to=12, style="headline"):
        self.op(type="guide", name=f"sec-{key}", axis="y", position=guide_y)
        gx = f"g-x{col_from}-start"
        self.op(type="shape", shape="rectangle", name=f"{key}-rule", width=round(span(col_from, col_to)), height=3, fill="@ink")
        self.op(type="constrain", target=f"{key}-rule", constraints={"left": f"guide:{gx}.left", "top": f"guide:sec-{key}.top"})
        self.text(f"{key}-num", number, "lead", color="@accent-text", font="dm-mono-500")
        self.op(type="constrain", target=f"{key}-num", constraints={"left": f"guide:{gx}.left", "top": f"{key}-rule.bottom+26"})
        self.text(f"{key}-title", title, style, font="heading")
        self.op(type="constrain", target=f"{key}-title", constraints={"left": f"{key}-num.right+18", "top": f"{key}-rule.bottom+12"})
        self.text(f"{key}-sub", sub, "body", color="@muted")
        self.op(type="constrain", target=f"{key}-sub", constraints={"left": f"{key}-title.left", "top": f"{key}-title.bottom+10"})

    # ---------------------------------------------------------------- bar chart
    def bar_chart(self):
        d = self.d
        rows = sorted(d["countries"], key=lambda r: -r[2])
        n = len(rows)
        self.section_head("a", "01", "Who's leading the switch",
                          f"Renewable share of electricity generation, 2025, with the 2015 level marked", 1160)
        self.flush()
        top = 1160 + 210
        row_h, row_gap = 34, 18
        label_w = span(1, 3)
        plot_x = col_x(4)
        plot_w = round(span(4, 12) - 70)  # leave room for value labels
        plot_h = n * row_h + (n - 1) * row_gap
        # legend, top right of the chart
        self.op(type="shape", shape="rounded-rectangle", name="lg-a-bar", width=26, height=14, radius=3, fill="@renewable")
        self.text("lg-a-bar-t", "2025 share", "caption", color="@muted")
        self.op(type="shape", shape="rectangle", name="lg-a-tick", width=4, height=22, fill="@ink")
        self.text("lg-a-tick-t", "2015 level", "caption", color="@muted")
        self.op(type="constrain", target="lg-a-tick-t", constraints={"right": "guide:g-x12-end.left", "bottom": "guide:sec-a.top+170"})
        self.op(type="constrain", target="lg-a-tick", constraints={"right": "lg-a-tick-t.left-10", "center-y": "lg-a-tick-t.center-y"})
        self.op(type="constrain", target="lg-a-bar-t", constraints={"right": "lg-a-tick.left-28", "center-y": "lg-a-tick-t.center-y"})
        self.op(type="constrain", target="lg-a-bar", constraints={"right": "lg-a-bar-t.left-10", "center-y": "lg-a-tick-t.center-y"})
        self.op(type="group", name="legend-a", targets=["lg-a-bar", "lg-a-bar-t", "lg-a-tick", "lg-a-tick-t"])

        # ---- plot group: frame defines 100 %, bars are sized as a percentage of it
        self.op(type="shape", shape="rectangle", name="a-frame", width=plot_w, height=plot_h + 24, x=plot_x, y=top - 12,
                fill="transparent")
        self.op(type="shape", shape="rectangle", name="a-grid", width=1, height=plot_h + 24, x=plot_x, y=top - 12, fill="@rule")
        a_grid = self.repeat("a-grid", 5, dx=(plot_w - 1) / 4)
        for i, (name, v15, v25) in enumerate(rows):
            y = top + i * (row_h + row_gap)
            self.op(type="shape", shape="rectangle", name=f"a-bar{i}", width=10, height=row_h, x=plot_x, y=y, fill="@renewable")
        self.flush()
        members = ["a-frame", *a_grid] + [f"a-bar{i}" for i in range(n)]
        self.op(type="group", name="a-plot", targets=members)
        for i, (name, v15, v25) in enumerate(rows):
            # percentage of the parent group == percentage of renewable share
            self.op(type="resize", target=f"a-bar{i}", width=f"{v25}%", height=row_h)
            self.op(type="shape", shape="rectangle", name=f"a-tick{i}", width=4, height=row_h + 12,
                    x=round(plot_x + plot_w * v15 / 100) - 2, y=top + i * (row_h + row_gap) - 6, fill="@ink")
        self.op(type="group", name="a-ticks", targets=[f"a-tick{i}" for i in range(n)])
        self.flush()
        # labels and values (top level, constrained to bars)
        for i, (name, v15, v25) in enumerate(rows):
            y = top + i * (row_h + row_gap)
            self.text(f"a-name{i}", name, "label", font="dm-sans-700")
            self.op(type="constrain", target=f"a-name{i}", constraints={"left": "guide:g-x1-start.left", "center-y": f"canvas.top+{y + row_h / 2:.0f}"})
            bar_end = plot_x + plot_w * v25 / 100
            if v25 > 90:  # would collide with the 100 % gridline: set the value inside the bar
                self.text(f"a-val{i}", f"{v25:.1f}%", "label", font="dm-mono-500", color="@on-accent")
                self.op(type="constrain", target=f"a-val{i}", constraints={"right": f"canvas.left+{bar_end - 14:.0f}", "center-y": f"canvas.top+{y + row_h / 2:.0f}"})
            else:
                self.text(f"a-val{i}", f"{v25:.1f}%", "label", font="dm-mono-500")
                self.op(type="constrain", target=f"a-val{i}", constraints={"left": f"canvas.left+{bar_end + 12:.0f}", "center-y": f"canvas.top+{y + row_h / 2:.0f}"})
        # axis labels under the plot
        for k in range(5):
            self.text(f"a-ax{k}", f"{k * 25}%", "tick", font="dm-mono-500")
            self.op(type="constrain", target=f"a-ax{k}", constraints={"center-x": f"canvas.left+{plot_x + plot_w * k / 4:.0f}", "top": f"canvas.top+{top + plot_h + 22}"})
        # reference line + annotation (leader line)
        ref_label, ref = d["reference"]
        rx = plot_x + plot_w * ref / 100
        self.op(type="pen", name="a-ref", points=[[3, 0], [3, plot_h + 60]], smooth=False, stroke="@accent", stroke_width=2,
                fill="transparent", x=round(rx) - 3, y=top - 36, width=6, height=plot_h + 60)
        self.text("a-ref-t", f"{ref_label} {ref:.1f}%", "caption", color="@accent-text", font="dm-sans-700")
        self.op(type="constrain", target="a-ref-t", constraints={"left": "a-ref.right+6", "top": "a-ref.top-4"})
        self.flush()
        self.n_rows = n
        self.a_bottom = top + plot_h + 60
        return top, plot_x, plot_w, plot_h

    # ---------------------------------------------------------------- line / area chart
    def line_chart(self):
        d = self.d
        sec = self.a_bottom + 110
        self.section_head("b", "02", "A decade of steady climbing",
                          f"{d['region']}: renewable share of electricity, and the part from solar and wind", sec)
        self.flush()
        top = sec + 200
        px, pw, ph = col_x(1) + 64, round(span(1, 12) - 64 - 150), 540
        ymax = math.ceil(max(d["renewables"]) * 1.15 / 10) * 10
        self.ymax = ymax
        n = len(YEARS)

        def pt(i, v):
            return pw * i / (n - 1), ph - ph * v / ymax

        # y grid via one repeated hairline
        steps = 4
        self.op(type="shape", shape="rectangle", name="b-grid", width=pw, height=1, x=px, y=top, fill="@rule")
        b_grid = self.repeat("b-grid", steps + 1, dy=(ph - 1) / steps)
        self.op(type="shape", shape="rectangle", name="b-base", width=pw, height=3, x=px, y=top + ph - 1, fill="@ink")
        for k in range(steps + 1):
            v = ymax * (steps - k) / steps
            self.text(f"b-yl{k}", f"{v:.0f}%", "tick", font="dm-mono-500", align="right")
            self.op(type="constrain", target=f"b-yl{k}", constraints={"right": f"canvas.left+{px - 14}", "center-y": f"canvas.top+{top + ph * k / steps:.0f}"})
        for i, yr in enumerate(YEARS):
            self.text(f"b-x{i}", str(yr), "tick", font="dm-mono-500")
            self.op(type="constrain", target=f"b-x{i}", constraints={"center-x": f"canvas.left+{px + pw * i / (n - 1):.0f}", "top": f"canvas.top+{top + ph + 16}"})
        # area for total renewables (single-contour Bézier-free path)
        pts = [pt(i, v) for i, v in enumerate(d["renewables"])]
        path = f"M0 {ph} " + " ".join(f"L{x:.1f} {y:.1f}" for x, y in pts) + f" L{pw} {ph} Z"
        self.op(type="shape", shape="path", name="b-area", width=pw, height=ph, x=px, y=top, path=path,
                fill="alpha(@renewable, 0.22)")
        # second area for solar + wind
        pts2 = [pt(i, v) for i, v in enumerate(d["solar_wind"])]
        path2 = f"M0 {ph} " + " ".join(f"L{x:.1f} {y:.1f}" for x, y in pts2) + f" L{pw} {ph} Z"
        self.op(type="shape", shape="path", name="b-area2", width=pw, height=ph, x=px, y=top, path=path2,
                fill="mix(@solar, @background, 45%)")
        # lines drawn with the pen (padded so the stroke is not clipped at the layer edge)
        pad = 8
        for nm, series, colr in (("b-line", pts, "@renewable"), ("b-line2", pts2, "@solar")):
            self.op(type="pen", name=nm, points=[[x + pad, y + pad] for x, y in series], smooth=False,
                    stroke=colr, stroke_width=5, fill="transparent", x=px - pad, y=top - pad, width=pw + 2 * pad, height=ph + 2 * pad)
        # end-point dots and direct labels (instead of a separate legend for this chart)
        for nm, series, colr, label, vals in (("b-end", pts, "@renewable", "All renewables", d["renewables"]),
                                              ("b-end2", pts2, "@solar", "Solar + wind", d["solar_wind"])):
            x, y = series[-1]
            self.op(type="shape", shape="ellipse", name=nm, width=18, height=18, x=round(px + x - 9), y=round(top + y - 9),
                    fill=colr, stroke="@background", stroke_width=3)
            self.text(f"{nm}-v", f"{vals[-1]:.1f}%", "lead", font="dm-sans-700")
            self.op(type="constrain", target=f"{nm}-v", constraints={"left": f"{nm}.right+12", "bottom": f"{nm}.center-y+2"})
            self.text(f"{nm}-t", label, "caption", color="@muted")
            self.op(type="constrain", target=f"{nm}-t", constraints={"left": f"{nm}-v.left", "top": f"{nm}-v.bottom+2"})
        # annotations with leader lines
        for k, (idx, series, note) in enumerate(d["notes"]):
            src = pts if series == "renewables" else pts2
            x, y = src[idx]
            ax, ay = px + x, top + y
            lead = 150 if series == "renewables" else 100
            ty = ay - lead
            self.op(type="shape", shape="ellipse", name=f"b-n{k}-dot", width=14, height=14, x=round(ax - 7), y=round(ay - 7),
                    fill="@background", stroke="@ink", stroke_width=3)
            y0, y1 = sorted([ay, ty])
            self.op(type="pen", name=f"b-n{k}-lead", points=[[3, 0], [3, y1 - y0]], smooth=False, stroke="@ink", stroke_width=2,
                    fill="transparent", x=round(ax - 3), y=round(y0), width=6, height=round(y1 - y0))
            self.text(f"b-n{k}-t", note, "caption", color="@ink", font="dm-sans-700")
            self.op(type="style-apply", target=f"b-n{k}-t", name="tight", kind="paragraph")
            if lead > 0:
                self.op(type="constrain", target=f"b-n{k}-t", constraints={"left": f"b-n{k}-lead.right+8", "top": f"b-n{k}-lead.top-2"})
            else:
                self.op(type="constrain", target=f"b-n{k}-t", constraints={"left": f"b-n{k}-lead.right+8", "bottom": f"b-n{k}-lead.bottom+2"})
        self.flush()
        # only unreferenced layers go in the group: constraints must stay among siblings
        members = [*b_grid, "b-base", "b-area", "b-area2", "b-line", "b-line2"]
        self.op(type="group", name="b-plot", targets=members)
        self.flush()
        self.b_bottom = top + ph + 60

    # ---------------------------------------------------------------- donut + isotype
    def donut(self):
        d = self.d
        sec = self.b_bottom + 110
        self.op(type="guide", name="sec-c", axis="y", position=sec)
        self.section_head("c", "03", "Today's power mix",
                          f"{d['region']} electricity mix, 2025", sec, 1, 6, style="title")
        self.section_head("d", "04", "Every hundred homes",
                          "Each house = 1% of 2025 generation", sec, 7, 12, style="title")
        self.flush()
        top = sec + 170
        R, r = 250, 150
        size = 2 * R
        cx = cy = R
        total = sum(v for _, v, _ in d["mix"])
        a = 0.0
        names = []
        gap = 0.9  # degrees of paper between segments
        for i, (label, v, sw) in enumerate(d["mix"]):
            a0, a1 = a + gap / 2, a + 360 * v / total - gap / 2
            a += 360 * v / total
            large = 1 if (a1 - a0) > 180 else 0

            def P(rad, ang):
                t = math.radians(ang - 90)
                return cx + rad * math.cos(t), cy + rad * math.sin(t)

            (x0, y0), (x1, y1) = P(R, a0), P(R, a1)
            (x2, y2), (x3, y3) = P(r, a1), P(r, a0)
            path = (f"M{x0:.2f} {y0:.2f} A{R} {R} 0 {large} 1 {x1:.2f} {y1:.2f} "
                    f"L{x2:.2f} {y2:.2f} A{r} {r} 0 {large} 0 {x3:.2f} {y3:.2f} Z")
            nm = f"c-seg{i}"
            self.op(type="shape", shape="path", name=nm, width=size, height=size, x=col_x(1), y=top, path=path, fill=f"@{sw}")
            names.append(nm)
        renew = sum(v for _, v, sw in d["mix"] if sw in ("solar", "wind", "hydro", "other"))
        self.text("c-center", f"{renew:.1f}%", "headline", font="heading")
        self.op(type="constrain", target="c-center", constraints={"center-x": f"canvas.left+{col_x(1) + R:.0f}", "center-y": f"canvas.top+{top + R - 14:.0f}"})
        self.text("c-center-t", "renewable", "caption", color="@muted", font="dm-sans-700")
        self.op(type="constrain", target="c-center-t", constraints={"center-x": "c-center.center-x", "top": "c-center.bottom+4"})
        # legend: swatch + label + value rows, distributed with a fixed gap
        rows = []
        for i, (label, v, sw) in enumerate(d["mix"]):
            ly = top + 40 + i * 64
            lx = col_x(1) + size + 48
            self.op(type="shape", shape="rounded-rectangle", name=f"c-lg{i}-sw", width=22, height=22, radius=5, x=lx, y=ly + 4,
                    fill=f"@{sw}", stroke="alpha(@ink, 0.25)" if sw == "other" else "transparent", stroke_width=1 if sw == "other" else 0)
            self.text(f"c-lg{i}-l", label, "caption", x=lx + 34, y=ly, color="@muted")
            self.text(f"c-lg{i}-v", f"{v:.1f}%", "body", x=lx + 34, y=ly + 20, font="dm-sans-700")
            self.op(type="group", name=f"c-lg{i}", targets=[f"c-lg{i}-sw", f"c-lg{i}-l", f"c-lg{i}-v"])
            rows.append(f"c-lg{i}")
        self.flush()
        self.op(type="distribute", targets=rows, axis="vertical", gap=18)
        self.op(type="group", name="c-legend", targets=rows)
        self.flush()
        self.op(type="group", name="c-donut", targets=names)
        self.op(type="group", name="donut-block", targets=["c-donut", "c-center", "c-center-t", "c-legend"])
        self.op(type="constrain", target="donut-block", constraints={"left": "guide:g-x1-start.left", "top": "guide:sec-c.top+170"})
        self.flush()
        self.c_top = top
        self.c_size = size

    def isotype(self):
        d = self.d
        top = self.c_top
        # 100 units, allocated with largest-remainder rounding
        raw = [(sw, v) for _, v, sw in d["mix"]]
        total = sum(v for _, v in raw)
        floors = [(sw, int(v * 100 / total), v * 100 / total - int(v * 100 / total)) for sw, v in raw]
        left = 100 - sum(f for _, f, _ in floors)
        order = sorted(range(len(floors)), key=lambda i: -floors[i][2])
        counts = [f for _, f, _ in floors]
        for i in order[:left]:
            counts[i] += 1
        seq = []
        for (sw, _), c in zip(raw, counts):
            seq += [sw] * c
        pitch = ISO_PITCH
        icon = 46
        house = "M23 1 L45 20 L40 20 L40 45 L28 45 L28 32 L18 32 L18 45 L6 45 L6 20 L1 20 Z"
        x0 = col_x(7) + 14
        names = []
        k = 0
        for row in range(10):
            cells = seq[row * 10:(row + 1) * 10]
            c = 0
            while c < 10:
                sw = cells[c]
                run = 1
                while c + run < 10 and cells[c + run] == sw:
                    run += 1
                nm = f"d-r{row}-{c}"
                self.op(type="shape", shape="path", name=nm, width=icon, height=icon, x=x0 + c * pitch, y=top + 4 + row * pitch,
                        path=house, fill=f"@{sw}")
                names += self.repeat(nm, run, dx=pitch) if run > 1 else [nm]
                c += run
                k += 1
        self.flush()
        self.op(type="group", name="d-grid", targets=names)
        # mini key under the grid -- reuse the same swatches in a single row
        renew = sum(c for (sw, _), c in zip(raw, counts) if sw in ("solar", "wind", "hydro", "other"))
        self.text("d-note", f"{renew} of 100 houses run on renewables;\n"
                  f"{counts[-1]} still burn coal, gas or oil.", "body", font="dm-sans-700")
        self.op(type="style-apply", target="d-note", name="tight", kind="paragraph")
        self.op(type="constrain", target="d-note", constraints={"left": "d-grid.left", "top": "d-grid.bottom+28"})
        self.flush()
        self.counts = counts

    # ---------------------------------------------------------------- footer
    def footer(self):
        d = self.d
        content_bottom = max(self.c_top + self.c_size, self.c_top + 4 + 10 * ISO_PITCH + 100)
        self.footer_y = content_bottom + 120
        self.height = self.footer_y + 260
        # trim the canvas to the content; guides stay absolute and constraints reflow
        self.op(type="canvas", width=W, height=self.height)
        self.op(type="guide", name="footer", axis="y", position=self.footer_y)
        self.op(type="shape", shape="rectangle", name="f-rule", width=round(span(1, 12)), height=1, fill="@rule")
        self.op(type="constrain", target="f-rule", constraints={"left": "guide:g-x1-start.left", "top": "guide:footer.top"})
        self.text("f-note", "*  " + d["source"], "caption", color="@muted")
        self.op(type="text-layout", target="f-note", width=round(span(1, 8)), height=60)
        self.op(type="constrain", target="f-note", constraints={"left": "guide:g-x1-start.left", "top": "f-rule.bottom+24"})
        self.text("f-method", "Method: shares of annual generation (TWh). Isotype rounded with the largest-remainder method.",
                  "caption", color="@muted")
        self.op(type="text-layout", target="f-method", width=round(span(1, 8)), height=60)
        self.op(type="constrain", target="f-method", constraints={"left": "guide:g-x1-start.left", "top": "f-note.bottom+14"})
        self.text("f-brand", "VIXL / FIELD NOTES", "caption", color="@ink", font="dm-mono-500")
        self.op(type="constrain", target="f-brand", constraints={"right": "guide:g-x12-end.left", "top": "f-rule.bottom+24"})
        self.text("f-palette", "Palette: Okabe–Ito (colour-blind safe)", "caption", color="@muted")
        self.op(type="constrain", target="f-palette", constraints={"right": "guide:g-x12-end.left", "top": "f-brand.bottom+10"})
        self.flush()

    # ---------------------------------------------------------------- social crop
    def social(self):
        """1080x1080 artboard showing the donut block, using a comp for the alternative arrangement."""
        self.text("s-eyebrow", "${eyebrow}", "caption", color="@accent-text", font="dm-mono-500")
        self.text("s-title", f"Where {self.d['region'].lower() if self.d['region'] != 'World' else 'the world'}'s power comes from",
                  "title", font="heading")
        self.text("s-foot", "2025 electricity mix  ·  illustrative data  ·  vixl field notes", "caption", color="@muted")
        for nm in ("s-eyebrow", "s-title", "s-foot"):
            self.op(type="hide", target=nm)
        self.flush()
        self.op(type="comp-save", name="poster")
        for nm in ("s-eyebrow", "s-title", "s-foot"):
            self.op(type="show", target=nm)
        self.op(type="constrain", target="s-eyebrow", constraints={"left": "canvas.left+80", "top": "canvas.top+80"})
        self.op(type="constrain", target="s-title", constraints={"left": "canvas.left+80", "top": "s-eyebrow.bottom+18"})
        self.op(type="unconstrain", target="donut-block")  # constrain merges per key; clear the poster anchors
        self.op(type="constrain", target="donut-block", constraints={"center-x": "canvas.center-x", "top": "s-title.bottom+90"})
        self.op(type="constrain", target="s-foot", constraints={"left": "canvas.left+80", "bottom": "canvas.bottom-64"})
        self.op(type="comp-save", name="social")
        self.op(type="comp-apply", name="poster")
        self.op(type="artboard", name="social", width=1080, height=1080, background="@background",
                targets=["donut-block", "s-eyebrow", "s-title", "s-foot"])
        self.flush()

    def build(self):
        self.setup()
        self.header()
        self.bar_chart()
        self.line_chart()
        self.donut()
        self.isotype()
        self.footer()
        self.social()
        return self.p


# --------------------------------------------------------------------------------------
# QA helpers
# --------------------------------------------------------------------------------------
def qa(p, slug, n_rows, report, height):
    r = {}
    # spacing: KPI cards, bar rows, legend rows
    r["kpi_cards"] = p.measure_spacing(targets=["kpi0", "kpi1", "kpi2"], axis="horizontal", expected=GUTTER, tolerance=1)
    r["bars"] = p.measure_spacing(targets=[f"a-bar{i}" for i in range(n_rows)], axis="vertical", expected=18, tolerance=0)
    r["donut_legend"] = p.measure_spacing(targets=[f"c-lg{i}" for i in range(6)], axis="vertical", expected=18, tolerance=0)
    # Label boxes have different heights (descenders), so equal *edge* gaps are not expected here;
    # the bars themselves carry the rhythm.
    r["axis_labels"] = p.measure_spacing(targets=[f"b-x{i}" for i in range(11)], axis="horizontal", tolerance=12)
    r["section_c_heads"] = p.measure_spacing(targets=["c-title", "d-title"], axis="horizontal")
    rules = [
        "canvas.width == 1600",
        f"canvas.height == {height}",
        "text.f-note.font-size >= 14",
        "layer.kpis.bounds within canvas",
        "layer.a-plot.bounds within canvas",
        "layer.b-plot.bounds within canvas",
        "layer.donut-block.bounds within canvas",
        "layer.d-grid.bounds within canvas",
        "layer.f-palette.bounds within canvas",
        "layer.legend-a.exists",
    ]
    from vixl.validation import validate

    r["validate"] = validate(p, rules=rules)
    # validate() also adds a bounds rule for EVERY layer; the decorative sun/rays bleed off the top on purpose.
    bleed = {"layer.sun.bounds within canvas", "layer.rays.bounds within canvas"}
    r["validate_excluding_bleed"] = all(c["passed"] or c["severity"] == "warning" or c["rule"] in bleed
                                        for c in r["validate"]["checks"])
    # Documented mismatch: font-size assertions read the layer's own size, not its linked character style.
    r["font_size_style_mismatch"] = {
        "style_size": p.state["character_styles"]["poster-title"]["size"],
        "layer_size": p.layer("title")["size"],
        "assert text.title.font-size >= 120": validate(p, rules=["text.title.font-size >= 120"])["checks"][-1]["passed"],
    }
    import time

    timings = {}
    t = time.time()
    # A poster is read at full size, so legibility is judged at a 1080 px "thumbnail", not 320 px.
    r["check"] = p.check(checks=["bounds", "overlap", "safe_area", "legibility", "color_vision"], safe_area=64,
                         thumbnail_width=1080)
    timings["check_without_contrast"] = round(time.time() - t, 1)
    # Contrast measures each text layer against a fresh render (~10-20 s per layer on this
    # 1600 px-wide poster), so it is run on a representative subset of text layers.
    contrast_targets = ["eyebrow", "title", "deck", "kpi0-cap", "a-sub", "a-name0", "a-ref-t", "b-yl0",
                        "b-n0-t", "c-lg0-l", "d-note", "f-note"]
    t = time.time()
    r["check_contrast"] = p.check(checks=["contrast"], targets=contrast_targets)
    timings["contrast_subset"] = round(time.time() - t, 1)
    t = time.time()
    r["check_social"] = p.check(artboard="social", comp="social", checks=["bounds", "overlap", "color_vision"])
    timings["check_social"] = round(time.time() - t, 1)
    r["timings"] = timings
    r["spacing_social"] = p.measure_spacing(targets=["s-eyebrow", "s-title"], axis="vertical", artboard="social", comp="social")
    report[slug] = r
    summary = {
        "spacing": {k: r[k]["passed"] for k in ("kpi_cards", "bars", "donut_legend", "axis_labels")},
        "validate": r["validate"]["valid"],
        "validate_excluding_bleed": r["validate_excluding_bleed"],
        "failed_rules": [c["rule"] for c in r["validate"]["checks"] if not c["passed"]],
        "check": {"passed": r["check"]["passed"], "errors": r["check"]["errors"], "warnings": r["check"]["warnings"]},
        "contrast": {"passed": r["check_contrast"]["passed"], "errors": r["check_contrast"]["errors"]},
        "timings": r["timings"],
        "check_social": {"passed": r["check_social"]["passed"], "errors": r["check_social"]["errors"],
                         "warnings": r["check_social"]["warnings"]},
    }
    print("  QA:", json.dumps(summary))
    return r


def series_separation(p):
    """Our own colour-vision test: min pairwise distance of the data swatches after simulation.
    vixl's colour_vision check only covers text, so chart fills are measured here."""
    from PIL import Image

    from vixl.colors import resolve_expression, to_rgba8

    keys = ["solar", "wind", "hydro", "other", "nuclear", "fossil", "renewable"]
    swatches = p.state["swatches"]

    def resolve(c):
        return to_rgba8(resolve_expression(c, swatches))[:3]

    cols = {k: resolve(swatches[k]) for k in keys}
    out = {}
    for kind in ("normal", "deuteranopia", "protanopia", "tritanopia"):
        img = Image.new("RGBA", (len(keys), 1))
        for i, k in enumerate(keys):
            img.putpixel((i, 0), tuple(int(v) for v in cols[k]) + (255,))
        sim = img if kind == "normal" else simulate_vision(img, kind)
        px = [sim.getpixel((i, 0))[:3] for i in range(len(keys))]
        worst = None
        donut = keys[:6]
        for i in range(len(donut)):
            for j in range(i + 1, len(donut)):
                dist = math.dist(px[i], px[j])
                if worst is None or dist < worst[0]:
                    worst = (round(dist, 1), donut[i], donut[j])
        out[kind] = worst
    return out


# --------------------------------------------------------------------------------------
def main():
    report = {}
    built = {}
    draft = "--draft" in sys.argv  # layout iteration: world PNG only
    for slug in (("world",) if draft else ("world", "europe")):
        print(f"building {slug} ...")
        poster = Poster(DATASETS[slug])
        p = poster.build()
        built[slug] = (p, poster)
        p.checkpoint("finished")
        p.save(OUT / f"infographic-{slug}.vixl")
        p.export(OUT / f"infographic-{slug}.png")
        if draft:
            return
        qa(p, slug, poster.n_rows, report, poster.height)

    p, poster = built["world"]
    # deuteranopia simulation + a scaled preview for the README
    p.export(OUT / "infographic-world-deuteranopia.png", simulate="deuteranopia", scale=0.5)
    p.export(OUT / "infographic-world-preview.png", scale=0.5)
    built["europe"][0].export(OUT / "infographic-europe-preview.png", scale=0.5)
    # social crop from the artboard + comp
    p.export(OUT / "social-donut-1080.png", artboard="social", comp="social")
    built["europe"][0].export(OUT / "social-donut-europe-1080.png", artboard="social", comp="social")
    # variables-only re-render (no regeneration): different edition line / title
    p.export(OUT / "infographic-world-variant-title.png", scale=0.5,
             variables={"title": "Ten Years of\nCleaner Power", "eyebrow": "SPECIAL REPRINT  /  DATA DESK"})

    # vector exports
    exports = {}
    try:
        p.export(OUT / "infographic-world-strict.svg", svg_policy="strict")
        exports["svg_strict"] = "ok"
    except VixlError as e:
        info = e.as_dict()
        exports["svg_strict"] = {"error": info.get("error"), "message": info.get("message"),
                                 "fallbacks": (info.get("details") or info).get("fallbacks")}
    p.export(OUT / "infographic-world.svg")
    # Same poster with repeats expanded into ordinary shapes: strict SVG then succeeds.
    vec = Poster(DATASETS["world"], expand_repeats=True).build()
    try:
        vec.export(OUT / "infographic-world-strict.svg", svg_policy="strict")
        exports["svg_strict_expanded"] = "ok"
    except VixlError as e:
        exports["svg_strict_expanded"] = e.as_dict()
    exports["layer_count"] = {"repeat": len(p.state["layers"]), "expanded": len(vec.state["layers"])}
    print("  strict SVG (expanded repeats):", exports["svg_strict_expanded"], exports["layer_count"])
    p.export(OUT / "infographic-world.html")
    p.export(OUT / "infographic-world.pdf")
    p.export(OUT / "infographic-world-cmyk.pdf", color_space="cmyk", ink_limit=300)
    report["exports"] = exports
    report["series_separation"] = series_separation(p)
    print("  strict SVG:", json.dumps(exports["svg_strict"])[:600])
    print("  colour separation:", report["series_separation"])

    # The same assertions through the CLI (rules must be a JSON file; spacing --check exits non-zero on mismatch)
    import subprocess

    rules_file = OUT / "qa-rules.json"
    rules_file.write_text(json.dumps(["layer.kpis.bounds within canvas", "layer.donut-block.bounds within canvas",
                                      "text.title.font-size >= 120"]))
    cli = {}
    for label, args in {
        "validate": ["validate", "--rules", str(rules_file)],
        "spacing_bars": ["spacing", "--targets", *[f"a-bar{i}" for i in range(poster.n_rows)], "--axis", "vertical",
                         "--expected", "18", "--tolerance", "0", "--check"],
        "spacing_kpis": ["spacing", "--targets", "kpi0", "kpi1", "kpi2", "--axis", "horizontal", "--expected", "32", "--check"],
    }.items():
        res = subprocess.run(["vixl", "--json", "-p", str(OUT / "infographic-world.vixl"), *args], capture_output=True, text=True)
        cli[label] = {"exit": res.returncode, "passed": '"passed": false' not in res.stdout and res.returncode == 0}
    report["cli"] = cli
    print("  CLI QA:", cli)
    (OUT / "qa-report.json").write_text(json.dumps(report, indent=2, default=str))
    shutil.rmtree(OUT / "_fontcache", ignore_errors=True)
    for f in OUT.glob("_resources.json"):
        f.unlink()
    for f in sorted(OUT.iterdir()):
        print(f"  {f.name:45s} {f.stat().st_size / 1024:8.0f} KB")


if __name__ == "__main__":
    main()
