"""One registry of named craft guidance.

``vixl_guide(brief=NAME)``, ``vixl_resource_get(kind="guidance", name=NAME)``, ``vixl_resources_list``,
the guidance names a ``vixl_guide`` kind points at and the ``guidance`` that ``vixl_capabilities`` lists
all read ``GUIDANCE``; user additions (``vixl_resource_add``) join it through ``resources.catalog``.
"""

GUIDANCE = {
    "overall": "Choose a clear hierarchy, align related elements, use consistent spacing, preserve readable contrast, inspect at delivery size, and measure before exporting.",
    "minimal": "Use generous negative space, a small palette, few type sizes, and a single focal point. Prefer simple geometry and deliberate alignment.",
    "editorial": "Establish headline, body and caption hierarchy. Use a coherent grid, restrained accents, and consistent margins. Keep body text readable.",
    "playful": "Use energetic accents and rounded forms while preserving hierarchy, contrast, and consistent spacing.",
    "meme": "Memes are layouts plus your own pictures: layout-apply meme-top-bottom, meme-caption-above, meme-comparison, meme-labelled, meme-reaction or meme-four-panel, with image (or images, one per panel) set to assets you have the rights to use; Vixl ships no meme images. Keep captions to a few words: stroked captions are uppercase, white with a black stroke, and shrink to fit their box (uppercase=false keeps the case). For the Impact look install an OFL condensed face, e.g. vixl_font_install('Anton', role='heading') or display_font, never a non-OFL font. Check, preview at phone size, export PNG or JPEG. GIF: start from meme-reaction, animate the caption (animate-preset pop-in or shake, or motion), preview with vixl_timeline_preview and export with vixl_export_timeline to .gif (keep it short, 2-4 s, and loop).",
    "logo": "Start on a transparent canvas. Use simple silhouettes, test small sizes and monochrome, and export SVG when scalable geometry is needed.",
    "pixel-art": "Use an intentional limited palette, integer positions and crisp nearest-neighbor exports. Keep sprite timing and silhouettes readable.",
    "typography": "Pick a pairing before placing text (vixl font pairings; font pair NAME), never ship the proofing fallback, and use one or two families with fixed roles: contrast in classification or a superfamily, matched x-heights, heading 600–800 over body 400. Use a modular type scale (type-scale). Keep body lines 45–75 characters, line height about 1.4 for body and 1.1 for headlines, and create hierarchy with size and weight before color. Align text to a shared edge.",
    "color": "Assign roles before picking hues: background, surface, ink, muted, accent. Keep body text at 4.5:1 or better, large text and graphics at 3:1, and use the accent sparingly for the one thing that matters. Check designs with color-vision simulation; never rely on hue alone.",
    "layout": "Start from a grid or a proportional system (thirds, golden section, modular columns). Give each piece of content one job, group related items by proximity, align to edges, keep consistent margins on a spacing unit, and leave space empty on purpose.",
    "accessibility": "Meet WCAG contrast (4.5:1 text, 3:1 large text and UI), keep text at legible sizes for the delivery medium, never encode meaning only in color, and keep important content inside safe areas.",
    "print": "Design at the final physical size and resolution (300 dpi for most print). Extend backgrounds into the bleed, keep text inside the safe (live) area, keep total ink coverage under about 300%, avoid type below 6 pt, and export CMYK with the printer's ICC profile when one is provided.",
    "icon": "Build on a square grid with a central keyline area, use one recognizable silhouette, test at 16–32 px and in monochrome, avoid fine detail and text, and export every required size from one master.",
    "motion": "Animate to explain, not decorate. Use 150–500 ms for interface-scale moves and up to about 1 s for entrances, ease out when entering and ease in when leaving, stagger related elements, and keep a still frame that reads on its own.",
    "image-rights": "Use an image from the web only when you have the right to: your own or the client's work, a stated license (Creative Commons, Unsplash, Pexels, public domain) or written permission. Import it with url= so the layer records the source URL, fetch time and sha256, and pass credit and license (e.g. credit 'Photo: Ana Ruiz / Unsplash', license 'CC BY 4.0'); inspect shows them and dependencies lists them as attributions. Honour license terms: CC BY needs visible credit, NC forbids commercial use, ND forbids edits. When rights are unclear, use a placeholder frame or a generated image instead, and never strip a watermark.",
    "brush": "Choose the brush for the medium: ink or fineliner for line art, marker for bold strokes, watercolor or airbrush for soft washes, chalk, charcoal or crayon for texture. Vary pressure and taper for life, and keep strokes on their own paint layers so they stay editable.",
"natural-color-light": """Natural color and lighting: working reference
Color is reflected illumination, not a fixed label. A foliage palette includes cool occlusion, muted local green, warm transmitted leaf edges and sky-reflecting highlights. Skin varies continuously in value, chroma and undertone; choose from observation and never infer identity from a swatch. Stone/wood/water depend on roughness, view angle and surrounding light. Use natural_palette or vixl_color natural with subject skin/foliage/sky/earth/water/stone and day/dawn/dusk/night. These are illustrative sRGB starting points, not measured material reflectances.
Plan one dominant light direction. A directional source gives approximately parallel cast shadows; point-light shadows diverge from the source; a large area light broadens penumbrae. Ambient and bounced light lift shadows; they do not erase contact occlusion. Keep a lit matte patch usually lighter than its own unlit counterpart under the same exposure; luminous objects, fill lights, local-color differences and specular reflection are exceptions. Low sun casts long shadows; noon short shadows; overcast creates broad soft modeling. Color temperature describes the illuminant, not how every painted object must look. Warm direct light can accompany cooler sky-filled shadows, but colored surroundings can reverse that relation. Simultaneous contrast means the same gray appears different on light/dark or warm/cool neighbors; inspect in context. For depth, move distant values/chroma toward the atmosphere and reduce edge contrast.
Recipes: single-source scene: choose a five-value palette, gradient background, local-color shape, clipped gradient shading, and shadow style directed away from the source. Key/fill: keep the fill weaker and broader; render both separately before blending. Rim light: duplicate the silhouette behind the subject, expand/highlight its light-facing edge, use screen/add-style compositing sparingly; avoid an even halo unless backlit. Glow: duplicate the emissive shape, blur it on its own layer, screen-blend, retain a bright small core and illuminate nearby surfaces. Keep cast shadows separate so direction and softness stay editable.
Verification: use guide-check with kind lighting, light [x,y], objects [{position:[x,y],shadow:[dx,dy],lit:'#...',shade:'#...'}]. It flags shadows pointing toward a point source and darker lit patches. These are scene-metadata heuristics; explain exceptions. Inspect grayscale and cropped final-size previews.
References: CIE International Lighting Vocabulary https://cie.co.at/e-ilv ; PBRT 4e, Light Sources and Color and Radiometry https://pbr-book.org/4ed/Light_Sources ; Josef Albers, Interaction of Color (1963), contextual color exercises. These sources establish principles, not numeric promises for the palettes.
""",
"anatomy-proportions": """Anatomy and appearance: construction reference
Use a gesture line and balance over support before contour. Torso masses are rib cage and pelvis linked by a flexible spine; shoulder girdle can move independently from the pelvis. Upper/lower arm and thigh/shin are similar but not identical lengths. Elbows and knees hinge, forearms pronate/supinate, and ball joints allow multiple axes: a 2D rig angle is not a complete anatomical joint orientation. Broad adult art convention: 7–8 heads tall; teen about 6.5–7.5; child about 5–6.5; toddler about 4–5. These overlapping ranges are construction aids, not health or appearance standards. Stylized figures can intentionally depart from them. Adult shoulder width often about 2–3 head widths. Pubic region is roughly halfway down standing height; elbow near waist, wrist near hip, fingertips near mid-thigh. Variation, pose and perspective dominate exact ratios.
Face: in a neutral front view eyes lie near half skull height (hair excluded); nose base between eyes/chin, mouth between nose/chin. The eye-to-eye gap is roughly one eye width as a starting convention, never a rule for every face. Establish cranium/jaw planes, place a centerline that wraps the form, then adapt actual asymmetry and feature spacing. Hands: palm mass plus thumb wedge and four finger arcs; knuckles and fingertips follow staggered arcs, not a straight rake. Hair is grouped volumes over the skull with parting and gravity. Clothing folds start at tension/compression/support, with thickness changing edge softness.
Represent diverse ages, body sizes, facial structure, skin tones, hair textures, mobility and clothing. Do not equate one default template with normality. Animals: use species-specific spine/ribcage/pelvis masses, limb joint direction, digitigrade/plantigrade stance and reference. Wings, fins, exoskeletons and plants require different construction; do not reuse human joint limits blindly.
Approximate adult illustration range reference (degrees, flexion coordinate conventions): elbow flexion 0–150, knee flexion 0–140, shoulder flexion 0–180, hip flexion 0–120, wrist flexion 0–80. Human variation and active/passive measurement protocols matter; these are loose illustration sanity bands, not clinical norms or medical judgments. The cited CDC study reports measured passive ranges and confidence intervals by age and sex. Check only labeled anatomical flexion measures, not arbitrary sprite rotation.
Workflow: figure-plan returns named editable head, torso, pelvis, arm and leg parts from head units and body width, plus a parts map. Apply its operations, adjust proportions from references, establish pivot locations, then use character rigging. guide-check kind anatomy accepts head_units, style realistic/stylized, joints [{name,angle}], and limbs [{name,upper,lower}]. It reports only egregious ratios and labeled flexion violations.
References: OpenStax Anatomy and Physiology 2e, chapters 7–9 (skeleton/joints) https://openstax.org/books/anatomy-and-physiology-2e/pages/9-5-types-of-body-movements ; CDC joint range-of-motion reference tables https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index_1715172647.html ; Andrew Loomis, Figure Drawing for All It's Worth (1943), art proportion conventions.
""",
"illustration-perspective": """Illustration style and perspective reference
Choose shape language and value hierarchy before texture. Large readable silhouettes, grouped dark/light masses, overlap and a deliberate focal contrast work across styles. Check the subject as a black silhouette at thumbnail size; avoid important appendages merging with the torso. Three grouped values usually communicate better than many unrelated midtones. Eye flow follows contrast, edges, faces and implied lines; secondary accents should lead back to the focal point.
Style recipes mapped to Vixl operations: flat = shape/pen, 3–5 palette roles, minimal gradients; line-and-wash = pen or paint with ink plus translucent watercolor/ink-wash drawn-texture; cutout = irregular shapes + paper pattern-fill and small directional shadows; painterly = paint with dry-brush/charcoal, broad masses before edges; ink = brush-pen outlines + hatching or stipple texture; pencil/crayon = paint preset plus drawn-texture and pressure/jitter, kept as separate overlays. pattern-stroke paints tiled material along a path. Inspect texture against the plain original and at intended delivery scale.
Perspective: horizon is eye level, including outside the crop. One point: front-facing planes retain parallel edges; receding edges share one vanishing point. Two point: two horizontal edge families converge to two points on one horizon. Three point: verticals also converge above/below the horizon. Wide field of view exaggerates near/far size; moving camera and changing focal length are different actions. Foreshortened limbs must shorten in projection; overlapping cross-contours and joint landmarks explain depth. Use overlap, relative size, edge softness and atmospheric contrast together. A long lens can compress depth; orthographic/isometric art deliberately avoids convergence.
Workflow: perspective-guides spec {width,height,horizon,points:1|2|3,depths:[positive distances],reference_size,reference_depth} returns a perspective grid operation and scale-by-depth sizes: size = reference_size * reference_depth / depth. Apply guide operations; place objects with a common ground plane and camera. guide-check kind perspective accepts horizon and vanishing points (only horizontal families), and objects {depth,size}; normalized size*depth should agree for equally sized objects. kind illustration accepts values [0..1] and silhouette_contrast [0..1] measured against the background. Checks are advisory and conditional, not automatic aesthetic judgments.
References: James Gurney, Imaginative Realism (2009), composition/value construction; Ernest R. Norling, Perspective Made Easy (1939), vanishing points/horizon; PBRT 4e, Cameras and Film https://pbr-book.org/4ed/Cameras_and_Film .
""",
"drawn-textures": """Drawn textures: compare before committing
Use drawn-texture target Shape preset pencil|charcoal|crayon|ink-wash|stipple|hatch. It adds a separate transparent raster overlay clipped to the rendered silhouette and retains the original vector. Set seed for reproducibility, strength 0..1, scale .1..20, jitter 0..1, pressure 0..1 and grain 0..1. Pencil/hatch jitter the line path and vary coverage per stroke; charcoal/wash use low-frequency pooled coverage; stipple scatters marks; crayon/pencil/charcoal interact with paper tooth. Render plain, textured and 200% detail views side by side, then verify at final size: visible tooth at 200% alone is insufficient. For editable hand-drawn outlines use paint pencil/charcoal/crayon/watercolor brush presets with pressure points; a fill overlay does not change the vector's outline geometry. Combine paper pattern-fill under a low-opacity ink wash; use clone-stamp to repeat sampled handmade marks and pattern-define to save a repeat. Inspect a 3x3 tile repeat for seams.
""",
"film-review": """Film review and performance
Before every full export, use film-preview PNG at each shot start/middle/end, at every crossfade midpoint and at extreme camera poses. time/start/end are milliseconds, matching film and timeline specs. PNG seeks directly to its requested frame, including camera crop, transitions and captions. Use shot (zero-based), or start/end, with GIF for a bounded loop (at most 300 frames/80M pixels), MP4/WebM/ZIP for a selected interval; add region [x,y,width,height] in original film pixels for a narrow crop. Do not render an entire film to check one framing change.
film-preview defaults to quality draft; explicit final uses delivery resolution. Draft caps the longest side at 640 and lowers video encoding quality. Static document shots avoid cloning/hashing timeline state each frame. Existing content-addressed disk layer caching preserves unchanged content between runs and shots; changing one layer invalidates its cache dependencies. Render only the changed shot/interval after a local change, then export the full film after approvals. Frame-parallel rendering is not enabled: memory growth and deterministic ordering must be profiled before adding it. The speedup depends on how much work is static, rasterization cost and codec; benchmark a representative draft and final interval, never assume a fixed full-film duration.
Use video-sample with explicit times or interval to produce visible labeled contact sheets; use audio-analyze for unweighted RMS dBFS, clipping, silence, spectral-flux onsets, a heuristic beat estimate and a spectrogram. Pass video event timestamps to events to measure onset timing errors. Numeric checks and spectrograms do not judge musical quality; audition exported audio with an audio-capable model/player if available.
""",
    "natural-motion": "Use anticipation (a small opposing move before effort), weight shift, curved paths, eased starts/stops and delayed secondary motion. Gravity uses y=y0+v0*t+g*t²/2 in pixels/seconds; each bounce loses velocity by restitution (0.5–0.75 is a useful start). Springs need zero initial velocity and damping; do not force an oscillating curve abruptly to its final value. Build a bouncing ball with motion recipe=bounce, then character-cycle walk, then react; inspect contact/extension/recovery poses. Use motion overlap for hair/accessories and stagger only related parts. Check motion findings for linear two-key stops and extreme acceleration; these are review heuristics, not proof of physical correctness. Constant-speed camera travel and impacts can be intentional. Sources: Thomas & Johnston, The Illusion of Life (1981); Richard Williams, The Animator's Survival Kit (2001); Newtonian projectile and damped oscillator equations.",
    "character-rigging": "Create character for a standard torso/head/eyes/brows/mouth/hair/segmented limbs set, or bind existing part layers. Save a reusable portable document template with character-save; character-load gives independent parts, colors, outfit and scale. Set proximal pivots, bone lengths, parent joints and angle limits; character-ik solves a two-bone chain in local pixels. Start walk/run with contact, passing and recovery poses, plant feet with IK, then offset secondary motion. Text lip-sync is approximate: use explicit timed viseme cues from aligned audio for production speech. Validate character and anatomy checks before animation.",
    "cut-paper": "Apply cut-paper to a character/group to add grain/fibers, rough silhouette edges, paper thickness shadows and shallow depth offsets. Start grain 0.04–0.08, roughness 0.3–0.6, thickness 1–3px; avoid heavy grain on small eyes/text. Use 10–12fps held poses with jitter 0–0.4px, pinned proximal limb pivots and constrained character-cycle motion. Review an image at final delivery size, plus two frames inside one hold (they should match) and across a hold boundary. Layer-depth and a slow camera move add parallax; use restrained warm lighting. See examples/build_cut_paper_demo.py.",
    "audio-composition": "Use audio-track with synthesized tones, piano/bell/bass, percussion or whoosh/pop/click/splash; sequence notes with start/duration/MIDI/velocity. Marker names synchronize timeline tracks. Keep peaks below 0dBFS: volume is linear gain, fades are milliseconds, and overlapping notes/tracks sum. WAV imports embed into the project. MP4/WebM timelines and films include the mix; export_audio writes a standalone WAV. Verify numeric peak/RMS/silence/onsets with audio analysis and listen to the result; estimated onsets/tempo do not establish perceptual musical quality.",
    "imperfection": "Imperfection (irregular, tear) makes things look made rather than computed; use it on a few chosen things, not as a finish for the whole document. Use it where the viewer expects a person, a material or an accident: a character or mascot, a sticker, a hand-inked outline, botanical shapes, cut or torn paper, a scatter of leaves or confetti. irregular {targets, seed, strength: subtle|natural|rough} wobbles outlines, jitters vertices, varies stroke weight (pressure) and drifts color, rotation, scale and position across a set; start at subtle, compare previews, then change the seed rather than stacking. tear {target, seed, edges, as: mask|clip|path} rips an edge with a paper rim and fibres, only where something is actually ripped. Do not use it on logos, icons, UI, diagrams, charts, maps or technical drawings; on anything that must align, measure or register (grids, tables, form fields, barcodes, print marks, text baselines); on text (refused); on things under about 20 px; on every layer (keep backgrounds, frames and type clean); twice (organic forms already have naturalness); or to rescue a weak design. A set of copies gets organic placement from irregular with only: [placement, color]. Pair a subtle irregular with a drawn-texture overlay or the sketch, watercolor or paper look for a hand-made finish; the hand-made look applies the wobble as a removable look, and motion recipe line-boil animates it. The result is seeded and stored: remove: true restores the exact source.",
    "scatter": "Scatter and repetition without code. scatter {target: SHAPE, source: [motif layers] or mark: {shape ...}, count or spacing, seed} fills the target's outline with Poisson-disc spaced copies (no grid look); placement: along puts them on its edge, direction normal|tangent|cone|random, anchor: base so blades and tufts grow out of the line. Vary them with rotation_jitter, scale_jitter, position_jitter, colors and tone_variation (OKLab lightness, in tones steps); exclude keeps layers clear. merge: true draws every copy as one path per tone, so hundreds of marks cost a few layers (shape motifs only); without it each copy is a layer in a group, and the layer budget applies. preset: fur grows tufts behind the edge and inner flicks above it in the target's color; the plush look does the same plus a soft gradient, hand-made wobbles outlines with irregular, and organic fur-blob is a ready furry body. Seamless patterns: pattern-scatter {source, width, height, count, seed, background, pattern: NAME} scatters on a wrap-around tile and adds wrapped copies for motifs crossing an edge, then reports seam (seamless_check: edge_error versus interior_variation); pattern-fill with that pattern and tile_variation 0.2-0.4 so the repeat does not read as a grid. Edit a motif, then pattern-scatter {target: TILE} rebuilds it with the same seed. Rows and rings: repeat and radial-repeat take rotation_step, scale_step, opacity_step and seeded rotation/scale/position/opacity jitter, and merge: true for one path. Motion: keyframes {property, sample: {fn: sin|cos|triangle|saw|square|noise, period, amplitude, offset, phase, step_ms, duration}} writes a wave as keys; motion recipe: wiggle (amount, frequency, samples) shakes about a value; recipe: line-boil (fps 8-12, variants 3) redraws vector lines with new irregular seeds per held frame for a hand-drawn boil.",
    "multi-part-objects": "Build an object from parts (a mascot, a character, a vehicle, a prop) as one group, with a subgroup per "
    "joint or sub-assembly (a head with its features, an arm with its hand), so it moves, scales and recolours as a unit; "
    "build in the group's own coordinates and use space: canvas only when placing against the scene. Parts that meet "
    "should overlap by a few pixels rather than abut, so seams do not open at small sizes, on rotation or when a joint "
    "turns: tuck a limb's end under the body and set its pivot inside the overlap. Order parts back to front (far limbs, "
    "body, near limbs, head, features). Outlines: one stroke weight for the whole object, scaled with it; outline the "
    "silhouette, not every internal seam (merge touching parts with pathfinder union, or draw the outline as one shape "
    "behind the fills), and keep inner detail lines thinner than the contour. Keep one light direction and one shadow "
    "colour across parts. To review, preview the object alone with vixl_render_preview(isolate=[group]) and compare "
    "revisions with vixl_render_compare(isolate=...); run vixl_check(checks=[connected]) to find parts that float free of "
    "the body (it also samples animation frames, where swinging limbs come loose); mark a part meant to float (a spark, a "
    "thrown ball) with layer-intent detached_ok. A prop held by a moving part follows it with motion recipe attach. A "
    "part drawn later (a tail added after the dog group exists) joins the object with {type: reparent, targets: [tail], "
    "into: dog}: it stays where it was drawn, and the group keeps its rotation, scale and effects.",
    "looping-motion": "Loops and staggered motion are one motion operation, not hand-written keys. Design the loop first: every track returns to its t=0 value at the loop end, so make duration a whole number of periods (motion period, character-cycle period). Repeating recipes: hover (float), breathing (scale), blink (held closures), wiggle (rotation about the pivot, or any property; samples sets how many keys), orbit, bounce, line-boil (a hand-drawn redraw at fps); one operation moves many targets, and stagger (ms per target) delays each one's start: {type: motion, recipe: hover, targets: [dot-1, dot-2, dot-3], amount: 8, period: 1000, duration: 2000, stagger: 150}. In a seamless loop animate and animate-preset wrap a staggered repeat that would pass the loop end around it; a motion stagger still runs past the end, so check the seam; phase (in cycles, e.g. -0.15 per dot) offsets a target inside the loop instead. For a looping card set {type: timeline-set, loop_mode: seamless}: it warns for any track that ends away from its start, and close: true (on keyframe, animate, animate-preset or motion) appends the start value so the track closes; entrance presets then hold and play back. A spinning motif loops with {type: motion, recipe: spin, turns: 1} or, for a symmetric motif, symmetry: 12 turns it 1/12 of a circle. animate and animate-preset take repeat (or until) and period to cycle without extra operations. character-cycle gives walk, run, idle, ride and react cycles for a rigged character; keyframes writes one property's keys in one operation, or samples them from a wave with sample: {fn: sin|triangle|saw|square|noise, period, amplitude, step_ms}, and hold or step easing holds a value without keys 1 ms apart. Keep the whole message readable at frame 0, keep moving layers off text, set pivots at joints (pivot) before rotating limbs, then check vixl_check(checks=[motion]) and vixl_timeline_preview at the first, middle and last frames (the last should flow into the first).",
    "testing": """Testing a design: why, when, which and how
Why: you cannot look at every pixel, and a preview is a small downsampled picture. Tests measure what a glance misses (text 1 px off the canvas, contrast 4.2:1 instead of 4.5:1, gaps of 20 and 24 px, a forgotten [Label]) and they stay true while later edits pile up, so a fix in one place cannot silently break another. They are cheap, exact and repeatable; a preview is for what tests cannot judge: taste, likeness, mood. Test first, then preview.
When: 1) Before building, turn the brief into requirements and attach them as a suite (suite-set) in the first batch. 2) While building, add check=true and suites=true to vixl_operations_apply so every batch reports its findings and failing rules with the edit. 3) Before every vixl_render_preview, run vixl_check and the suites and fix what fails; preview only a design that passes. 4) Before export, run them once more (with sampling for animation). A failed test means change the design, never loosen the rule; set tolerances before checking, not to make a failure go away.
Choose: vixl_check covers general defects (bounds, overlap, contrast, safe_area, legibility, blanks, placeholders, fonts) and opt-in families for the document type: deck for slides, print for print, color_vision, form with sample=worst, diagram, codes, drawing, connected and character for characters and mascots, motion for animation, guides/alignment, style for a tagged style. Starter suites (vixl_workflow resource-list kind suites; suite-use attaches one) bundle them per type: social-card, composition, slide-deck, logo, motion-loop, character, fillable-form, diagram, print-ready, accessible, delivery, palette, opaque, no-placeholders, containers. Then add rules for what only this brief requires.
Make your own: one rule per requirement, named for the requirement. Requirement to rule kind: 'title reads at thumbnail size' -> contrast {target, minimum 4.5} and text-fit {target, minimum}; 'headline clearly dominates' -> hierarchy {targets [title, subtitle, body], ratio 1.25}; 'cards evenly spaced' -> spacing {targets, axis, expected?}; 'logo 48 px from the edges' -> relation {target logo, to canvas, position inside, minimum 48}; 'caption under the photo, left-aligned' -> relation {target caption, to photo, position below, align [left], maximum 24}; 'price never overlaps the product' -> relation {position apart}; 'keep the top third quiet for the headline' -> ink {region, maximum 0.02}; 'balanced' -> balance {tolerance 0.1} or focal {target, grid thirds}; 'brand red stays brand red' -> color {point or region, expected @brand} or palette; 'exactly three bullets' -> count {target 'bullet-*', minimum 3, maximum 3}; 'headline at most 40 characters', 'must say Terms apply', 'never say free' -> text {target, max_characters 40} / {contains 'Terms apply'} / {forbid '(?i)\\bfree\\b'}; 'at most 3 fonts, images 240 ppi' -> budget {max_fonts 3, min_ppi 240}; 'transparent logo' -> alpha; any fixed value -> property or assert; a finished part that must not change -> suite-capture (unchanged and pixels rules). Use severity warning for preferences (balance, breathing room) so they need review instead of failing. Animation: add sampling {mode: sampled, count: 8} so rules hold at every sampled time; several formats: sampling {artboards: 'all', pages: 'all', comps: [...]} so rules hold on every variant. An approved design: vixl_workflow('suite-infer', {name}) proposes a tolerant suite with what each rule measured; review it before use.
Run: vixl_workflow('check', {suite: NAME or an inline suite}) returns each rule's status and measurements (failed, needs_review, passed); a rule that cannot be measured is needs_review, never a pass. vixl_workflow('act', {operations, suites}) applies a batch only if the suites still pass (repair: true first tries the built-in repairs: fit-text, contrast ink, safe-area nudge). Every result has an outcome: validated means required checks ran and passed with nothing left to review; unvalidated means nothing required was checked. Save a suite you will reuse with resource-save kind suites. Read the failing rule's numbers, fix the design, rerun, then preview. A passing suite proves only its own rules: keep them specific to the brief.""",
}
