"""One-line summaries, per-field descriptions and worked examples for every operation.

``schema.operation_schema`` merges these into each operation's JSON Schema, so
``vixl_operation_schema`` answers "what does this do, what does each field take, and what does
a working call look like" without a failed call or a docs lookup. Descriptions fill only gaps:
a description written next to the field's definition wins. ``tests/test_operation_docs.py``
fails when an operation, field or example is missing here.
"""

from copy import deepcopy

SUMMARIES = {
    "add": "Embed an image as a new raster layer (an embedded asset id from vixl_import_image, or a path in the CLI).",
    "solid": "Add a flat-color rectangle layer, by default covering the canvas (a background).",
    "gradient": "Add a linear, angled or radial gradient layer between two colors or several stops.",
    "text": "Add an editable text layer (auto-sized to its text).",
    "text-set": "Change a whole text layer: content, color, size, font, alignment, spacing or stroke. To style only part of the text (a phrase, range, paragraph, bold/italic) use text-style.",
    "shape": "Add a vector shape layer (rectangle, ellipse, polygon, star, arrow, heart, path …) with fill and stroke.",
    "pen": "Draw an editable Bezier or freehand path from anchor nodes or points.",
    "organic-shape": "Add a simple organic outline (leaf, petal, blob, rose) that regrows with a new seed.",
    "organic": "Grow a living form (flower, tree, fern, jellyfish …) from presets or generator parts and rules.",
    "pathfinder": "Combine shape layers into one: union, subtract or intersect.",
    "frame": "Add an image inside a fixed-size frame that crops or fits it.",
    "replace-contents": "Swap the image in a raster or frame layer, keeping its placement, effects and identity.",
    "paint-layer": "Add an empty paint layer for brush strokes.",
    "paint": "Paint brush strokes (points or an SVG path) on a paint layer; strokes stay editable.",
    "paint-clear": "Remove the last N strokes (or all) from a paint layer.",
    "brush-define": "Save a custom brush as overrides on a built-in brush.",
    "pixel-art": "Add a pixel-art layer from character rows and a palette.",
    "pixel-draw": "Draw a pixel, line, rectangle or flood fill on a pixel layer.",
    "pixel-palette": "Replace the palette of a pixel layer.",
    "rich-text": "Create or replace a text layer from Markdown or spans, with paragraphs, lists and mixed styles.",
    "text-style": "Style part of a text layer: a matched phrase, a character range or paragraphs. To change the layer's content or overall color, size or font use text-set.",
    "text-layout": "Set a text layer's wrapping box, fit-to-box, warp (arc, flag, bulge) or path.",
    "field": "Add a fillable form field (text, checkbox, radio, dropdown, signature …).",
    "field-set": "Change a form field's settings.",
    "form": "Set document-wide form options: tab order, entry font, title and language.",
    "drawing": "Import, clean, vectorize, straighten, smooth, fill, stroke or restyle a hand drawing.",
    "symbol": "Mark a layer as a symbol master that instances can reuse.",
    "symbol-instance": "Place an instance of a symbol master.",
    "adjustment": "Add an adjustment layer that applies effects to everything beneath it.",
    "lookup": "Add a saved LUT color grade to a layer's effect stack (toggle, reorder or remove it like any effect).",
    "lut": "Define a 3D color lookup table.",
    "container-place": "Place a saved container (a reflowing group) from the resource library.",
    "container-reflow": "Re-run a container's flow or grid layout after its content changed.",
    "container-swap": "Swap a placed container for another resource, keeping the placement.",
    "shape-place": "Place a saved shape resource as a shape layer.",
    "remove": "Delete a layer (and a group's children).",
    "hide": "Hide a layer without deleting it.",
    "show": "Show a hidden layer.",
    "raise": "Move a layer up one step in the stack.",
    "lower": "Move a layer down one step in the stack.",
    "top": "Move a layer to the top of its stack.",
    "bottom": "Move a layer to the bottom of its stack.",
    "select-layer": "Make a layer the active layer (the default target).",
    "rasterize": "Bake a layer, with its effects and styles, into pixels.",
    "unconstrain": "Drop a layer's constraints, keeping where it is now.",
    "rename": "Rename a layer.",
    "duplicate": "Copy a layer (and a group's children).",
    "move": "Move a layer to x/y, or by x/y with relative.",
    "resize": "Set a layer's width and/or height.",
    "scale": "Scale a layer by a factor.",
    "rotate": "Rotate a layer by degrees about its center or pivot.",
    "pivot": "Set the point a layer rotates and scales about.",
    "opacity": "Set a layer's opacity from 0 (clear) to 1 (opaque).",
    "blend": "Set a layer's blend mode.",
    "flip": "Mirror a layer horizontally or vertically.",
    "crop": "Crop a raster layer to a rectangle of its source image.",
    "reorder": "Place a layer above or below another in the same group.",
    "align": "Align layers to the canvas, each other or a layer; with a margin.",
    "constrain": "Pin a layer's edges or center to the canvas, a layer or a guide.",
    "distribute": "Space three or more layers evenly along an axis.",
    "group": "Group layers into one transformable layer.",
    "ungroup": "Dissolve a group, keeping its children in place.",
    "clip": "Clip a layer to the shape of a base layer beneath it (or release it).",
    "repeat": "Repeat a layer N times with a per-copy offset and size change (linear).",
    "repeat-blend": "Repeat a layer N times while blending its size and color to an end state.",
    "radial-repeat": "Make N copies of a layer around a center, optionally mirrored (radial symmetry, mandalas, rosettes).",
    "look": "Apply a named finishing look (glow, drop shadow, grain, paper, gradient …) to layers in one step.",
    "layer-style": "Add or remove a layer style: drop shadow, stroke, outer glow, color or gradient overlay.",
    "layer-intent": "Mark a layer as content, decoration, background or the page title, allow intended overlaps, or allow an intentional crop.",
    "path-fit": "Fit a path layer's geometry into its box.",
    "font-fallbacks": "Register fonts used for characters the primary font lacks.",
    "artboard": "Define a named artboard (size, background, variables, viewport) for variants.",
    "comp-save": "Save the layers' visibility, position, opacity and styles as a named comp.",
    "comp-apply": "Restore a saved comp.",
    "canvas": "Set the canvas size (pixels or a named size), background, dpi, orientation or bleed.",
    "select": "Make a selection (rect, ellipse, color, alpha, wand, lasso, path …) that effects and masks use.",
    "mask": "Create, import, invert, enable, disable or delete a layer mask.",
    "effect": "Add a non-destructive effect to a layer by name (brightness, blur, grain, sepia …).",
    "effect-set": "Change an effect's settings by ID or 1-based index.",
    "effect-enable": "Turn an effect on again.",
    "effect-disable": "Turn an effect off without removing it.",
    "effect-remove": "Remove an effect from a layer.",
    "effect-move": "Reorder a layer's effect stack: move one effect to a position, to the top or bottom, or before/after another.",
    "preset-save": "Save a layer's effect stack as a named preset.",
    "preset-apply": "Add a saved effect preset to a layer, optionally overriding amounts.",
    "variable": "Set or delete a document variable used as ${name} in text, colors and images.",
    "swatch": "Define a named color (used as @name) that can build on other swatches.",
    "palette-define": "Define a named palette of 2-256 colors.",
    "palette-apply": "Apply a palette: adds numbered swatches and assigns role swatches (background, ink, accent …).",
    "palette-generate": "Generate swatches from one color: a 50-950 scale or a harmony (complementary, triadic …).",
    "template-apply": "Create layers from a named template with variables.",
    "guidance": "Store or remove a written design guide (brand voice, rules) in the document.",
    "font-register": "Register an imported font by name, and optionally make it the heading or body font.",
    "style-define": "Define a named character or paragraph style.",
    "style-apply": "Apply a named character or paragraph style to a text layer.",
    "style-set": "Tag the document with a design style (swiss, brutalist, art-deco …) for style guidance and checks.",
    "type-scale": "Define character styles caption to display on a modular scale.",
    "layout-apply": "Build a principled layout (hero-statement, app-icon, logo-horizontal …) from copy slots, palette and seed.",
    "guide": "Create or delete a guide: an axis, line, ray, segment, point, circle or path.",
    "grid": "Create a grid system (columns, baseline, thirds, golden, polar, isometric, perspective …) of guides.",
    "place": "Place layers on a guide (at a fraction, spread evenly, at intersections, turned to the tangent), or "
             "within a shape's content box (a bubble's body, a badge) with an anchor and margin.",
    "snap": "Move near-miss layers onto guides and points, and straighten near-miss angles.",
    "frame-save": "Save the current canvas as a named animation frame.",
    "frame-apply": "Load a saved animation frame onto the canvas.",
    "frame-delete": "Delete a saved animation frame.",
    "animation-set": "Set the frame loop count and order for a frame animation.",
    "timeline-set": "Set the timeline duration, fps and loop, or clear it.",
    "keyframe": "Set a keyframe value for a layer property at a time.",
    "keyframe-remove": "Remove keyframes of a property (or at a time).",
    "animate": "Animate a property between two values over a time range.",
    "animate-preset": "Apply a ready-made motion (fade-in, slide, pop, bounce …) to layers.",
    "marker": "Add or delete a named timeline marker.",
    "suite-set": "Attach a check suite (assert rules) to the document under a name.",
    "suite-capture": "Capture a structural and pixel baseline of layers as a suite.",
    "role-set": "Name a set of layers as a role that motions can target.",
    "motion-define": "Save a reusable motion recipe bound to roles.",
    "motion-apply": "Apply a saved motion recipe as editable timeline tracks.",
    "action-define": "Save a bounded list of operations as a reusable action.",
    "action-apply": "Run a saved action as one edit.",
    "recipe-set": "Attach a typed recipe (inputs, actions, examples) to the document.",
    "fit-text": "Wrap and fit a text layer into a width and height within a font-size range.",
    "arrange-grid": "Place layers on a simple column grid sized to the largest item.",
    "adapt-layout": "Reflow layers vertically into a new width and height.",
    # Pages
    "page": "Add, select, remove, move or edit a page of a multi-page document (slides, carousels).",
    "master": "Add, select, remove or edit a master: layers drawn under every page that uses it.",
    # Imperfection, bulk edits, frames and linked documents
    "irregular": "Opt in to seeded, bounded imperfection (wobble, jitter, stroke weight, color drift) on vector layers.",
    "tear": "Make a torn, ripped paper edge as a mask, clip or path, with a paper rim and loose fibres.",
    "edit-layers": "Apply a change or operation to every layer matching a selector (role, name, kind, tag, text) in one call.",
    "frames-edit": "Apply a list of operations to every saved frame, a named animation's frames or chosen frames, atomically.",
    "link": "Draw another .vixl document live as a layer (fit, position, crop, artboard, page, variables), or change a link.",
    "link-refresh": "Record the current revision of linked documents so stale links are reported only when the source changes.",
    "link-embed": "Freeze a linked document into an ordinary raster layer that no longer follows its source.",
    "chart": "Draw a data-bound chart (bars, lines, areas, pie, donut) as vector layers, or restyle one with target.",
    "chart-data": "Edit a chart's data in place (cells, categories, series, CSV reload) and redraw it, keeping layer IDs.",
    "stack": "Lay a group out as a row or column that reflows and re-centres when a member is empty or hidden.",
    "diagram": "Draw a flowchart, dependency graph, org chart or mind map from nodes and edges, laid out automatically.",
    "diagram-from-text": "Draw a diagram from a short text format (A -> B: label, indentation for hierarchies, group lanes).",
    "diagram-set": "Change a diagram's nodes, edges or options and lay it out again in place, keeping layer IDs.",
    "text-flow": "Flow one story through linked text frames (columns, pages, shapes), reflow it and report overflow.",
}

# Every effect is also an operation type ({type: blur, amount: 6} equals {type: effect, name: blur ...}).
EFFECT_SUMMARIES = {
    "denoise": ("Edge-preserving noise reduction for photos (non-local means on luminance, guided smoothing on color).",
                "Strength 0-100 for luminance and chroma together (default 50); luminance and chroma set them apart."),
    "brightness": ("Brighten (positive) or darken (negative) a layer.", "Percent change, -100 to 100 (0 unchanged)."),
    "contrast": ("Raise or lower contrast around the layer's average.", "Percent change, -100 to 100."),
    "saturation": ("Boost or mute color; -100 is grayscale.", "Percent change, -100 to 100."),
    "hue": ("Rotate hues around the color wheel.", "Degrees, -180 to 180."),
    "exposure": ("Brighten or darken in photographic stops.", "Stops, -32 to 32 (each +1 doubles brightness)."),
    "gamma": ("Adjust midtones without moving black or white.", "Gamma above 0; above 1 brightens midtones."),
    "temperature": ("Warm (positive) or cool (negative) the white point; black stays black.",
                    "-100 to 100, 0.75 mired per unit: 100 is about 6500 K to 4400 K, 20-30 is subtle."),
    "tint": ("Shift the white point toward magenta (positive) or green (negative); black stays black.",
             "-100 to 100, matched to temperature: tint 100 is as strong a cast as temperature 100."),
    "white-balance": ("Multiply the channels to neutralize a cast: set gains [r, g, b] or a neutral color that should be grey.",
                      "Strength of the correction, 0-100 (default 100)."),
    "shadows": ("Lift or deepen the dark areas.", "Percent change, -100 to 100."),
    "highlights": ("Lift or tame the bright areas.", "Percent change, -100 to 100."),
    "levels": ("Set black and white points to stretch tones.", "Unused; use black and white."),
    "curves": ("Remap tones through a curve of [input, output] points.", "Unused; use points."),
    "blur": ("Gaussian blur that spreads past the layer's edge (soft focus, glows).", "Blur radius in pixels (0-1000)."),
    "gaussian-blur": ("Gaussian blur (same as blur).", "Blur radius in pixels (0-1000)."),
    "sharpen": ("Sharpen edges.", "Sharpness, 0-100 (0 unchanged)."),
    "grayscale": ("Remove all color.", "Unused."),
    "invert": ("Invert colors (negative).", "Unused."),
    "posterize": ("Reduce each channel to a few levels.", "Bits per channel, 1-8."),
    "threshold": ("Pure black and white around a brightness cut.", "Cut level, 0-255."),
    "noise": ("Add random grain.", "Noise strength, 0-1 (0.05 is subtle film grain)."),
    "grain": ("Add film grain (same as noise).", "Grain strength, 0-1 (0.05 is subtle)."),
    "vignette": ("Darken toward the corners.", "Darkening at the corners, 0-1."),
    "auto-tone": ("Stretch each channel's tones automatically.", "Unused."),
    "auto-color": ("Neutralize color casts automatically.", "Unused."),
    "auto-contrast": ("Stretch overall contrast automatically.", "Unused."),
    "sepia": ("Warm brown monochrome tint.", "Strength, 0-100."),
    "duotone": ("Map shadows and highlights to two colors.", "Strength, 0-100 (set shadow_color and highlight_color)."),
    "solarize": ("Invert tones above a level.", "Level, 0-255."),
    "pixelate": ("Chunky mosaic pixels.", "Block size in pixels, 1-256."),
    "halftone": ("Print-style dot screen.", "Dot cell size in pixels, 2-128."),
    "crosshatch": ("Engraving-style cross-hatched lines.", "Line spacing in pixels, 2-128."),
    "ink-blot": ("Two-tone ink blot.", "Threshold, 0-255."),
    "stamp": ("Bold single-ink rubber-stamp look.", "Threshold, 0-255."),
    "photocopy": ("High-contrast photocopy look.", "Threshold, 0-255."),
    "pencil-sketch": ("Pencil drawing from edges and tones.", "Strength, 0-100."),
    "charcoal": ("Smudged charcoal drawing.", "Strength, 0-100."),
    "find-edges": ("Outline edges on a dark field.", "Strength, 0-100."),
    "emboss": ("Raised relief from edges.", "Strength, 0-100."),
    "oil-paint": ("Painterly oil strokes.", "Brush size, integer 1-6."),
    "watercolor": ("Soft washed watercolor.", "Strength, 0-100."),
    "swirl": ("Twirl the image around its center.", "Twist in degrees, -720 to 720."),
    "ripple": ("Sine ripples across the layer.", "Amplitude in pixels, 0-64."),
    "wave": ("Wavy distortion.", "Amplitude in pixels, 0-64."),
    "glass": ("Frosted glass refraction.", "Distortion in pixels, 0-64."),
}

# Descriptions by field name; OVERRIDES refine a field for one operation.
FIELDS = {
    "name": "Layer name (unique) or the name of the thing being created.",
    "target": "Stable layer ID or unique name; omitted means the active layer.",
    "targets": "Layer IDs or names the operation applies to.",
    "x": "Horizontal position in pixels, 'center' or a percentage such as '50%'.",
    "y": "Vertical position in pixels, 'center' or a percentage such as '50%'.",
    "width": "Width in pixels or a percentage such as '25%' of the canvas or parent group.",
    "height": "Height in pixels or a percentage such as '25%' of the canvas or parent group.",
    "color": "Color: CSS name, #hex, rgb()/hsl()/oklch(), or @swatch.",
    "fill": "Fill color (any color value or @swatch); 'transparent' for none.",
    "stroke": "Outline color; omit for no outline.",
    "stroke_width": "Outline thickness in pixels.",
    "stroke_color": "Outline color of the text.",
    "background": "Background color (any color value or @swatch).",
    "path": "Workspace file path (CLI) or an SVG path 'M … C … Z' string where the operation draws one.",
    "asset": "Embedded asset ID, as returned by vixl_import_image.",
    "size": "Size: a font size in pixels for text, or a named size / grid size where the operation says so.",
    "value": "The new value.",
    "points": "List of [x, y] points (pixels).",
    "seed": "Integer seed; the same seed always gives the same result.",
    "font": "Registered font name, or 'heading' / 'body' for the document typography.",
    "kind": "Which variant of the operation to use.",
    "start": "Start value or time.",
    "end": "End value or time.",
    "delete": "true removes the named item instead of creating or changing it.",
    "align": "Horizontal alignment: left, center, right (or justify for rich text).",
    "variables": "Variable values {name: value} that replace ${name} in text, colors and images.",
    "amount": "Strength of the effect or action.",
    "radius": "Radius in pixels (blur radius for effects).",
    "settings": "Settings object; see the operation's documentation for its keys.",
    "angle": "Angle in degrees (0 points right; positive turns clockwise).",
    "colors": "Colors, each any color value or @swatch.",
    "spacing": "Spacing in pixels (line gap for text, step for placement).",
    "preset": "Named preset: a size from vixl_sizes_list or a ready-made recipe.",
    "mode": "Mode: how the operation combines or behaves.",
    "effect": "Effect ID (from the layer's effect list), its 1-based index, or its name when used once in the stack.",
    "fit": "How an image fits its box: fill crops to cover; fit shows all of it.",
    "duration": "Length in ms or a time string such as '1.5s'.",
    "padding": "Inner margin in pixels.",
    "prefix": "Prefix for created names.",
    "text": "The text content.",
    "clear": "true removes the setting instead of changing it.",
    "margin": "Margin in pixels.",
    "base": "Base value the others derive from.",
    "gap": "Gap between items in pixels.",
    "count": "Number of copies or steps.",
    "property": "Layer property: x, y, translate-x, translate-y, opacity, rotation, scale, scale-x, scale-y, width, height, size, spacing, a color field (color, fill, stroke …), text or visible.",
    "time": "Time in ms, a '1.5s' string, a percentage or a marker name.",
    "easing": "Curve: linear, hold, ease, ease-in, ease-out, ease-in-out, ease-{in,out,in-out}-{sine,quad,cubic,quart,expo,back}, bounce-out, elastic-out, spring, cubic-bezier(x1,y1,x2,y2) or steps(n).",
    "label": "Visible label text.",
    "resource": "Name of a saved resource in the workspace library.",
    "direction": "Direction of the effect.",
    "roles": "Role-to-value mapping.",
    "role": "Role the item plays.",
    "shape": "Shape name.",
    "tolerance": "Allowed difference.",
    "strength": "Strength, 0-1.",
    "shadow_color": "Color mapped to shadows.",
    "highlight_color": "Color mapped to highlights.",
    "black": "Black point, 0-254 (levels below it become black).",
    "white": "White point, 1-255 (levels above it become white).",
    "axis": "Axis of the operation.",
    "dx": "Horizontal offset per copy, in pixels.",
    "dy": "Vertical offset per copy, in pixels.",
    "dw": "Width change per copy, in pixels.",
    "dh": "Height change per copy, in pixels.",
    "columns": "Number of columns.",
    "rows": "Number of rows (or row heights).",
    "offset": "Offset in pixels.",
    "angles": "Angles in degrees.",
    "palette": "Palette name or a list of colors.",
    "loop": "How many times to loop (0 is forever).",
    "from": "Starting value.",
    "to": "Ending value.",
    "title": "Title text.",
    "index": "Zero-based position.",
    "paragraphs": "Paragraph settings (list of objects).",
    "line_height": "Line height as a multiple of the font size.",
    "paragraph_spacing": "Space between paragraphs, in pixels.",
    "list_indent": "Indent per list level, in pixels.",
    "font_variants": "Registered fonts for styled runs: {bold, italic, bold_italic: font name}.",
    "rename": "New name.",
    "select": "true makes it the active one.",
    "key": "Form field key: the name its value is filled under.",
    "label_layer": "Text layer that labels the field.",
    "group_label": "Accessible label for a radio group.",
    "required": "true makes the field required.",
    "read_only": "true makes the field non-editable.",
    "default": "Default value.",
    "max_length": "Longest allowed text, in characters.",
    "comb": "Number of character cells (comb field).",
    "format": "Value format (number or date pattern).",
    "options": "Choices for a dropdown or radio group.",
    "editable": "true lets a dropdown take typed values.",
    "option": "Radio button's option name.",
    "on_value": "Export value when a checkbox is checked.",
    "tab": "Tab order position.",
    "overflow": "What to do when the value does not fit: shrink, clip or error.",
    "min_size": "Smallest font size when shrinking, in points.",
    "appearance": "Drawn appearance of the field box.",
}

_DIAGRAM_FIELDS = {
    "layout": "Layout: auto (picks one from the graph), layered (flowcharts, dependencies), tree, radial, mindmap or grid.",
    "routing": "How edges run: orthogonal (right angles, default), curved or straight.",
    "lanes": "Layered layout: turn kind: group nodes into swimlanes (columns for TB, rows for LR) instead of cluster boxes.",
    "theme": "Colors: light (default), dark or mono.",
    "text_color": "Default label color for nodes and edges.",
    "node_color": "Default node fill; a node's own color wins.",
    "edge_color": "Default edge and arrowhead color; an edge's own color wins.",
    "node_gap": "Space between nodes in the same rank, in pixels at scale 1 (default 44).",
    "rank_gap": "Space between ranks (rows or columns of the layout), in pixels at scale 1 (default 68).",
    "arrows": "Draw arrowheads on edges (default true).",
}

OVERRIDES = {
    "diagram": {**_DIAGRAM_FIELDS, "replace": "Replace an existing diagram of the same name instead of failing."},
    "diagram-from-text": {**_DIAGRAM_FIELDS, "replace": "Replace an existing diagram of the same name instead of failing."},
    "diagram-set": {**_DIAGRAM_FIELDS, "remove_nodes": "IDs of nodes to remove, with the edges that touch them.",
                    "remove_edges": "IDs of edges to remove."},
    "text-flow": {"action": "create (default), set, add-frame, link, unlink, reflow, style or delete.",
                  "markdown": "The story as Markdown (headings, bold, italic, lists), same syntax as rich-text.",
                  "spans": "The story as explicit rich-text spans (with paragraphs), same shape as rich-text.",
                  "frames": "Frames to flow through, in order: each {x, y, width, height} with optional columns, gutter, "
                            "page, inset, shape.",
                  "layers": "Existing text layers (IDs or names) to link into the chain, in order.",
                  "gutter": "Space between columns, in pixels (default 1.5 x the font size).",
                  "page": "Page (name or number) a frame lives on, in a multi-page document.",
                  "inset": "Space kept between a frame's edge and its text, in pixels.",
                  "keep_together": "Never split a paragraph that fits one frame between two frames.",
                  "keep_with_next": "Never leave a heading as the last thing in a frame (default true for rich text).",
                  "orphans": "Fewest lines of a paragraph left at the bottom of a frame (0 turns the rule off).",
                  "widows": "Fewest lines of a paragraph carried to the top of the next frame (0 turns the rule off).",
                  "delete_frames": "With unlink or delete: remove the frame layers too, not just the link.",
                  "match": "style: the words of the story to style (see occurrence).",
                  "occurrence": "style: which match to style, a 1-based number or 'all' (default)."},
    "link": {"source": "Workspace path of the .vixl document to draw (a link with a target: the new source).",
             "position": "Where the document sits in the box when it does not fill it: an anchor name (center, top-left …) "
                         "or [x, y] fractions 0-1.",
             "crop": "Region of the source to show, {x, y, width, height} in source pixels.",
             "artboard": "Name of an artboard in the source to draw instead of the whole canvas.",
             "source_page": "Page of a multi-page source to draw, by name or number."},
    "add": {"path": "Image file in the workspace (CLI and Python; services import with vixl_import_image).",
            "asset": "Embedded asset ID from vixl_import_image.",
            "name": "Layer name (defaults to the file name).",
            "linked": "Keep the layer linked to the file instead of embedding it.",
            "max_pixels": "Downsample the embedded copy to at most this many pixels; retain source provenance.",
            "downsample": "placed@2x stores an image with twice the placed resolution without upscaling.",
            "provenance": "Record of where the image came from."},
    "solid": {"color": "Fill color.", "name": "Layer name (default 'solid')."},
    "gradient": {"start": "Start color (the first stop).", "end": "End color (the last stop).",
                 "direction": "horizontal and vertical run edge to edge, radial from the center, angled uses angle.",
                 "stops": "2-64 color stops [{offset: 0-1 (strictly increasing), color}], used instead of start/end.",
                 "angle": "Degrees for direction 'angled'."},
    "palette-define": {"name": "Palette name.", "colors": "2-256 colors."},
    "palette-apply": {"name": "Palette to apply (built-in, document or workspace).",
                      "prefix": "Prefix for the numbered swatches (default the palette name).",
                      "roles": "true (default) assigns role swatches (background, surface, ink, muted, accent, "
                               "accent-text, on-accent); false only adds the numbered swatches; an object maps "
                               "roles to colors or to palette indexes, e.g. {background: 0, accent: 2}.",
                      "keep_order": "true uses the palette in the order given: background, surface, then accents "
                                    "(ink and muted are derived for contrast); the result's palette_roles explains every role.",
                      "policy": "strict (default) picks roles from the palette's own colors; accessible adjusts "
                                "them to meet contrast."},
    "template-apply": {"name": "Template name.", "variables": "Values for the template's inputs.",
                       "seed": "Seed for templates that vary."},
    "guidance": {"name": "Guidance name (a built-in guide, or any name when text is given).",
                 "text": "Guidance text to store.", "style": "Slot to store it in (default 'overall')."},
    "font-register": {"name": "Name to register the font under.", "asset": "Imported font asset ID.",
                      "role": "heading or body: make it the document's heading or body font."},
    "text": {"size": "Font size in pixels.", "color": "Text color.", "align": "Alignment within the text box.",
             "spacing": "Line spacing in pixels (default 4)."},
    "text-set": {"stroke_width": "Outline thickness in pixels (0 removes it).", "size": "Font size in pixels.",
                 "spacing": "Line spacing in pixels."},
    "rename": {"name": "New unique layer name."},
    "duplicate": {"name": "Name for the copy (default '<name> copy')."},
    "move": {"x": "New x in pixels, 'center' or a percentage; with relative, a shift.",
             "y": "New y in pixels, 'center' or a percentage; with relative, a shift.",
             "relative": "true treats x/y as a shift from the current position."},
    "scale": {"value": "Scale factor above 0 (2 doubles the size)."},
    "rotate": {"value": "Degrees clockwise about the layer's pivot (default its center)."},
    "pivot": {"value": "[x, y] as fractions of the layer box (0.5, 0.5 is the center) or an anchor such as "
                       "'top-left'.",
              "units": "fraction (default) of the layer box; px from the layer box's top-left corner; canvas: "
                       "an absolute document point (for a grouped layer, converted through its parent groups' "
                       "transforms).",
              "clear": "true restores the default center pivot."},
    "opacity": {"value": "0 (invisible) to 1 (opaque); a percentage string such as '70%' is read as 0.7. A bare "
                         "number above 1 is an error."},
    "blend": {"value": "Blend mode: normal, multiply, screen, overlay, darken, lighten, difference, add, subtract."},
    "flip": {"direction": "horizontal mirrors left-right; vertical mirrors top-bottom."},
    "crop": {"x": "Left edge of the crop in source pixels.", "y": "Top edge of the crop in source pixels.",
             "width": "Crop width in source pixels.", "height": "Crop height in source pixels."},
    "align": {"alignment": "Which edge or center to align to.", "margin": "Gap from the edge in pixels.",
              "relative_to": "canvas, selection, or a layer name (default canvas, or the selection for targets).",
              "targets": "Layers to align together (default the target)."},
    "constrain": {"constraints": "Anchors to expressions: {left|right|top|bottom|center-x|center-y: a number, "
                                 "'canvas.right-40', 'layer.left+8' or 'guide:name.center-x'}; one per axis."},
    "canvas": {"width": "Canvas width in pixels.", "height": "Canvas height in pixels.",
               "size": "Named size from vixl_sizes_list (letter, instagram-post, favicon …).",
               "preset": "Same as size.", "dpi": "Dots per inch for print metadata (36-2400).",
               "orientation": "Swap a named size to portrait or landscape.",
               "bleed": "true adds the size's standard bleed, or a bleed amount."},
    "select": {"shape": "Selection kind: all, none, invert, rect, ellipse, color, alpha (a layer), asset, wand, "
                        "lasso or path.",
               "color": "color selection: the color to match.", "tolerance": "How close a color must be (0-255).",
               "contiguous": "wand: only connected pixels.", "points": "lasso: polygon points [[x, y] …].",
               "path": "path selection: an SVG path string.", "feather": "Soften the selection edge, in pixels.",
               "mode": "How to combine with the current selection.", "asset": "asset selection: a mask asset ID."},
    "mask": {"action": "create (opaque mask), from-selection, import, invert, enable, disable or delete.",
             "path": "import: image file for the mask."},
    "effect": {"name": "Effect name (blur, grain, sepia, duotone … see the effect operations).",
               "amount": "Strength; its meaning depends on the effect.", "value": "Same as amount.",
               "seed": "Seed for random effects (grain, noise).", "radius": "Radius for vignette or distortion.",
               "strength": "Vignette strength, 0-1.",
               "shadow_color": "duotone: color for dark tones.", "highlight_color": "duotone: color for light tones.",
               "black": "levels: black point, 0-254.", "white": "levels: white point, 1-255.",
               "points": "curves: [[input, output] …] tone points, 0-255, inputs increasing.",
               "gains": "white-balance: channel multipliers [red, green, blue], 0-16.",
               "neutral": "white-balance: a color in the image that should be neutral grey (its luma is kept).",
               "lut": "lookup: the LUT name (defined with the lut operation); amount blends it, 0-1."},
    "effect-move": {"to": "New 1-based position in the stack, or top / bottom (the stack runs top to bottom).",
                    "before": "Place it just before this effect (ID, position or name).",
                    "after": "Place it just after this effect (ID, position or name)."},
    "variable": {"name": "Variable name (letters, digits, - and _).", "value": "String, number or boolean value."},
    "preset-save": {"name": "Preset name."},
    "preset-apply": {"name": "Saved preset.", "overrides": "{effect name: amount} replacements."},
    "shape": {"shape": "rectangle, rounded-rectangle, ellipse, polygon, star, line, triangle, right-triangle, "
                       "diamond, arrow, chevron, cross, heart, speech-bubble, or path (with path).",
              "path": "path shape: SVG path data (M L H V C S Q T A Z, several M sub-paths allowed) in literal local "
                      "pixels: a point (px, py) draws at (x + px, y + py). Without width/height the box reaches the "
                      "path's farthest point (never the whole canvas); with them, that is the box it is drawn in. "
                      "Negative coordinates draw outside the box. Later resizes scale the path; path-fit scales "
                      "geometry into a box.",
              "radius": "Corner radius in pixels (rounded-rectangle).", "sides": "Polygon side count.",
              "inner_radius": "Star inner radius as a fraction of the outer radius.",
              "fill": "Fill color; use a gradient-overlay layer-style (or the look operation) for gradients."},
    "group": {"name": "Group name.", "targets": "Layers to group (must share a parent)."},
    "clip": {"base": "Layer that supplies the clipping shape.", "release": "true removes the clip."},
    "layer-style": {"name": "drop-shadow, stroke, outer-glow, color-overlay or gradient-overlay.",
                    "settings": "drop-shadow {color, dx, dy, blur, opacity}; outer-glow {color, blur, opacity}; "
                                "stroke {color, width}; color-overlay {color, opacity}; gradient-overlay {start, end "
                                "or stops, direction, angle, opacity}; enabled false switches one off.",
                    "remove": "true removes the style."},
    "distribute": {"targets": "Three or more layers to space evenly.", "axis": "horizontal or vertical.",
                   "gap": "Fixed gap in pixels (default: even spacing between the ends)."},
    "style-define": {"name": "Style name.", "kind": "character or paragraph.",
                     "settings": "Text properties: size, color, font, spacing, align …"},
    "style-apply": {"name": "Defined style name.", "kind": "character or paragraph."},
    "swatch": {"name": "Swatch name (used as @name).", "color": "Color value; may use other swatches."},
    "artboard": {"name": "Artboard name.", "width": "Artboard width in pixels.", "height": "Artboard height in pixels.",
                 "x": "Viewport origin x on the canvas.", "y": "Viewport origin y on the canvas.",
                 "preset": "Named size for the artboard.", "variables": "Variable overrides for this artboard.",
                 "targets": "Layers shown on this artboard (default all)."},
    "frame": {"fit": "fill crops the image to cover the frame; fit shows the whole image.",
              "max_pixels": "Downsample the embedded copy to at most this many pixels; retain source provenance.",
              "downsample": "placed@2x stores enough resolution to draw this frame at twice its placed size.",
              "path": "Image file in the workspace (CLI and Python).", "asset": "Embedded asset ID from vixl_import_image."},
    "replace-contents": {"path": "Image file in the workspace (CLI and Python).",
                         "asset": "Embedded asset ID from vixl_import_image.", "variable": "Bind the image to this variable (replace it later by changing the variable).",
                         "fit": "fill crops to cover; fit shows all of the image."},
    "repeat": {"count": "Number of copies including the original.",
               "dx": "Horizontal offset between copies, in pixels.", "dy": "Vertical offset between copies, in pixels.",
               "dw": "Width added per copy.", "dh": "Height added per copy."},
    "repeat-blend": {"end": "End state {width, height, fill, color} the last copy blends to."},
    "adjustment": {"effects": "Effects applied to everything beneath, [{name, amount …}].",
                   "name": "Layer name (default 'adjustment')."},
    "lut": {"name": "LUT name.", "size": "Cube size, 2-33.", "values": "size³ RGB triplets in 0-1."},
    "lookup": {"name": "Defined LUT name.", "amount": "Blend with the original, 0-1 (default 1)."},
    "comp-save": {"name": "Comp name."}, "comp-apply": {"name": "Saved comp name."},
    "text-layout": {"width": "Wrapping box width in pixels or a percentage.", "height": "Box height.",
                    "fit": "true shrinks the text to fit the box.", "warp": "none, arc, flag or bulge.",
                    "amount": "Warp strength as a fraction of the box height (default 0.2; negative bends the other way).", "path": "Points [[x, y] …] the text follows."},
    "guide": {"name": "Guide name.", "axis": "x (vertical line) or y (horizontal line) for an axis guide.",
              "position": "Axis guide position in pixels.",
              "kind": "axis, line, ray, segment, point, circle or path.",
              "x": "Point or circle center x.", "y": "Point or circle center y.", "angle": "Line or ray angle in degrees.",
              "radius": "Circle radius.", "d": "SVG path data for a path guide.",
              "points": "Two [x, y] points for a segment or line."},
    "grid": {"name": "Grid name (its guides are prefixed with it).", "kind": "Grid system to generate.",
             "columns": "Column count.", "rows": "Row count or row heights.", "margin": "Outer margin in pixels.",
             "gutter": "Gap between columns in pixels.", "spacing": "Line spacing in pixels.",
             "offset": "Start offset in pixels.", "region": "[x, y, width, height] the grid fills.",
             "x": "Center or origin x.", "y": "Center or origin y.", "radius": "Outer radius.",
             "rings": "Ring count or radii.", "spokes": "Number of spokes.", "angle": "Rotation in degrees.",
             "angles": "Line angles in degrees.", "spacings": "Spacings between lines.", "turns": "Spiral turns.",
             "corner": "Golden spiral start corner.", "horizon": "Perspective horizon y.",
             "points": "Perspective vanishing points (1-3).", "vanishing": "Vanishing points [[x, y] …].",
             "rays": "Number of rays.", "delete": "true removes the grid."},
    "pathfinder": {"name": "Resulting layer name.", "targets": "Shape layers to combine.",
                   "mode": "union merges; subtract cuts the later layers out of the first; intersect keeps the overlap."},
    "symbol": {"name": "Symbol name."},
    "symbol-instance": {"symbol": "Symbol master name."},
    "pixel-art": {"palette": "Characters mapped to colors {'#': 'black', '.': 'white'}.",
                  "rows": "Strings, one per pixel row; each character is a palette key.",
                  "width": "Grid width in pixels (default the longest row).", "height": "Grid height in pixels.",
                  "x": "Layer x on the canvas.", "y": "Layer y on the canvas."},
    "pixel-draw": {"tool": "pixel, line, rect or fill.", "x": "Start column.", "y": "Start row.",
                   "x2": "Line end column.", "y2": "Line end row.", "width": "Rectangle width in pixels.",
                   "height": "Rectangle height in pixels.", "color": "Color or palette key."},
    "pixel-palette": {"colors": "Palette {character: color}."},
    "frame-save": {"name": "Frame name.", "duration": "Frame time in ms (a multiple of 10)."},
    "frame-apply": {"name": "Saved frame name."}, "frame-delete": {"name": "Saved frame name."},
    "animation-set": {"loop": "Loop count (0 is forever).", "order": "Frame names in playback order."},
    "paint-layer": {"name": "Layer name.", "width": "Surface width.", "height": "Surface height."},
    "paint": {"brush": "Brush name from vixl_brushes_list.", "points": "Stroke points [[x, y, pressure?] …].",
              "path": "Stroke along an SVG path instead of points.", "pressure": "Pressure per point, 0-1.",
              "space": "canvas (default) or layer coordinates.", "size": "Brush size in pixels.",
              "color": "Paint color.", "opacity": "Stroke opacity, 0-1.", "mode": "paint or erase.",
              "seed": "Seed for textured brushes.", "settings": "Brush overrides (hardness, spacing, flow …)."},
    "paint-clear": {"last": "Remove the last N strokes (default all)."},
    "brush-define": {"name": "New brush name.", "base": "Built-in brush to start from.",
                     "description": "What the brush is for.", "settings": "Overrides of the base brush."},
    "timeline-set": {"duration": "Total length in ms or '5s'.", "fps": "Frames per second, 1-60.",
                     "loop": "Loop count (0 is forever).", "clear": "true removes all tracks."},
    "keyframe": {"value": "Value at that time.", "targets": "Layers to key (default the target)."},
    "keyframe-remove": {"property": "Remove keys of this property.", "time": "Remove the key at this time."},
    "animate": {"from": "Start value (default the current value).", "to": "End value.",
                "start": "When it begins.", "end": "When it ends.", "duration": "Length instead of end.",
                "targets": "Layers to animate."},
    "animate-preset": {"preset": "Motion: fade-in/out, slide-in/out-left|right|up|down, pop-in/out, zoom-in/out, spin, pulse, shake, bounce, float, blink, typewriter or color-shift.",
                       "start": "When it begins.", "duration": "How long it runs.",
                       "distance": "Travel distance in pixels for slides.", "amount": "Strength of the motion.",
                       "fade": "true adds a fade.", "to": "Final value for presets that animate to one.",
                       "targets": "Layers to animate."},
    "marker": {"name": "Marker name.", "time": "Time of the marker.", "delete": "true removes it."},
    "layout-apply": {"name": "Layout from vixl_layouts_list.",
                     "seed": "Integer or 'random'; omitted uses a fresh seed unless document/workspace variety is fixed.",
                     "unfilled": "blank (default) shows [Label] placeholders that check flags; omit leaves them out.",
                     "palette": "Palette name or colors; roles are assigned by luminance and mode unless keep_order "
                                "or colors says otherwise.",
                     "colors": "Explicit role colors {background, surface, ink, muted, accent, accent-text, "
                               "on-accent}; they win over the palette.",
                     "keep_order": "true uses the palette in the order given: background, surface, then accents "
                                   "(ink and muted are derived for contrast).",
                     "mode": "light or dark (default: from the canvas background).",
                     "density": "airy, balanced or dense.", "align": "left, center or right.",
                     "accent": "rule, bar, dot, block, outline or none.",
                     "type_scale": "Ratio name (minor-third … golden) or number 1.05-2.",
                     "base_size": "Body size in pixels.", "mark": "Brand mark text or glyph.",
                     "font": "Body font name.", "display_font": "Heading font name.",
                     "transparent": "true skips the background layer.",
                     "uppercase_labels": "Upper-case the label slot (default true).", "prefix": "Prefix for layer names.",
                     "replace": "true removes the previous layout's layers first.",
                     "predictable": "true fixes align, density, type scale and accent to plain defaults.",
                     "title": "Headline copy.", "subtitle": "Supporting line.", "body": "Body copy.",
                     "label": "Short kicker or tag.", "cta": "Call to action button text.", "caption": "Small note.",
                     "image": "Embedded asset ID filling the layout's image slot; unfilled shows a placeholder frame "
                              "you can fill with replace-contents, drawn shapes, or an AI tool.",
                     "items": "One item per line."},
    "type-scale": {"base": "Body size in pixels.", "ratio": "Scale ratio name or number 1.05-2.",
                   "prefix": "Prefix for the style names.", "color": "Color for the styles."},
    "suite-set": {"name": "Suite name.", "suite": "The suite object."},
    "suite-capture": {"name": "Suite name.", "targets": "Layers to protect.", "regions": "Pixel regions [[x, y, w, h]]."},
    "role-set": {"name": "Role name.", "targets": "Layers in the role."},
    "motion-define": {"name": "Motion name.", "motion": "Motion recipe {steps: [...]}."},
    "motion-apply": {"name": "Saved motion.", "roles": "Role-to-layer overrides.", "speed": "Speed multiplier.",
                     "start": "When the motion begins."},
    "action-define": {"name": "Action name.", "action": "Action {operations: [...]}."},
    "action-apply": {"name": "Saved action name."},
    "recipe-set": {},
    "fit-text": {"width": "Box width.", "height": "Box height.", "minimum": "Smallest font size.",
                 "maximum": "Largest font size."},
    "arrange-grid": {"targets": "Layers to arrange.", "columns": "Columns.", "gap": "Gap in pixels.",
                     "x": "Grid origin x.", "y": "Grid origin y."},
    "adapt-layout": {"targets": "Layers in priority order.", "width": "New width.", "height": "New height.",
                     "margin": "Outer margin.", "gap": "Gap between layers."},
    "pen": {"nodes": "Anchors [{point: [x, y], in: [x, y], out: [x, y]}] for a Bezier path.",
            "points": "Freehand points [[x, y] …] smoothed into a path.", "closed": "Close the path.",
            "smooth": "Smooth freehand points (default true).", "tension": "Handle length for smoothed points (default 1; 0 gives straight segments).",
            "corners": "Indexes of points kept sharp."},
    "organic-shape": {"kind": "leaf, petal, blob or rose.", "lobes": "Lobe or petal count.",
                      "variation": "Randomness of the outline, 0-1."},
    "path-fit": {"padding": "Inner margin in pixels.", "preserve_aspect": "true keeps the path's proportions."},
    "layer-intent": {"role": "content, decoration (may overlap and bleed), background (checks skip it; use it for full-canvas art), or title (the heading that names the page and the PDF).",
                     "allow_overlap": "Layers this layer may overlap without a check finding.",
                     "color_vision_safe": "true on a chart group says its series differ by more than color (labels, patterns), so the color_vision check skips it.",
                     "allow_crop": "true marks a deliberate edge crop or bleed: checks report it as informational "
                                   "instead of a problem."},
    "font-fallbacks": {"fonts": "Registered font names tried for missing characters."},
    "container-place": {"name": "Group layer name.", "resource": "Saved container name.",
                        "variables": "Container variables."},
    "container-swap": {"resource": "Replacement container.", "variables": "Container variables."},
    "shape-place": {"resource": "Saved shape name.", "name": "Layer name.", "width": "Width.", "height": "Height.",
                    "fill": "Fill color.", "stroke": "Outline color."},
    "organic": {"name": "Layer name.", "preset": "Ready-made form (flower, tree, fern, jellyfish …).",
                "parts": "Generator parts with rules, instead of a preset (docs/organic.md).",
                "params": "Preset parameters, e.g. {petals: 8}.", "colors": "Per-part colors {part: color}.",
                "naturalness": "Irregularity, 0 (geometric) to 1 (wild).", "padding": "Inner margin in pixels.",
                "stretch": "true stretches the form to fill the box.", "stroke": "Outline color.",
                "stroke_width": "Outline thickness."},
    "place": {"targets": "Layers to place.", "guide": "Guide name to place on.", "with": "Second guide: place at "
              "intersections.", "index": "Which intersection (zero-based).", "at": "Fraction along the guide, 0-1.",
              "start": "First fraction when spreading.", "end": "Last fraction when spreading.",
              "spacing": "Fixed spacing in pixels along the guide.", "angle": "Angle for the placed layers.",
              "anchor": "Which point of the layer sits on the guide (center, top-left … or [x, y] fractions).",
              "orient": "Turn layers to the guide: none, tangent, normal, radial or upright.",
              "rotate": "Extra rotation in degrees.", "offset": "Shift along the guide's normal in pixels."},
    "snap": {"targets": "Layers to snap (default all).", "guides": "Guides to snap to (default all).",
             "tolerance": "Largest move in pixels (default 8).", "angle_tolerance": "Largest turn in degrees.",
             "angles": "Straighten near-miss rotations.", "intersections": "Snap to guide intersections.",
             "anchors": "Layer anchors that may snap."},
    "rich-text": {"markdown": "Markdown (bold, italic, headings, lists, [text]{color=…}).",
                  "spans": "Explicit spans [{text, bold, italic, color …}].", "name": "Layer name.",
                  "size": "Base font size.", "color": "Base text color.", "fit": "Shrink text to fit the box."},
    "text-style": {"match": "Text to find and style.", "occurrence": "Which match: a 1-based number, or 'all' (default).",
                   "paragraphs": "Paragraph indexes (0-based) the paragraph settings apply to, or 'all'.",
                   "start": "First character index.", "end": "Character index after the last.",
                   "bold": "Bold on or off.", "italic": "Italic on or off.", "underline": "Underline on or off.",
                   "strike": "Strikethrough on or off.", "color": "Text color.", "size": "Font size.",
                   "font": "Font name.", "highlight": "Highlight color.", "baseline": "super, sub or normal.",
                   "tracking": "Letter spacing in pixels.", "list": "none, bullet or number.",
                   "level": "List level (0-based).", "paragraph_align": "left, center, right or justify.",
                   "space_before": "Space above the paragraph.", "space_after": "Space below the paragraph.",
                   "indent": "Paragraph indent.", "number_start": "First number of a numbered list.",
                   "clear": "true removes the styling."},
    "page": {"action": "add, select, remove, move or set.", "page": "Page name or number.", "name": "Page name.",
             "after": "Insert after this page.", "before": "Insert before this page.", "index": "Insert at position.",
             "duplicate": "Copy this page's layers.", "first": "Make the page first.",
             "master": "Master name (null for none).", "notes": "Speaker notes.", "background": "Page background.",
             "variables": "Page variables.", "hidden": "Hide from export.", "select": "Make it the active page.",
             "transition": "Slide transition: none, fade, push, wipe, cover, split or zoom."},
    "master": {"action": "add, select, remove or set.", "name": "Master name.", "from": "Copy layers from this page.",
               "background": "Background color."},
    "drawing": {"action": "import, clean, vectorize, straighten, smooth, fill, stroke or restyle.",
                "name": "Drawing name.", "asset": "Embedded scan or photo asset.", "path": "Scan or photo file.",
                "settings": "Action settings (docs/drawing.md).", "strokes": "Stroke IDs or 'all'.",
                "points": "Points for a manual stroke.", "color": "Color.",
                "x": "Position x.", "y": "Position y.", "width": "Width.", "height": "Height."},
    "palette-generate": {"name": "Prefix for the swatches (NAME-50 … or NAME-1 …).",
                         "color": "Source color (any color value or @swatch).",
                         "scheme": "scale (default) for a 50-950 ramp, or a harmony: complementary, analogous, "
                                   "triadic, split-complementary, tetradic, square, monochromatic, tints, shades, tones.",
                         "count": "Colors for a harmony."},
    "look": {"look": "Look name; vixl_guide or the look catalog lists them.",
             "color": "Main color of the look (glow color, shadow color, tint).",
             "amount": "Strength from subtle (0) to strong (1); default 0.5.", "targets": "Several layers instead of target.",
             "remove": "true takes the look off again."},
    "radial-repeat": {"count": "Copies around the center (2-360).", "cx": "Center x (pixels, '50%' or 'center').",
                      "cy": "Center y (pixels, '50%' or 'center').", "sweep": "Degrees covered (default 360).",
                      "start_angle": "Rotation of the first copy in degrees.", "mirror": "true adds a mirrored copy of "
                      "each (dihedral symmetry).", "group": "true (default) groups the copies.",
                      "name": "Name of the group of copies."},
    "style-set": {"style": "Style name (or up to three names) from vixl_styles; null clears the tag.",
                  "options": "Overrides for the style's check settings."},
}

EXAMPLES = {
    "gradient": [
        {"type": "gradient", "name": "sky", "start": "#1e3a8a", "end": "#7dd3fc", "direction": "vertical"},
        {"type": "gradient", "name": "glow-disc", "width": 400, "height": 400, "start": "#fde68a",
         "end": "#00000000", "direction": "radial"},
        {"type": "gradient", "name": "sunset", "direction": "angled", "angle": 35,
         "stops": [{"offset": 0, "color": "#f97316"}, {"offset": 0.55, "color": "#db2777"},
                   {"offset": 1, "color": "#4c1d95"}]},
    ],
    "shape": [
        {"type": "shape", "shape": "rounded-rectangle", "name": "card", "x": 80, "y": 80, "width": 320,
         "height": 200, "radius": 24, "fill": "#ffffff", "stroke": "#cbd5e1", "stroke_width": 2},
        {"type": "shape", "shape": "star", "name": "badge", "x": 60, "y": 60, "width": 120, "height": 120,
         "sides": 5, "fill": "#facc15"},
    ],
    "layer-style": [
        {"type": "layer-style", "target": "card", "name": "drop-shadow",
         "settings": {"color": "#00000066", "dx": 0, "dy": 12, "blur": 24}},
        {"type": "layer-style", "target": "badge", "name": "outer-glow",
         "settings": {"color": "#fde047", "blur": 18, "opacity": 0.9}},
        {"type": "layer-style", "target": "card", "name": "gradient-overlay",
         "settings": {"start": "#6366f1", "end": "#ec4899", "direction": "angled", "angle": 45}},
    ],
    "repeat": [
        {"type": "repeat", "target": "badge", "count": 5, "dx": 70, "dy": 0},
    ],
    "radial-repeat": [
        {"type": "radial-repeat", "target": "badge", "count": 12, "cx": "50%", "cy": "50%", "name": "rosette"},
        {"type": "radial-repeat", "target": "badge", "count": 8, "cx": 300, "cy": 200, "mirror": True,
         "name": "mandala"},
    ],
    "look": [
        {"type": "look", "target": "badge", "look": "glow", "color": "#fde047"},
        {"type": "look", "target": "card", "look": "soft-shadow"},
        {"type": "look", "target": "card", "look": "paper"},
    ],
    "effect-move": [
        {"type": "effect-move", "target": "photo", "effect": "grain", "to": "top"},
        {"type": "effect-move", "target": "photo", "effect": 3, "before": "blur"},
    ],
    "effect": [
        {"type": "effect", "target": "card", "name": "grain", "amount": 0.06, "seed": 3},
        {"type": "effect", "target": "card", "name": "duotone", "shadow_color": "#1e1b4b",
         "highlight_color": "#fef3c7"},
    ],
    "text": [
        {"type": "text", "text": "Hello", "name": "greeting", "size": 72, "color": "#ffffff", "x": "center",
         "y": "40%"},
    ],
    "layout-apply": [
        {"type": "layout-apply", "name": "hero-statement", "title": "Make it simple", "subtitle": "One idea, said well.",
         "label": "Open call", "cta": "Join in", "palette": "midnight", "seed": 7},
        {"type": "layout-apply", "name": "app-icon", "title": "Notes", "palette": ["#0f172a", "#1e293b", "#38bdf8"],
         "keep_order": True},
    ],
    "palette-apply": [
        {"type": "palette-apply", "name": "ocean", "roles": {"background": 0, "accent": 2}},
    ],
    "palette-generate": [
        {"type": "palette-generate", "name": "brand", "color": "#2563eb", "scheme": "scale"},
        {"type": "palette-generate", "name": "accent", "color": "#2563eb", "scheme": "triadic"},
    ],
    "organic": [
        {"type": "organic", "preset": "flower", "name": "bloom", "x": 40, "y": 40, "width": 240, "height": 280,
         "seed": 4},
    ],
    "clip": [
        {"type": "clip", "target": "photo", "base": "card"},
    ],
    "pathfinder": [
        {"type": "pathfinder", "name": "crescent", "targets": ["moon", "bite"], "mode": "subtract"},
    ],
    "layer-intent": [
        {"type": "layer-intent", "target": "photo", "role": "decoration", "allow_crop": True},
    ],
    "style-set": [
        {"type": "style-set", "style": "swiss"},
    ],
    "suite-set": [
        {"type": "suite-set", "name": "quality", "suite": {"version": 1, "rules": [
            {"id": "logo-inside", "kind": "assert", "expression": "layer.logo.bounds within canvas"}]}},
    ],
    "animate-preset": [
        {"type": "animate-preset", "targets": ["greeting"], "preset": "fade-in", "start": 0, "duration": "600ms"},
    ],
}

# Defaults for properties that were declared without a type.
UNTYPED = {"x": {"type": ["number", "string"]}, "y": {"type": ["number", "string"]},
           "width": {"type": ["number", "string"]}, "height": {"type": ["number", "string"]}}
TYPED = ("type", "enum", "anyOf", "oneOf", "const", "$ref", "allOf")


def effect_help(name):
    summary, amount = EFFECT_SUMMARIES[name]
    return summary, {"amount": amount, "value": "Same as amount."}


def describe_field(kind, field):
    """The description for ``field`` of operation ``kind`` (None when nothing is known)."""
    if kind in EFFECT_SUMMARIES and field in ("amount", "value"):
        return effect_help(kind)[1][field]
    return OVERRIDES.get(kind, {}).get(field) or (
        OVERRIDES["effect"].get(field) if kind in EFFECT_SUMMARIES or kind.startswith("effect-") else None
    ) or FIELDS.get(field)


def enrich(variants):
    """Add ``description`` and ``examples`` to each operation variant and a description to every
    property that has none (a description set where the field is defined is kept)."""
    for variant in variants:
        kind = variant["properties"]["type"]["const"]
        if kind in EFFECT_SUMMARIES:
            variant["description"] = f"{effect_help(kind)[0]} Same as {{type: effect, name: {kind}}}."
        elif kind in SUMMARIES:
            variant["description"] = SUMMARIES[kind]
        elif kind.startswith("effect-"):
            variant["description"] = SUMMARIES.get(kind, "")
        if kind in EXAMPLES:
            variant["examples"] = deepcopy(EXAMPLES[kind])
        for field, schema in list(variant["properties"].items()):
            if field == "type":
                continue
            if not any(key in schema for key in TYPED) and field in UNTYPED:
                schema = {**schema, **UNTYPED[field]}
            if "description" not in schema:
                text = describe_field(kind, field)
                if text:
                    schema = {**schema, "description": text}
            variant["properties"][field] = schema
    return variants
