"""Curated catalog of design styles: principles, palettes, type, layout, imagery and checks.

Each entry distills what the movement or genre is known for (sources in docs/styles.md) into
guidance an agent can act on, plus a few *premade checks*: parameterised rules that
``vixl.styles`` evaluates on the open document. Checks are optional and advisory; a style that
fits the brief better with one rule relaxed can override it (``style-set`` ``options``).

Rule shorthand: ``R(kind, summary, fix, severity="warning", id=None, **params)``. ``kind`` names an
evaluator in ``vixl.styles.RULES``; ``params`` are its settings.
"""


def R(kind, summary, fix, severity="warning", id=None, **params):
    return {"id": id or kind.replace("_", "-"), "kind": kind, "severity": severity, "summary": summary,
            "fix": fix, "params": params}


def P(name, note, *swatches):
    return {"name": name, "note": note, "swatches": list(swatches)}


STYLES = {
    "swiss": {
        "title": "Swiss / International Typographic Style",
        "summary": "Objective, grid-built design: sans-serif type, flush-left ragged-right text, asymmetric balance, "
                   "strong scale contrast and few colors, so the information carries the page.",
        "era": "1950s-1970s, Switzerland (Muller-Brockmann, Hofmann, Ruder)",
        "keywords": ["grid", "helvetica", "objective", "asymmetric", "rational", "modernist", "clean"],
        "best_for": ["posters", "annual reports", "identity systems", "signage", "information design"],
        "principles": [
            "Build everything on a visible-or-invisible grid; every element sits on a column or baseline line.",
            "Set text flush left, ragged right; avoid justified and centered body copy.",
            "Use one or two sans-serif typefaces, strong scale contrast and weight to build hierarchy instead of decoration.",
            "Asymmetric balance with generous white space; photographs are objective, rectangular and cropped on the grid.",
            "Limit color to black, white and one assertive accent (often red).",
        ],
        "palettes": [
            P("Swiss red", "Black type on white with one red accent", "#ffffff", "#111111", "#e30613", "#8c8c8c"),
            P("Swiss blue", "Cool variant for corporate work", "#f4f4f2", "#101820", "#0050b5", "#9aa5b1"),
        ],
        "palette_names": ["mono", "accessible-red"],
        "type": {
            "categories": ["sans-serif"],
            "families": ["Inter", "Archivo", "Work Sans", "Public Sans", "Libre Franklin"],
            "pairings": ["inter-single-ui", "inter-tight-inter", "public-sans-single", "archivo-black-archivo"],
            "weights": "Regular and bold (or one light and one bold); size, not decoration, makes hierarchy.",
            "case": "Lower case or sentence case for text; headings may be set large and tight.",
            "avoid": ["decorative or script faces", "more than two families", "centered or justified paragraphs"],
        },
        "layout": {
            "grid": "Modular grid of 4-12 columns with a baseline; align every left edge to a column.",
            "alignment": "Flush left, ragged right.",
            "negative_space": "Generous; white space is an active element.",
            "layouts": ["editorial-grid", "f-pattern", "asymmetric-balance", "rule-of-thirds", "big-number"],
        },
        "imagery": {
            "advice": "Objective black-and-white or full-color photographs, cropped to the grid; no drop shadows or effects.",
            "looks": ["halftone"], "effects": ["grayscale", "contrast"],
            "avoid": ["gradients", "soft shadows", "ornament", "rotated text outside 90-degree turns"],
        },
        "do": ["Align to a grid", "Use scale contrast for hierarchy", "Keep to black, white and one accent",
               "Set body text flush left"],
        "dont": ["Center everything", "Mix many typefaces", "Add drop shadows or gradients", "Tilt elements for effect"],
        "checks": [
            R("max_typefaces", "At most two typefaces", "Use one sans family in two weights", max=2),
            R("text_align", "Text is flush left (ragged right)", "Set text align to left", allowed=["left"], scope="body"),
            R("edge_alignment", "Elements share left edges on a grid", "Align layers to the same left edge or guide",
              min_fraction=0.7, tolerance=3),
            R("tilt", "No tilted elements (only 90-degree turns)", "Reset rotation to 0", max_fraction=0.0),
            R("shadows", "No shadows or glows", "Remove layer styles; use scale and weight instead", mode="none"),
            R("hue_count", "One accent color at most", "Reduce to black, white and one accent", max=1),
        ],
    },
    "brutalist": {
        "title": "Brutalist (raw web and print brutalism)",
        "summary": "Deliberately raw and blunt: heavy type, hard edges, stark black-and-white or primary colors, visible "
                   "structure, no polish or decoration, and high contrast everywhere.",
        "era": "2010s web revival of 1950s architectural brutalism",
        "keywords": ["raw", "heavy", "monospace", "harsh", "anti-design", "stark", "concrete"],
        "best_for": ["art and culture sites", "music posters", "manifestos", "editorial statements", "portfolios"],
        "principles": [
            "Embrace the raw: default-looking system or monospace type, hard rectangles, thick rules.",
            "Use maximum contrast: black on white, or a flat acid color on black; no subtle grays.",
            "Heavy weights and very large type; layout is blocky and exposed, never smoothed.",
            "No rounded corners, soft shadows, gradients or glossy effects.",
            "Let structure show: borders, tables, visible grids and overlapping slabs are features.",
        ],
        "palettes": [
            P("Concrete", "Black, white and one signal color", "#ffffff", "#000000", "#ff2d00", "#d9d9d9"),
            P("Highlighter", "Acid yellow on black", "#000000", "#fff200", "#ffffff"),
            P("Primary blocks", "Flat primaries", "#ffffff", "#000000", "#0000ff", "#ffdd00", "#ff0000"),
        ],
        "palette_names": ["mono", "neon"],
        "type": {
            "categories": ["monospace", "sans-serif", "display"],
            "families": ["Space Mono", "Archivo Black", "Anton", "IBM Plex Mono", "League Gothic", "Bebas Neue"],
            "pairings": ["space-mono-single-brutalist", "archivo-black-archivo", "anton-roboto-thumbnail",
                         "league-gothic-libre-baskerville"],
            "weights": "Bold or black for headings; large size.",
            "case": "Upper case headings are common.",
            "avoid": ["delicate hairline weights", "script faces", "refined serifs"],
        },
        "layout": {
            "grid": "Blocky slabs, thick borders, overlapping boxes; asymmetry is fine.",
            "alignment": "Flush left or stacked blocks; do not over-polish.",
            "negative_space": "Tight to moderate; fill the page.",
            "layouts": ["typographic-poster", "thumbnail-bold", "asymmetric-balance", "hero-statement"],
        },
        "imagery": {
            "advice": "High-contrast, thresholded or grainy photos; raw screenshots; hard black outlines.",
            "looks": ["hard-shadow", "outline", "halftone", "grain"], "effects": ["threshold", "grayscale", "contrast"],
            "avoid": ["soft shadows", "gradients", "rounded cards", "pastel colors"],
        },
        "do": ["Use heavy weights and large type", "Keep contrast at its maximum", "Use hard rectangles and thick borders"],
        "dont": ["Round the corners", "Add soft shadows or glows", "Use delicate light weights", "Smooth it over with gradients"],
        "checks": [
            R("min_weight", "Headlines are bold or black", "Use a 700+ weight for the largest text", weight=700,
              scope="headline"),
            R("design_check", "High contrast (7:1 or better)", "Use pure black and white or a saturated flat color",
              id="high-contrast", checks=["contrast"], options={"min_contrast": 7}),
            R("no_rounded_corners", "No rounded corners", "Use square rectangles", allow_circles=False),
            R("shadows", "No soft shadows", "Remove soft shadows; a hard offset shadow is acceptable", mode="hard-or-none"),
            R("gradients", "No gradients", "Use flat fills", mode="none"),
        ],
    },
    "neo-brutalist": {
        "title": "Neo-brutalism",
        "summary": "Playful, bold UI cousin of brutalism: flat saturated colors, thick black outlines, hard offset "
                   "shadows and chunky type on friendly rectangles.",
        "era": "2020s product and web design",
        "keywords": ["outline", "offset shadow", "chunky", "saturated", "playful", "sticker", "bold"],
        "best_for": ["landing pages", "app marketing", "social cards", "startups", "stickers"],
        "principles": [
            "Thick (2-4 px) black outlines on every card, button and badge.",
            "Hard offset shadows with zero blur, in black, instead of soft shadows.",
            "Flat, saturated fills (yellow, pink, lime, blue) on an off-white or tinted ground.",
            "Heavy, slightly quirky type; generous padding inside blocks.",
            "Mild rounding is allowed; keep everything flat and graphic.",
        ],
        "palettes": [
            P("Candy blocks", "Saturated flats on cream", "#fffdf5", "#111111", "#ffd23f", "#ff6b9d", "#7ae582", "#4d96ff"),
            P("Pop", "Yellow-violet", "#fff7d6", "#000000", "#a78bfa", "#fde047"),
        ],
        "palette_names": ["candy", "coral"],
        "type": {
            "categories": ["sans-serif", "display"],
            "families": ["Archivo Black", "Space Grotesk", "Bricolage Grotesque", "Unbounded", "Syne", "DM Sans"],
            "pairings": ["archivo-black-archivo", "space-mono-space-grotesk", "unbounded-manrope", "bricolage-figtree"],
            "weights": "Bold headings, medium body.",
            "case": "Sentence or title case; short punchy headlines.",
            "avoid": ["hairline weights", "thin gray text"],
        },
        "layout": {
            "grid": "Cards and badges on a loose grid; overlap slightly.",
            "alignment": "Left-aligned cards with comfortable padding.",
            "negative_space": "Moderate.",
            "layouts": ["bento-grid", "product-card", "hero-statement", "banner"],
        },
        "imagery": {
            "advice": "Flat illustration and stickers with black outlines; screenshots in outlined frames.",
            "looks": ["hard-shadow", "outline"], "effects": [],
            "avoid": ["soft blurred shadows", "photographic gradients", "glassy effects"],
        },
        "do": ["Outline everything in black", "Use hard offset shadows", "Pick 3-4 saturated flats"],
        "dont": ["Use blurred shadows", "Use thin gray text", "Mix in glass or gradient effects"],
        "checks": [
            R("shadows", "Shadows are hard offsets (no blur)", "Use look hard-shadow", mode="hard"),
            R("gradients", "Flat fills only", "Replace gradients with flat colors", mode="none"),
            R("min_stroke_width", "Outlines are at least 2 px", "Use a stroke of 2-4 px", width=2),
            R("min_weight", "Headlines are bold", "Use a 600+ weight for the largest text", weight=600, scope="headline"),
        ],
    },
    "minimalist": {
        "title": "Minimalism",
        "summary": "Say one thing with the least: generous negative space, a restrained palette of two or three "
                   "colors, one typeface, and only the elements the message needs.",
        "era": "1960s onward; 'less is more'",
        "keywords": ["restraint", "whitespace", "reduction", "calm", "quiet", "simple", "essential"],
        "best_for": ["logos", "product pages", "portfolios", "invitations", "quote cards", "covers"],
        "principles": [
            "Reduce until nothing more can be removed without losing meaning.",
            "At least 40% of the canvas stays empty; margins are generous.",
            "Two or three colors total, one typeface, a small set of sizes.",
            "One focal point; everything else recedes.",
            "Precision matters more in minimalism: align and space exactly.",
        ],
        "palettes": [
            P("Paper and ink", "Off-white with near-black and one accent", "#fafaf8", "#1a1a1a", "#c8553d"),
            P("Fog", "Neutral grays with a blue accent", "#f2f4f6", "#25282c", "#5b7c99"),
            P("Night", "Dark minimal", "#0f1113", "#e8eaed", "#7aa2f7"),
        ],
        "palette_names": ["mono", "slate", "nordic"],
        "type": {
            "categories": ["sans-serif", "serif"],
            "families": ["Inter", "Geist", "Instrument Sans", "Plus Jakarta Sans", "Instrument Serif"],
            "pairings": ["inter-single-ui", "geist-dev", "instrument-serif-sans", "plus-jakarta-single"],
            "weights": "Light to regular; one bold at most.",
            "case": "Sentence case; small sizes need generous tracking.",
            "avoid": ["decorative faces", "multiple accents", "text effects"],
        },
        "layout": {
            "grid": "Few elements on a clear axis or thirds line.",
            "alignment": "One alignment throughout.",
            "negative_space": "40-80% of the canvas empty.",
            "layouts": ["minimal-mark", "hero-statement", "centered-axis", "quote-card", "logo-stacked"],
        },
        "imagery": {
            "advice": "One image or none; large, quiet and well cropped; no effects.",
            "looks": [], "effects": [],
            "avoid": ["drop shadows", "gradients", "textures", "ornament"],
        },
        "do": ["Leave most of the canvas empty", "Limit to 2-3 colors", "Use one typeface"],
        "dont": ["Decorate", "Add more elements 'to fill space'", "Use more than one accent"],
        "checks": [
            R("min_negative_space", "At least 40% of the canvas is empty", "Remove elements or enlarge margins",
              fraction=0.4),
            R("max_colors", "At most three colors", "Reduce the palette to three colors", max=3, distance=40),
            R("max_typefaces", "One typeface", "Use a single family", max=1),
            R("max_words", "Few words (40 or fewer)", "Cut copy to the essentials", max=40),
            R("margins", "Generous margins (6% or more of the short side)", "Pull content in from the edges",
              min_fraction=0.06),
            R("shadows", "No shadows or glows", "Remove layer styles", mode="none"),
        ],
    },
    "scandinavian": {
        "title": "Scandinavian / Nordic",
        "summary": "Warm minimalism: soft muted palettes, natural textures, friendly rounded sans-serifs, airy "
                   "layouts and a human, functional calm.",
        "era": "1950s onward; contemporary 'hygge' branding",
        "keywords": ["nordic", "hygge", "muted", "natural", "friendly", "functional", "airy"],
        "best_for": ["lifestyle brands", "home and wellness", "packaging", "editorial", "cafes"],
        "principles": [
            "Muted, low-saturation colors drawn from nature: sand, sage, clay, slate blue, off-white.",
            "Functional simplicity with warmth: soft shapes, gentle contrast, natural textures.",
            "Friendly humanist sans-serifs, sometimes with a soft serif for headings.",
            "Light and airy layouts with plenty of space; avoid heavy ornament.",
            "Organic accents (leaves, wood grain, paper) rather than glossy effects.",
        ],
        "palettes": [
            P("Sand and sage", "Natural neutrals", "#f6f1ea", "#2f3b36", "#9caf88", "#d9c5a0"),
            P("Nordic blue", "Cool airy", "#f3f6f8", "#27333d", "#7a9eb1", "#cfd8dc"),
            P("Clay", "Warm earth", "#f7efe8", "#3b2f2a", "#c58d6b", "#e6d3c1"),
        ],
        "palette_names": ["nordic", "sage", "peach"],
        "type": {
            "categories": ["sans-serif", "serif"],
            "families": ["DM Sans", "Figtree", "Lexend", "Fraunces", "Work Sans", "Atkinson Hyperlegible Next"],
            "pairings": ["fraunces-work-sans", "dm-serif-dm-sans", "lexend-atkinson", "bricolage-figtree"],
            "weights": "Regular and medium; avoid black weights.",
            "case": "Sentence case.",
            "avoid": ["aggressive display faces", "neon colors"],
        },
        "layout": {
            "grid": "Calm modular layouts with soft rounded containers.",
            "alignment": "Left or centered, with space.",
            "negative_space": "Generous (30% or more).",
            "layouts": ["hero-statement", "split-screen", "product-card", "photo-caption", "minimal-mark"],
        },
        "imagery": {
            "advice": "Natural light photography, plants, wood, linen; subtle paper grain.",
            "looks": ["paper", "grain", "soft-shadow"], "effects": ["grain"],
            "avoid": ["neon", "harsh black outlines", "high-saturation colors"],
        },
        "do": ["Use muted natural colors", "Round the corners softly", "Leave air around things"],
        "dont": ["Use saturated neons", "Use harsh blacks and heavy outlines", "Crowd the layout"],
        "checks": [
            R("saturation", "Muted colors (average saturation 55% or less)", "Desaturate or tint the palette", max=0.55),
            R("min_negative_space", "Airy layout (30% or more empty)", "Add space around elements", fraction=0.3),
            R("max_typefaces", "At most two typefaces", "Use one sans and one soft serif at most", max=2),
            R("shadows", "Only soft shadows, if any", "Replace hard shadows", mode="soft-or-none"),
        ],
    },
    "bauhaus": {
        "title": "Bauhaus",
        "summary": "Geometry first: circles, squares and triangles in primary colors, sans-serif type, asymmetric "
                   "dynamic compositions, and form following function.",
        "era": "1919-1933, Germany (Bayer, Moholy-Nagy, Albers)",
        "keywords": ["primary colors", "geometric", "circle square triangle", "functional", "constructivist", "dynamic"],
        "best_for": ["posters", "exhibitions", "identity", "infographics", "book covers"],
        "principles": [
            "Reduce form to circle, square and triangle; build images from geometry.",
            "Primary colors (red, yellow, blue) with black and white; flat fills.",
            "Sans-serif, geometric lettering; text can be rotated 90 degrees or set on a diagonal.",
            "Asymmetric, dynamic balance; strong diagonals and overlapping shapes.",
            "Function before ornament: every element has a purpose.",
        ],
        "palettes": [
            P("Primary", "Red, yellow, blue on cream", "#f2ead8", "#111111", "#d62828", "#f4c20d", "#1d4e9e"),
            P("Muted Bauhaus", "Softer vintage primaries", "#efe6d2", "#222222", "#c0392b", "#e0b33a", "#2e5a88"),
        ],
        "palette_names": ["retro"],
        "type": {
            "categories": ["sans-serif"],
            "families": ["Josefin Sans", "League Spartan", "Montserrat", "Jost", "Bebas Neue"],
            "pairings": ["league-spartan-libre-baskerville", "josefin-sans-crimson-pro", "montserrat-open-sans",
                         "bebas-neue-inter"],
            "weights": "Bold geometric headings, regular text.",
            "case": "Lower case was a Bauhaus statement; upper case headings also work.",
            "avoid": ["ornate serifs", "script faces"],
        },
        "layout": {
            "grid": "Dynamic asymmetry with diagonals and overlapping basic shapes.",
            "alignment": "Asymmetric; text may run vertically.",
            "negative_space": "Balanced against heavy shapes.",
            "layouts": ["diagonal-band", "asymmetric-balance", "typographic-poster", "golden-section"],
        },
        "imagery": {
            "advice": "Photomontage, geometric compositions, high-contrast photographs.",
            "looks": ["halftone", "duotone"], "effects": ["grayscale", "contrast"],
            "avoid": ["soft gradients", "ornament", "realistic shadows"],
        },
        "do": ["Compose from circles, squares and triangles", "Use primaries and black", "Make it asymmetric and diagonal"],
        "dont": ["Add ornament", "Use soft gradients", "Center everything"],
        "checks": [
            R("max_typefaces", "At most two typefaces", "Use one geometric sans", max=2),
            R("type_categories", "Sans-serif type", "Use a geometric sans-serif", allowed=["sans-serif"]),
            R("max_colors", "A tight palette (5 colors or fewer)", "Limit to primaries plus black and white", max=5, distance=40),
            R("gradients", "Flat fills", "Replace gradients with flat colors", mode="none"),
            R("shadows", "No soft shadows", "Remove shadows", mode="none"),
        ],
    },
    "art-deco": {
        "title": "Art Deco",
        "summary": "Glamorous symmetry: strong geometry, fans and sunbursts, metallic gold on deep jewel tones, "
                   "tall elegant capitals and ornamental line work.",
        "era": "1920s-1930s, Paris, New York",
        "keywords": ["symmetry", "gold", "geometric ornament", "luxury", "gatsby", "sunburst", "elegant"],
        "best_for": ["invitations", "cocktail menus", "luxury branding", "event posters", "certificates"],
        "principles": [
            "Strict symmetry on a central axis; mirrored ornament and stepped forms.",
            "Gold and metallic accents on deep black, navy, emerald or burgundy.",
            "Tall, geometric capitals with high contrast; letter-spaced small caps for secondary lines.",
            "Fans, sunbursts, chevrons and parallel lines as ornament; fine rules and borders.",
            "Rich but controlled: ornament follows geometry, never random.",
        ],
        "palettes": [
            P("Gold on black", "Classic deco", "#0b0b0d", "#d4af37", "#f5e6b3", "#1c1c21"),
            P("Emerald", "Jewel and gold", "#0f2a24", "#d9b44a", "#f3ead2", "#1f5c4a"),
            P("Navy and cream", "Cool deco", "#10203a", "#e8d8a8", "#f7f1e1", "#b08d57"),
        ],
        "palette_names": ["gold", "midnight"],
        "type": {
            "categories": ["serif", "display", "sans-serif"],
            "families": ["Cinzel", "Marcellus", "Josefin Sans", "Bodoni Moda", "Playfair Display"],
            "pairings": ["cinzel-eb-garamond", "marcellus-lato", "bodoni-moda-inter", "josefin-sans-crimson-pro"],
            "weights": "High-contrast capitals for display; light geometric sans for supporting lines.",
            "case": "Upper case with generous letter spacing.",
            "avoid": ["casual scripts", "rounded bubbly faces"],
        },
        "layout": {
            "grid": "Central axis, concentric frames, stepped corners.",
            "alignment": "Centered and symmetric.",
            "negative_space": "Controlled; ornament frames the content.",
            "layouts": ["centered-axis", "framed", "emblem", "quote-card", "event-poster"],
        },
        "imagery": {
            "advice": "Sunbursts, fan shapes, chevrons and thin gold rules; metallic gradients used sparingly.",
            "looks": ["gradient", "glow", "outline"], "effects": [],
            "avoid": ["asymmetry", "casual hand-drawn marks", "pastel palettes"],
        },
        "do": ["Keep a central axis", "Use gold on dark", "Frame with fine rules"],
        "dont": ["Break symmetry", "Use casual typefaces", "Overload with unrelated ornament"],
        "checks": [
            R("symmetry", "Left and right halves mirror each other (80% or better)", "Mirror elements about the center axis",
              axis="vertical", min=0.8),
            R("text_align", "Text is centered", "Set text align to center", allowed=["center"], scope="all"),
            R("tilt", "Elements stay upright", "Reset rotation", max_fraction=0.25),
            R("type_categories", "Serif or display capitals present", "Use a high-contrast serif for headings",
              required=["serif", "display"]),
        ],
    },
    "mid-century-modern": {
        "title": "Mid-century modern",
        "summary": "Optimistic 1950s-60s modernism: warm earthy-with-pop colors, organic boomerang and atomic "
                   "shapes, chunky slab or geometric type, and tidy layouts with a hand-printed feel.",
        "era": "1945-1969, North America and Europe",
        "keywords": ["atomic", "retro", "boomerang", "teak", "mustard", "orange", "optimistic"],
        "best_for": ["posters", "album covers", "packaging", "book covers", "interiors brands"],
        "principles": [
            "Warm, slightly dusty colors: mustard, burnt orange, teal, olive, cream and walnut brown.",
            "Simple organic and geometric shapes: boomerangs, starbursts, kidney and circle forms.",
            "Flat shapes with slight overprint or grain, like screen-printed work.",
            "Clean sans or friendly slab type with generous size contrast.",
            "Asymmetric but tidy compositions with strong shapes and clear hierarchy.",
        ],
        "palettes": [
            P("Atomic", "Mustard, orange, teal", "#f3e9d2", "#2b2b2b", "#e0a526", "#d9531e", "#2a7f86", "#6b7a3c"),
            P("Teak", "Warm woods", "#efe3cc", "#3a2a1f", "#a0522d", "#e2a63a", "#5f8575"),
        ],
        "palette_names": ["retro", "desert", "autumn"],
        "type": {
            "categories": ["sans-serif", "serif"],
            "families": ["Young Serif", "Rubik", "Alfa Slab One", "Poppins", "Work Sans", "Fraunces"],
            "pairings": ["young-serif-rubik", "alfa-slab-source-sans", "poppins-lora", "work-sans-bitter"],
            "weights": "Bold or slab headings, regular text.",
            "case": "Mixed case; lowercase headlines feel period-correct.",
            "avoid": ["neon colors", "glossy effects", "very thin type"],
        },
        "layout": {
            "grid": "Simple blocks with a dominant shape.",
            "alignment": "Left or asymmetric.",
            "negative_space": "Moderate.",
            "layouts": ["asymmetric-balance", "split-screen", "rule-of-thirds", "event-poster"],
        },
        "imagery": {
            "advice": "Flat shapes, starbursts, simple botanical and geometric motifs with light grain.",
            "looks": ["risograph", "grain", "paper"], "effects": ["grain"],
            "avoid": ["glossy gradients", "neon", "heavy shadows"],
        },
        "do": ["Use warm dusty colors", "Use flat organic shapes", "Add subtle print grain"],
        "dont": ["Use neon", "Add glossy effects", "Use ultra-thin type"],
        "checks": [
            R("saturation", "Dusty, not neon (average saturation 75% or less)", "Tone down the palette", max=0.75),
            R("gradients", "Flat shapes", "Replace gradients with flat color", mode="none"),
            R("max_typefaces", "At most two typefaces", "Use two families", max=2),
            R("max_colors", "A tight palette (6 colors or fewer)", "Limit the palette", max=6, distance=40),
        ],
    },
    "memphis": {
        "title": "Memphis",
        "summary": "Loud, playful 1980s postmodern: clashing bright colors, squiggles, confetti, zigzags and "
                   "terrazzo patterns, tilted shapes and chunky type on busy layouts.",
        "era": "1981-1988, Milan (Memphis Group, Sottsass)",
        "keywords": ["80s", "squiggle", "confetti", "pattern", "clashing", "playful", "terrazzo", "postmodern"],
        "best_for": ["event posters", "kids brands", "social graphics", "music", "packaging"],
        "principles": [
            "Clashing, saturated colors (pink, teal, yellow, purple) with black outlines.",
            "Geometric primitives, squiggles, zigzags, dots and terrazzo-like confetti scattered across the layout.",
            "Tilted, overlapping shapes break the grid on purpose.",
            "Chunky or quirky type; patterns as backgrounds.",
            "Fun over polish; the composition feels spontaneous but balanced.",
        ],
        "palettes": [
            P("Memphis classic", "Pink, teal, yellow, violet", "#fff4e0", "#111111", "#ff4fa3", "#27c4b5", "#ffd23f", "#7b4de0"),
            P("Pastel Memphis", "Softer", "#fff9f0", "#222222", "#ff9ec7", "#8fe3d4", "#ffe58a", "#b9a6ff"),
        ],
        "palette_names": ["candy", "pastel"],
        "type": {
            "categories": ["display", "sans-serif"],
            "families": ["Shrikhand", "Fredoka", "Unbounded", "Syne", "Rubik", "Bungee"],
            "pairings": ["shrikhand-nunito", "fredoka-nunito", "unbounded-manrope", "rubik-karla"],
            "weights": "Bold, rounded or chunky.",
            "case": "Any; playful mixing is fine.",
            "avoid": ["restrained corporate palettes", "perfectly aligned grids"],
        },
        "layout": {
            "grid": "Scattered; overlap and tilt shapes around a focal block of type.",
            "alignment": "Free.",
            "negative_space": "Low; fill with pattern.",
            "layouts": ["diagonal-band", "asymmetric-balance", "thumbnail-bold", "event-poster"],
        },
        "imagery": {
            "advice": "Confetti, squiggles, zigzags, dotted and striped patterns; outlined flat shapes.",
            "looks": ["outline", "hard-shadow"], "effects": ["halftone"],
            "avoid": ["muted palettes", "photographic realism", "perfect symmetry"],
        },
        "do": ["Clash bright colors", "Tilt and overlap shapes", "Use patterns"],
        "dont": ["Keep it tidy and corporate", "Use muted tones only"],
        "checks": [
            R("hue_count", "Several clashing hues (3 or more)", "Add contrasting hues", min=3),
            R("tilt", "Some elements are tilted", "Rotate a few shapes 10-30 degrees", min_fraction=0.15),
            R("max_negative_space", "Busy: no more than 50% empty", "Add shapes or pattern", fraction=0.5),
        ],
    },
    "retro-futurism": {
        "title": "Retro-futurism",
        "summary": "The future as imagined in the past: chrome and gradients, sunset horizons, starbursts, rounded "
                   "geometric type and a space-age optimism in 1950s-80s palettes.",
        "era": "1950s space age to 1980s synth",
        "keywords": ["space age", "chrome", "sunset gradient", "starburst", "atomic", "synth", "orbit"],
        "best_for": ["posters", "album covers", "game art", "tech-nostalgia branding"],
        "principles": [
            "Sunset gradients (orange, magenta, violet), horizon lines and glowing orbs.",
            "Rounded geometric, wide or italic display type with chrome or outline treatment.",
            "Orbits, rockets, stars and grid floors built from simple geometry.",
            "Dark space backgrounds make glows and gradients pop.",
            "Optimistic, clean forms rather than gritty ones.",
        ],
        "palettes": [
            P("Sunset grid", "Synth sunset", "#120a2a", "#ff3c8e", "#ff9f1c", "#7a3cff", "#00e5ff"),
            P("Atomic age", "1950s space", "#10253f", "#f4d35e", "#ee6c4d", "#7bdff2", "#f7f0e0"),
        ],
        "palette_names": ["sunset", "neon", "retro"],
        "type": {
            "categories": ["sans-serif", "display"],
            "families": ["Unbounded", "Syne", "Space Grotesk", "Monoton", "Bungee", "Space Mono"],
            "pairings": ["unbounded-manrope", "space-mono-space-grotesk", "syne-dm-sans"],
            "weights": "Bold wide headings; light body.",
            "case": "Upper case wide display lines.",
            "avoid": ["rustic serifs", "muted earth palettes"],
        },
        "layout": {
            "grid": "Centered horizon compositions, perspective grids, concentric rings.",
            "alignment": "Centered or banded.",
            "negative_space": "Moderate; space for glow.",
            "layouts": ["centered-axis", "hero-statement", "thumbnail-bold", "banner"],
        },
        "imagery": {
            "advice": "Gradient suns, perspective grids, stars, chrome type; glows on dark backgrounds.",
            "looks": ["gradient", "glow", "neon"], "effects": ["vignette"],
            "avoid": ["flat earth palettes", "rustic textures"],
        },
        "do": ["Use sunset gradients", "Set wide geometric display type", "Add glows against dark space"],
        "dont": ["Use muted earth tones", "Use rustic textures"],
        "checks": [
            R("gradients", "Uses gradients", "Add a gradient sky or sun", mode="required"),
            R("type_categories", "Sans or display type", "Use a wide geometric sans or display face",
              allowed=["sans-serif", "display", "monospace"]),
            R("hue_count", "At least two hues", "Add a contrasting second hue", min=2),
        ],
    },
    "vaporwave": {
        "title": "Vaporwave",
        "summary": "Ironic 1980s-90s internet nostalgia: pink-and-cyan gradients, marble busts, palms, grids, "
                   "glitch and Japanese text, over dreamy low-fi gradients.",
        "era": "2010s internet aesthetic",
        "keywords": ["pink cyan", "glitch", "grid", "marble", "retro computer", "dreamy", "aesthetic"],
        "best_for": ["album art", "social media", "posters", "stickers"],
        "principles": [
            "Pink, cyan and purple gradients on dark or pastel backgrounds.",
            "Retro-computer UI, grid floors, sunsets, palm trees and classical statues.",
            "Wide-spaced type, often with Japanese characters or mock-corporate phrases.",
            "Glitch, scanline and chromatic-offset effects add lo-fi texture.",
            "Dreamy, hazy depth rather than crisp realism.",
        ],
        "palettes": [
            P("Vapor", "Pink, cyan, violet", "#1b1034", "#ff71ce", "#01cdfe", "#b967ff", "#fffb96"),
            P("Pastel vapor", "Softer", "#2a1b4d", "#ffb3e6", "#a0f1ff", "#c3a6ff"),
        ],
        "palette_names": ["neon", "lavender", "candy"],
        "type": {
            "categories": ["sans-serif", "display", "monospace"],
            "families": ["Press Start 2P", "Space Mono", "Unbounded", "Monoton", "Syne"],
            "pairings": ["press-start-space-mono", "unbounded-manrope", "space-mono-space-grotesk"],
            "weights": "Any; wide letter spacing.",
            "case": "Upper case with wide tracking.",
            "avoid": ["earth-tone palettes", "tight crowded type"],
        },
        "layout": {
            "grid": "Centered focal object over a perspective grid.",
            "alignment": "Centered.",
            "negative_space": "Moderate.",
            "layouts": ["centered-axis", "hero-statement", "banner"],
        },
        "imagery": {
            "advice": "Gradients, glows, scanlines and chromatic offsets; statues and palms as cut-outs.",
            "looks": ["gradient", "glow", "neon", "duotone"], "effects": ["pixelate", "wave", "vignette"],
            "avoid": ["neutral corporate palettes", "crisp minimal flats"],
        },
        "do": ["Use pink-cyan gradients", "Add glow and glitch", "Space type widely"],
        "dont": ["Use earth tones", "Keep it clinical"],
        "checks": [
            R("gradients", "Uses gradients", "Add a pink-to-cyan gradient", mode="required"),
            R("hue_range", "Mostly magenta, cyan and violet hues", "Shift colors toward pink, cyan and purple",
              hues=[[160, 210], [260, 340]], min_fraction=0.6),
            R("glow", "Something glows", "Apply the glow look to a focal element", mode="required", severity="info"),
        ],
    },
    "y2k": {
        "title": "Y2K",
        "summary": "Late-90s and early-2000s optimism: glossy chrome and bubbles, translucent plastic, silver and "
                   "baby blue, techno-futurist type and stars, butterflies and orbit rings.",
        "era": "1998-2004",
        "keywords": ["chrome", "glossy", "bubble", "silver", "cyber", "futuristic", "web 1.0"],
        "best_for": ["fashion", "music", "social graphics", "stickers", "merch"],
        "principles": [
            "Metallic and glossy surfaces: chrome gradients, bubble highlights and inner glows.",
            "Baby blue, silver, hot pink and lime on light or white-gradient grounds.",
            "Wide, rounded or technical type, sometimes with outlines or chrome effects.",
            "Sparkles, stars, orbits, lens flares and low-res web motifs.",
            "Playful and optimistic; digital rather than organic.",
        ],
        "palettes": [
            P("Chrome pop", "Silver, baby blue, hot pink", "#f4f8ff", "#9bb7e8", "#ff4fa3", "#c0c8d4", "#222a35"),
            P("Cyber lime", "Acid accents", "#eef3fb", "#111827", "#b6ff3b", "#4cc9f0", "#b8bfcc"),
        ],
        "palette_names": ["ice", "candy", "mint"],
        "type": {
            "categories": ["sans-serif", "display"],
            "families": ["Unbounded", "Syne", "Space Grotesk", "Bricolage Grotesque", "Space Mono"],
            "pairings": ["unbounded-manrope", "syne-dm-sans", "bricolage-figtree", "space-mono-space-grotesk"],
            "weights": "Bold and wide.",
            "case": "Lower or mixed case with a techno feel.",
            "avoid": ["earth tones", "hand-lettered scripts"],
        },
        "layout": {
            "grid": "Centered focal graphic with orbit rings and stickers.",
            "alignment": "Centered or free.",
            "negative_space": "Moderate.",
            "layouts": ["hero-statement", "thumbnail-bold", "centered-axis"],
        },
        "imagery": {
            "advice": "Chrome gradients, bubbles, translucent shapes, sparkles and stars.",
            "looks": ["gradient", "glow", "soft-shadow"], "effects": ["blur"],
            "avoid": ["matte earth palettes", "rough print textures"],
        },
        "do": ["Use glossy gradients", "Use silver and baby blue with a hot accent", "Add sparkle shapes"],
        "dont": ["Use matte earth tones", "Use rough print grain"],
        "checks": [
            R("gradients", "Uses gradients for gloss", "Add chrome or glossy gradients", mode="required"),
            R("min_colors", "At least three colors", "Add silver, blue and a pink accent", min=3, distance=40),
            R("shadows", "Soft shadows or none (no hard offsets)", "Use the soft-shadow look", mode="soft-or-none"),
        ],
    },
    "editorial": {
        "title": "Editorial / magazine",
        "summary": "Confident print-inspired layouts: expressive serif headlines, strong hierarchy, multi-column "
                   "grids, pull quotes, captions and full-bleed photography.",
        "era": "Modern magazine and newspaper design",
        "keywords": ["magazine", "serif headline", "columns", "pull quote", "caption", "hierarchy", "long-form"],
        "best_for": ["articles", "covers", "reports", "newsletters", "slides"],
        "principles": [
            "Clear hierarchy: kicker, headline, deck, byline, body, caption.",
            "Expressive display serif or sans for headlines, readable text serif for body.",
            "Multi-column grids with consistent gutters and baseline; pull quotes break the rhythm.",
            "Large, well-cropped photography with captions; rules separate sections.",
            "Dramatic scale contrast between headline and text.",
        ],
        "palettes": [
            P("Newsprint", "Black on warm white with a red accent", "#f7f4ee", "#161616", "#c1272d", "#8a8478"),
            P("Glossy", "High-contrast fashion", "#ffffff", "#000000", "#e4002b"),
        ],
        "palette_names": ["mono", "retro"],
        "type": {
            "categories": ["serif", "sans-serif"],
            "families": ["Playfair Display", "Newsreader", "Source Serif 4", "Fraunces", "Instrument Serif", "Libre Franklin"],
            "pairings": ["playfair-lato", "schibsted-newsreader", "bodoni-moda-inter", "fraunces-work-sans",
                         "instrument-serif-sans", "libre-franklin-libre-baskerville"],
            "weights": "Bold or high-contrast headlines, regular text.",
            "case": "Sentence or title case; small caps for kickers.",
            "avoid": ["more than two families", "decorative scripts for text"],
        },
        "layout": {
            "grid": "Multi-column grid with consistent gutters and baseline.",
            "alignment": "Left aligned text; centered headlines for covers.",
            "negative_space": "Controlled; margins frame the page.",
            "layouts": ["editorial-grid", "photo-caption", "quote-card", "f-pattern", "golden-section"],
        },
        "imagery": {
            "advice": "Full-bleed or large photography with captions; duotone for sections.",
            "looks": ["duotone", "grain"], "effects": ["grain"],
            "avoid": ["clip-art", "drop-shadow overload"],
        },
        "do": ["Build a clear type hierarchy", "Use a column grid", "Add captions and pull quotes"],
        "dont": ["Use too many faces", "Center body text", "Skimp on scale contrast"],
        "checks": [
            R("max_typefaces", "At most two typefaces", "Pair one display and one text face", max=2),
            R("type_scale_ratio", "Strong scale contrast (largest text 3x the smallest or more)",
              "Make the headline much larger than the body", min=3),
            R("text_align", "Body text is left aligned", "Set body text align to left", allowed=["left"], scope="body"),
            R("edge_alignment", "Elements align to a column grid", "Align layers to the same edges", min_fraction=0.6,
              tolerance=3),
        ],
    },
    "corporate-flat": {
        "title": "Corporate / flat design",
        "summary": "Clean, trustworthy and modern: flat vector illustration, a safe blue-led palette, sans-serif "
                   "type, tidy grids and consistent iconography, without gloss or texture.",
        "era": "2010s onward; business and SaaS",
        "keywords": ["flat", "business", "saas", "clean", "trustworthy", "icons", "infographic"],
        "best_for": ["presentations", "reports", "pitch decks", "websites", "infographics"],
        "principles": [
            "Flat fills with no gradients, textures or bevels; simple shapes and icons.",
            "A restrained brand palette: one primary, one or two supports, neutrals.",
            "Readable sans-serif type with a clear scale and consistent alignment.",
            "Generous spacing and a consistent grid; cards and sections are clearly delineated.",
            "Accessibility first: contrast of 4.5:1 and larger text.",
        ],
        "palettes": [
            P("Trust blue", "Blue-led corporate", "#ffffff", "#0b3d91", "#1e88e5", "#f1f5f9", "#1f2937"),
            P("Fresh green", "Growth and finance", "#ffffff", "#0f5132", "#2e9e6b", "#eef7f1", "#1f2937"),
        ],
        "palette_names": ["accessible-blue", "slate", "midnight"],
        "type": {
            "categories": ["sans-serif"],
            "families": ["Roboto", "Open Sans", "Inter", "Montserrat", "IBM Plex Sans", "Public Sans"],
            "pairings": ["roboto-material", "montserrat-open-sans", "inter-single-ui", "ibm-plex-serif-sans",
                         "public-sans-single"],
            "weights": "Bold headings, regular text.",
            "case": "Sentence or title case.",
            "avoid": ["novelty faces", "heavy texture"],
        },
        "layout": {
            "grid": "12-column grid, cards and clear sections.",
            "alignment": "Left aligned.",
            "negative_space": "Comfortable.",
            "layouts": ["slide-content", "split-screen", "bento-grid", "banner", "product-card"],
        },
        "imagery": {
            "advice": "Flat vector illustration and consistent line icons; photos with a color overlay.",
            "looks": ["soft-shadow"], "effects": [],
            "avoid": ["gradients", "bevels", "textures", "glow"],
        },
        "do": ["Keep fills flat", "Use a consistent icon style", "Meet 4.5:1 contrast"],
        "dont": ["Add gloss or texture", "Use novelty type"],
        "checks": [
            R("gradients", "Flat fills", "Replace gradients with flat colors", mode="none"),
            R("design_check", "Readable contrast (4.5:1)", "Darken text or lighten the ground", id="readable-contrast",
              checks=["contrast"], options={"min_contrast": 4.5}),
            R("max_typefaces", "At most two typefaces", "Use one or two sans families", max=2),
            R("type_categories", "Sans-serif type", "Use a sans-serif", allowed=["sans-serif"]),
            R("glow", "No glow", "Remove outer glows", mode="none"),
        ],
    },
    "material": {
        "title": "Material design",
        "summary": "Google's paper-and-ink system: layered surfaces with elevation shadows, bold color, rounded "
                   "cards, Roboto-style type, clear motion and an 8-pixel baseline.",
        "era": "2014 onward",
        "keywords": ["elevation", "cards", "roboto", "fab", "surface", "ripple", "app ui"],
        "best_for": ["app interfaces", "dashboards", "UI mockups", "product screens"],
        "principles": [
            "Surfaces at different elevations cast soft shadows; depth communicates hierarchy.",
            "Bold primary and accent colors with accessible on-colors.",
            "Rounded rectangles, floating action buttons and cards on an 8 dp grid.",
            "Roboto-like geometric sans with a defined type scale.",
            "Meaningful motion and generous touch targets.",
        ],
        "palettes": [
            P("Indigo and pink", "Classic Material", "#fafafa", "#3f51b5", "#ff4081", "#212121", "#ffffff"),
            P("Teal and amber", "Alternative", "#fafafa", "#009688", "#ffc107", "#212121"),
        ],
        "palette_names": ["accessible-blue", "slate"],
        "type": {
            "categories": ["sans-serif"],
            "families": ["Roboto", "Inter", "Open Sans", "Noto Sans"],
            "pairings": ["roboto-material", "roboto-slab-roboto", "inter-single-ui"],
            "weights": "Regular, medium and bold.",
            "case": "Sentence case; buttons in medium weight.",
            "avoid": ["decorative faces"],
        },
        "layout": {
            "grid": "8-pixel baseline, cards with consistent padding.",
            "alignment": "Left aligned in cards.",
            "negative_space": "Comfortable.",
            "layouts": ["bento-grid", "product-card", "banner", "app-icon"],
        },
        "imagery": {
            "advice": "Elevation shadows (soft), cards and floating buttons.",
            "looks": ["soft-shadow"], "effects": [],
            "avoid": ["hard offset shadows", "heavy textures"],
        },
        "do": ["Use soft elevation shadows", "Use rounded cards", "Keep contrast accessible"],
        "dont": ["Use hard offset shadows", "Use ornamental type"],
        "checks": [
            R("shadows", "Soft elevation shadows", "Use look soft-shadow", mode="soft-or-none"),
            R("rounded_corners", "Rounded cards and buttons", "Round the corners of rectangles", min_fraction=0.5),
            R("type_categories", "Sans-serif type", "Use a sans-serif", allowed=["sans-serif"]),
            R("design_check", "Readable contrast (4.5:1)", "Darken text or lighten the ground", id="readable-contrast",
              checks=["contrast"], options={"min_contrast": 4.5}),
        ],
    },
    "glassmorphism": {
        "title": "Glassmorphism",
        "summary": "Frosted-glass cards floating over vivid blurred gradients: translucency, soft borders, subtle "
                   "light edges and layered depth.",
        "era": "2020s UI trend",
        "keywords": ["frosted", "blur", "translucent", "gradient background", "glass", "floating cards"],
        "best_for": ["dashboards", "app UI", "login screens", "landing hero sections", "music players"],
        "principles": [
            "A vivid, blurred gradient background gives the glass something to refract.",
            "Cards are translucent (about 10-30% white or black) with a thin light border and soft shadow.",
            "Rounded corners and generous padding; layers float at different depths.",
            "White or very dark text must still meet contrast over the blur.",
            "Use sparingly: too much glass reads as noise.",
        ],
        "palettes": [
            P("Aurora", "Vivid gradient behind glass", "#4f46e5", "#ec4899", "#22d3ee", "#ffffff"),
            P("Dusk", "Deep violet and orange", "#312e81", "#f97316", "#a78bfa", "#ffffff"),
        ],
        "palette_names": ["lavender", "ocean", "neon"],
        "type": {
            "categories": ["sans-serif"],
            "families": ["Plus Jakarta Sans", "Inter Tight", "Geist", "Poppins", "Inter"],
            "pairings": ["plus-jakarta-single", "inter-tight-inter", "geist-dev"],
            "weights": "Medium to bold, white text.",
            "case": "Sentence case.",
            "avoid": ["thin gray text on blur", "ornate faces"],
        },
        "layout": {
            "grid": "A few large rounded cards floating over a gradient field.",
            "alignment": "Left aligned in cards, centered hero.",
            "negative_space": "Moderate.",
            "layouts": ["bento-grid", "hero-statement", "product-card", "split-screen"],
        },
        "imagery": {
            "advice": "Blurred gradient blobs behind translucent cards; add a thin light stroke and soft shadow.",
            "looks": ["gradient", "soft-shadow", "outline"], "effects": ["blur"],
            "avoid": ["hard shadows", "flat opaque cards"],
        },
        "do": ["Blur a vivid gradient behind the cards", "Add a thin light border", "Keep text contrast high"],
        "dont": ["Use hard shadows", "Put low-contrast text on busy blur"],
        "checks": [
            R("gradients", "A gradient background", "Add a vivid gradient behind the glass", mode="required"),
            R("rounded_corners", "Rounded translucent cards", "Round the corner radius", min_fraction=0.5),
            R("design_check", "Readable contrast (4.5:1)", "Darken the glass or lighten the text", id="readable-contrast",
              checks=["contrast"], options={"min_contrast": 4.5}),
            R("shadows", "Soft shadows only", "Replace hard shadows", mode="soft-or-none"),
        ],
    },
    "grunge-zine": {
        "title": "Grunge / punk zine",
        "summary": "DIY photocopy aesthetic: cut-and-paste collage, ransom-note type, torn paper, tape, rough "
                   "halftone and distressed texture in harsh black, white and one neon or red.",
        "era": "1970s punk, 1990s grunge and riot grrrl zines",
        "keywords": ["xerox", "collage", "torn paper", "ransom note", "distressed", "diy", "photocopy"],
        "best_for": ["gig posters", "zines", "album art", "protest graphics", "streetwear"],
        "principles": [
            "Photocopied, high-contrast, grainy imagery; thresholded and halftone photographs.",
            "Cut-and-paste collage with mismatched type, torn edges, tape and handwritten marks.",
            "Harsh black and white with one hot color (red, yellow, magenta).",
            "Rotated, overlapping layers; imperfect alignment is intentional.",
            "Texture everywhere: grain, scratches, stains.",
        ],
        "palettes": [
            P("Xerox", "Black, white, hot red", "#f1efe9", "#0d0d0d", "#e10600", "#bdb8ad"),
            P("Neon zine", "Photocopy plus fluorescent", "#f5f3ee", "#101010", "#ff2e93", "#d6ff2e"),
        ],
        "palette_names": ["mono", "neon"],
        "type": {
            "categories": ["display", "sans-serif", "monospace", "handwriting"],
            "families": ["Permanent Marker", "Anton", "League Gothic", "Space Mono", "Caveat", "UnifrakturMaguntia"],
            "pairings": ["unifraktur-libre-caslon", "league-gothic-libre-baskerville", "anton-roboto-thumbnail",
                         "space-mono-single-brutalist", "caveat-karla"],
            "weights": "Bold; mix sizes and faces on purpose.",
            "case": "Upper case with mismatched letters.",
            "avoid": ["tidy corporate sans", "perfect alignment"],
        },
        "layout": {
            "grid": "Collage; overlap, rotate and tape elements.",
            "alignment": "Free and off-kilter.",
            "negative_space": "Low.",
            "layouts": ["typographic-poster", "diagonal-band", "thumbnail-bold"],
        },
        "imagery": {
            "advice": "Thresholded and halftoned photos, torn paper shapes (tear with as: mask on photos, as: path for "
                      "scraps), tape rectangles, grain on everything; irregular placement on rotated cut-outs.",
            "looks": ["grain", "halftone", "paper"], "effects": ["threshold", "halftone", "grain", "photocopy"],
            "avoid": ["clean gradients", "soft shadows", "tidy grids"],
        },
        "do": ["Photocopy everything", "Rotate and overlap", "Add grain and halftone"],
        "dont": ["Keep it tidy", "Use clean gradients"],
        "checks": [
            R("effects", "Has texture (grain, halftone or photocopy effects)", "Add the grain or halftone look",
              require_any=["grain", "noise", "halftone", "photocopy", "threshold", "stamp", "ink-blot", "pixelate"]),
            R("tilt", "Some elements are rotated", "Tilt a few layers", min_fraction=0.15),
            R("gradients", "No clean gradients", "Use flat black and white", mode="none"),
        ],
    },
    "japanese-minimal": {
        "title": "Japanese minimalism (Ma)",
        "summary": "Quiet, asymmetric restraint built on 'ma' (meaningful emptiness): soft natural palettes, "
                   "fine type, vertical text, a single red seal accent and careful balance.",
        "era": "Traditional aesthetics (wabi-sabi, ma) and modern Muji-like design",
        "keywords": ["ma", "wabi-sabi", "zen", "negative space", "hanko", "muji", "vertical text"],
        "best_for": ["tea and ceramics", "stationery", "hospitality", "packaging", "portfolios"],
        "principles": [
            "Embrace emptiness (ma): at least half the canvas is quiet space.",
            "Asymmetric balance with a small focal element, often placed off-center.",
            "Natural, desaturated palette: paper white, charcoal, indigo and a single vermilion seal accent.",
            "Fine, precise type; vertical text lines are traditional; Mincho (serif) and Gothic (sans) pairings.",
            "Imperfection and natural texture (paper, ink wash) are welcome; ornament is not.",
        ],
        "palettes": [
            P("Washi and sumi", "Paper, ink, vermilion", "#f4f0e6", "#222222", "#c8372d", "#8a8a80"),
            P("Indigo", "Aizome", "#f2efe6", "#1f2a44", "#c8372d", "#6b7a99"),
        ],
        "palette_names": ["mono", "sage"],
        "type": {
            "categories": ["serif", "sans-serif"],
            "families": ["Noto Serif JP", "Noto Sans JP", "Cormorant Garamond", "Jost", "EB Garamond"],
            "pairings": ["noto-serif-jp-sans-jp", "cormorant-jost", "eb-garamond-single"],
            "weights": "Light to regular.",
            "case": "Sentence case; generous tracking in small text.",
            "avoid": ["loud display faces", "heavy weights"],
        },
        "layout": {
            "grid": "Asymmetric; a small element and a short text block in a field of quiet space.",
            "alignment": "Off-center; vertical text lines are acceptable.",
            "negative_space": "50% or more.",
            "layouts": ["minimal-mark", "quote-card", "rule-of-thirds", "asymmetric-balance"],
        },
        "imagery": {
            "advice": "One ink-wash or natural photograph; red seal square as the single accent; subtle paper grain.",
            "looks": ["paper", "grain", "watercolor"], "effects": ["grain"],
            "avoid": ["gradients", "neon", "ornament"],
        },
        "do": ["Leave half the canvas empty", "Use one red accent", "Use fine type"],
        "dont": ["Fill the space", "Use more than one accent", "Use heavy display faces"],
        "checks": [
            R("min_negative_space", "At least half the canvas is empty", "Remove elements or enlarge the empty area",
              fraction=0.5),
            R("max_colors", "At most four colors", "Limit to paper, ink, one gray and one accent", max=4, distance=40),
            R("max_weight", "Light to regular weights", "Use a lighter weight", weight=500, scope="all"),
            R("gradients", "No gradients", "Use flat color", mode="none"),
        ],
    },
    "vintage-letterpress": {
        "title": "Vintage / letterpress",
        "summary": "Classic printed-matter charm: serif and slab type, ornamental rules and frames, cream paper "
                   "with deep ink colors, slightly uneven impression and old-style layouts.",
        "era": "19th and early 20th century printing; modern letterpress revival",
        "keywords": ["letterpress", "antique", "serif", "ornament", "cream paper", "stamp", "badge"],
        "best_for": ["wedding stationery", "craft labels", "menus", "certificates", "heritage brands"],
        "principles": [
            "Cream or kraft paper stock with one or two deep ink colors (black, oxblood, navy).",
            "Serif and slab-serif type, mixed sizes in the same block, ornamental rules, frames and flourishes.",
            "Centered, formal layouts with symmetrical ornament; small caps and italics.",
            "Impression and ink texture: slight grain, uneven ink and paper fibre.",
            "Badges, banners and stamps are classic containers.",
        ],
        "palettes": [
            P("Cream and oxblood", "Two-ink print", "#f3ead8", "#1f1a17", "#7a1f2b"),
            P("Navy ink", "Cool vintage", "#f1e9d6", "#1d2b4f", "#b5651d"),
            P("Kraft", "Natural paper", "#d9bf94", "#2b2118", "#8b3a2f"),
        ],
        "palette_names": ["coffee", "copper", "autumn"],
        "type": {
            "categories": ["serif", "display"],
            "families": ["Old Standard TT", "EB Garamond", "Libre Caslon Text", "Cinzel", "Abril Fatface", "Alfa Slab One"],
            "pairings": ["old-standard-single-academic", "eb-garamond-single", "abril-fatface-pt-sans",
                         "great-vibes-eb-garamond", "unifraktur-libre-caslon", "cinzel-eb-garamond"],
            "weights": "Regular and bold serifs; italics for emphasis.",
            "case": "Mixed: small caps and upper case for display lines.",
            "avoid": ["geometric sans-serifs", "neon colors"],
        },
        "layout": {
            "grid": "Centered stacks inside frames and banners.",
            "alignment": "Centered.",
            "negative_space": "Moderate; ornament fills.",
            "layouts": ["framed", "centered-axis", "emblem", "letterhead", "price-list"],
        },
        "imagery": {
            "advice": "Woodcut engravings, rules, frames, banners and stamps; paper grain and slight ink spread.",
            "looks": ["paper", "film", "grain"], "effects": ["sepia", "grain"],
            "avoid": ["gradients", "glows", "neon"],
        },
        "do": ["Print on cream paper", "Use serif and slab type", "Frame with rules"],
        "dont": ["Use geometric sans", "Add gradients or glows"],
        "checks": [
            R("type_categories", "Serif or slab type", "Use a serif or slab-serif", allowed=["serif", "display"]),
            R("max_colors", "A two-ink palette plus paper (4 colors or fewer)", "Limit the palette", max=4, distance=40),
            R("gradients", "No gradients", "Use flat ink colors", mode="none"),
            R("glow", "No glow", "Remove outer glows", mode="none"),
        ],
    },
    "hand-drawn": {
        "title": "Hand-drawn / organic",
        "summary": "Warm, human, imperfect: sketchy lines, brush lettering, doodles, natural color and organic "
                   "shapes that feel made by a person.",
        "era": "Contemporary craft and indie branding",
        "keywords": ["doodle", "sketch", "organic", "handwritten", "brush", "illustrated", "imperfect"],
        "best_for": ["food and craft brands", "children's books", "invitations", "social graphics", "packaging"],
        "principles": [
            "Embrace imperfection: wobbly lines, uneven fills, visible brush strokes.",
            "Hand lettering or a handwriting face for accents, paired with a calm text face.",
            "Organic, curved shapes and botanical motifs instead of rigid geometry.",
            "Warm, natural colors with watercolor, pencil or ink textures.",
            "Layouts feel relaxed and slightly asymmetric.",
        ],
        "palettes": [
            P("Garden", "Leaf green, terracotta, cream", "#f8f1e4", "#2f3a2c", "#6a994e", "#e07a5f", "#f2cc8f"),
            P("Ink and wash", "Ink with soft watercolor", "#fbf7f0", "#1f2933", "#4a90a4", "#e9b872"),
        ],
        "palette_names": ["forest", "earth", "spring"],
        "type": {
            "categories": ["handwriting", "serif", "sans-serif"],
            "families": ["Caveat", "Pacifico", "Dancing Script", "Permanent Marker", "Fraunces", "Karla"],
            "pairings": ["caveat-karla", "pacifico-lato", "fraunces-work-sans", "young-serif-rubik"],
            "weights": "Regular; the hand does the emphasis.",
            "case": "Sentence case.",
            "avoid": ["rigid corporate sans only", "perfect geometric shapes only"],
        },
        "layout": {
            "grid": "Loose and relaxed; organic shapes frame content.",
            "alignment": "Left or centered, imperfectly.",
            "negative_space": "Moderate.",
            "layouts": ["rule-of-thirds", "hero-statement", "photo-caption", "quote-card"],
        },
        "imagery": {
            "advice": "Use organic, paint and pen operations; botanical presets; pencil or watercolor looks. Give drawn "
                      "shapes and outlines irregular (subtle or natural, with pressure) so lines waver like ink; add "
                      "drawn-texture pencil or ink-wash on fills. Keep the type and frame clean.",
            "looks": ["sketch", "watercolor", "paper"], "effects": ["pencil-sketch", "watercolor"],
            "avoid": ["hard shadows", "glossy gradients", "perfect geometry only"],
        },
        "do": ["Use brush and pencil strokes", "Add botanical shapes", "Use warm natural colors"],
        "dont": ["Keep everything perfectly geometric", "Use glossy effects"],
        "checks": [
            R("type_categories", "Includes a handwriting or serif accent", "Use a hand-lettered face for the headline",
              required=["handwriting", "serif"]),
            R("gradients", "No glossy gradients", "Use flat or textured fills", mode="none"),
            R("shadows", "No hard shadows", "Remove hard shadows", mode="soft-or-none"),
        ],
    },
    "maximalist": {
        "title": "Maximalism",
        "summary": "More is more: rich saturated color, layered patterns, mixed typefaces, ornate detail and "
                   "full, dense compositions with confident clashes.",
        "era": "Contemporary reaction to minimalism",
        "keywords": ["bold", "pattern mix", "dense", "ornate", "eclectic", "colorful", "layered"],
        "best_for": ["festival posters", "fashion", "packaging", "album art", "editorial spreads"],
        "principles": [
            "Fill the canvas: layered patterns, overlapping images, big type and ornament.",
            "Rich, saturated, unexpected color combinations.",
            "Mix typefaces (display serif, script, grotesque) with deliberate hierarchy.",
            "Pattern on pattern, but keep one dominant focal point so the page still reads.",
            "Texture, gradients and ornament are welcome.",
        ],
        "palettes": [
            P("Jewel box", "Deep saturated jewels", "#2a0a3a", "#ff3d81", "#ffb400", "#00b3a4", "#f6e9ff"),
            P("Tropical", "Hot and lush", "#0d3b2e", "#ff5d73", "#ffd166", "#06d6a0", "#f8f1e5"),
        ],
        "palette_names": ["berry", "candy", "neon"],
        "type": {
            "categories": ["display", "serif", "handwriting", "sans-serif"],
            "families": ["Abril Fatface", "Shrikhand", "Playfair Display", "Dancing Script", "Bodoni Moda", "Unbounded"],
            "pairings": ["abril-fatface-pt-sans", "shrikhand-nunito", "playfair-lato", "bodoni-moda-inter"],
            "weights": "Bold display with detailed supporting type.",
            "case": "Any; contrast is the point.",
            "avoid": ["empty space", "single-color restraint"],
        },
        "layout": {
            "grid": "Layered and overlapping with one clear focal block.",
            "alignment": "Mixed.",
            "negative_space": "Low (under 35%).",
            "layouts": ["typographic-poster", "event-poster", "diagonal-band", "editorial-grid"],
        },
        "imagery": {
            "advice": "Layered patterns, cut-out photos, ornament, gradients and glows.",
            "looks": ["gradient", "glow", "hard-shadow", "outline"], "effects": [],
            "avoid": ["large empty areas", "monochrome restraint"],
        },
        "do": ["Layer patterns", "Mix rich colors", "Keep one dominant focal point"],
        "dont": ["Leave large empty areas", "Stay monochrome"],
        "checks": [
            R("max_negative_space", "Dense: no more than 35% empty", "Add layers, pattern or ornament", fraction=0.35),
            R("min_colors", "A rich palette (4 colors or more)", "Add contrasting colors", min=4, distance=40),
            R("min_layers", "Many elements (8 or more)", "Add pattern and ornament layers", min=8),
        ],
    },
    "cyberpunk": {
        "title": "Cyberpunk / neon",
        "summary": "High-tech low-life: neon magenta, cyan and yellow on near-black, glowing outlines, glitch and "
                   "scanlines, monospace and condensed type, and dense HUD overlays.",
        "era": "1980s sci-fi (Blade Runner, Neuromancer) to modern game UI",
        "keywords": ["neon", "glow", "dystopian", "hud", "glitch", "dark", "synthwave"],
        "best_for": ["game art", "event posters", "tech launches", "album covers", "streaming overlays"],
        "principles": [
            "Dark background (near-black navy or purple) so neon colors glow.",
            "Neon magenta, cyan, yellow and electric green with glowing outlines.",
            "Monospace, condensed or angular display type; HUD frames, brackets and data labels.",
            "Glitch, scanline, chromatic aberration and grain add grit.",
            "High contrast and dense detail.",
        ],
        "palettes": [
            P("Night city", "Neon on near-black", "#0a0a1a", "#ff2bd6", "#00f0ff", "#fcee0a", "#7d00ff"),
            P("Acid", "Green and violet", "#07070d", "#39ff14", "#b026ff", "#00e5ff"),
        ],
        "palette_names": ["neon", "midnight"],
        "type": {
            "categories": ["monospace", "sans-serif", "display"],
            "families": ["Space Mono", "JetBrains Mono", "Big Shoulders Display", "Unbounded", "Press Start 2P", "Monoton"],
            "pairings": ["space-mono-space-grotesk", "jetbrains-mono-inter-docs", "big-shoulders-barlow",
                         "press-start-space-mono", "unbounded-manrope"],
            "weights": "Bold condensed or mono.",
            "case": "Upper case.",
            "avoid": ["serif romance", "pastel palettes"],
        },
        "layout": {
            "grid": "Dense HUD frames and diagonal slashes around a glowing focal element.",
            "alignment": "Left, asymmetric.",
            "negative_space": "Low to moderate.",
            "layouts": ["thumbnail-bold", "diagonal-band", "hero-statement", "banner"],
        },
        "imagery": {
            "advice": "Neon glows, outlines and gradients on dark; scanlines and glitch offsets.",
            "looks": ["neon", "glow", "grain"], "effects": ["vignette", "grain"],
            "avoid": ["light backgrounds", "muted palettes"],
        },
        "do": ["Go dark", "Glow the neon", "Use mono or condensed type"],
        "dont": ["Use light backgrounds", "Use muted palettes"],
        "checks": [
            R("dark_background", "Dark background", "Use a near-black background", max_luminance=0.12),
            R("glow", "Neon glow present", "Apply the glow or neon look", mode="required"),
            R("design_check", "Readable contrast (4.5:1)", "Brighten text against the dark", id="readable-contrast",
              checks=["contrast"], options={"min_contrast": 4.5}),
        ],
    },
    "kawaii": {
        "title": "Kawaii",
        "summary": "Japanese cute culture: pastel colors, rounded blobby shapes, big-eyed faces, sparkles and hearts, "
                   "soft outlines and bubbly rounded type.",
        "era": "1970s onward; Sanrio and contemporary character design",
        "keywords": ["cute", "pastel", "rounded", "sticker", "mascot", "chibi", "sparkle"],
        "best_for": ["stickers", "characters and mascots", "kids brands", "social posts", "packaging"],
        "principles": [
            "Pastel pinks, mints, lavenders and baby blues with soft contrast.",
            "Very rounded, simple shapes; thick soft outlines or none; big heads, tiny details.",
            "Faces with wide-set eyes and small mouths; blushes; sparkles, hearts and stars as accents.",
            "Rounded, bubbly type with generous spacing.",
            "Everything is soft: no sharp corners or harsh shadows.",
        ],
        "palettes": [
            P("Candy pastel", "Pink, mint, lavender", "#fff1f6", "#5b3a4e", "#ffb3d1", "#b8f0d8", "#cdb4ff", "#fff3a3"),
            P("Cloud", "Baby blue and cream", "#f4fbff", "#4a5a78", "#a8d8f0", "#ffd6e0", "#fff7c2"),
        ],
        "palette_names": ["pastel", "peach", "lavender"],
        "type": {
            "categories": ["sans-serif", "display", "handwriting"],
            "families": ["Fredoka", "Nunito", "Pacifico", "Rubik", "Shrikhand"],
            "pairings": ["fredoka-nunito", "pacifico-lato", "shrikhand-nunito", "rubik-karla"],
            "weights": "Medium to bold rounded.",
            "case": "Lower or sentence case.",
            "avoid": ["sharp angular faces", "dark moody palettes"],
        },
        "layout": {
            "grid": "Centered character with floating accents.",
            "alignment": "Centered.",
            "negative_space": "Moderate.",
            "layouts": ["centered-axis", "hero-statement", "product-card", "emblem"],
        },
        "imagery": {
            "advice": "Build characters from grouped rounded parts (character, or ellipses and rounded rectangles) with soft "
                      "outlines and sparkle and heart accents. irregular strength subtle on bodies, ears and accents (not "
                      "eyes) keeps them hand-made; scatter accents irregularly rather than on a grid.",
            "looks": ["soft-shadow", "outline", "glow"], "effects": [],
            "avoid": ["sharp corners", "harsh black", "gritty textures"],
        },
        "do": ["Round everything", "Use pastel colors", "Add sparkles and hearts"],
        "dont": ["Use sharp corners", "Use harsh dark palettes"],
        "checks": [
            R("rounded_corners", "Shapes are rounded (no sharp rectangles)", "Use rounded-rectangle or ellipse shapes",
              min_fraction=0.8),
            R("saturation", "Soft pastels (average saturation 60% or less)", "Lighten and soften the colors", max=0.6),
            R("lightness", "Light colors (average lightness 60% or more)", "Use lighter pastel tints", min=0.6),
        ],
    },
    "line-art": {
        "title": "Line art / outline illustration",
        "summary": "Drawing with line alone: consistent stroke weight, little or no fill, simple continuous "
                   "contours and plenty of paper, in one ink color.",
        "era": "Timeless; contemporary monoline illustration and icons",
        "keywords": ["monoline", "outline", "contour", "icon", "continuous line", "minimal drawing"],
        "best_for": ["icons", "logos", "illustrations", "tattoo-style art", "stationery"],
        "principles": [
            "Use one stroke weight throughout (monoline) with round caps and joins.",
            "Shapes are outlined, not filled; fill only for deliberate emphasis.",
            "One ink color on a light ground; at most one accent.",
            "Simplify forms to their contour; leave gaps for suggestion.",
            "Align and space icons on a keyline grid.",
        ],
        "palettes": [
            P("Ink", "Single ink on paper", "#fbfaf7", "#1c1c1c"),
            P("Blue ink", "Blue line on cream", "#fbf8f1", "#243b6b", "#d98324"),
        ],
        "palette_names": ["mono"],
        "type": {
            "categories": ["sans-serif", "serif"],
            "families": ["Josefin Sans", "Cormorant Garamond", "Jost", "Instrument Sans", "Inter"],
            "pairings": ["josefin-sans-crimson-pro", "cormorant-jost", "instrument-serif-sans", "inter-single-ui"],
            "weights": "Light to regular, matching the line weight.",
            "case": "Sentence case or small caps.",
            "avoid": ["heavy black weights", "filled blobs"],
        },
        "layout": {
            "grid": "Keyline grid for icons; airy compositions.",
            "alignment": "Centered or grid-aligned.",
            "negative_space": "Generous.",
            "layouts": ["logo-stacked", "monogram", "minimal-mark", "app-icon"],
        },
        "imagery": {
            "advice": "Use pen and shape strokes with transparent fills; round caps; pencil-sketch look for photos.",
            "looks": ["outline", "sketch"], "effects": ["pencil-sketch", "find-edges"],
            "avoid": ["fills and gradients", "shadows", "mixed stroke weights"],
        },
        "do": ["Keep one stroke weight", "Leave shapes unfilled", "Use one ink color"],
        "dont": ["Fill shapes solid", "Add shadows or gradients", "Mix many line weights"],
        "checks": [
            R("stroke_style", "Shapes are outlined, not filled", "Set fill to transparent and add a stroke", mode="outline"),
            R("uniform_stroke", "One stroke weight throughout", "Use the same stroke width on every shape", tolerance=0.5),
            R("shadows", "No shadows or glows", "Remove layer styles", mode="none"),
            R("max_colors", "One or two inks", "Limit the palette to two colors", max=2, distance=40),
        ],
    },
    "risograph": {
        "title": "Risograph",
        "summary": "Two- and three-ink print look: limited vibrant spot colors that overprint, visible grain and "
                   "halftone, slight misregistration and uncoated paper.",
        "era": "Contemporary indie print revival",
        "keywords": ["riso", "spot color", "overprint", "halftone", "grain", "misregistration", "zine"],
        "best_for": ["posters", "zines", "illustration prints", "album art", "event flyers"],
        "principles": [
            "Limit the palette to two or three spot inks (fluorescent pink, blue, yellow, teal).",
            "Overlap inks with multiply blending so overprints make new colors.",
            "Grain and halftone shading replace smooth gradients.",
            "Slight misregistration between color layers adds charm.",
            "Warm off-white paper ground.",
        ],
        "palettes": [
            P("Pink and blue", "Classic riso duo", "#f7f1e3", "#ff48b0", "#0078bf", "#2b2b2b"),
            P("Sunrise", "Yellow, orange, teal", "#f6efdd", "#ffb511", "#ff6c2f", "#00a95c"),
        ],
        "palette_names": ["candy", "retro"],
        "type": {
            "categories": ["sans-serif", "serif", "display"],
            "families": ["Bricolage Grotesque", "Syne", "Young Serif", "Space Grotesk", "Space Mono"],
            "pairings": ["bricolage-figtree", "syne-dm-sans", "space-mono-space-grotesk", "young-serif-rubik"],
            "weights": "Bold headings that print solid.",
            "case": "Any.",
            "avoid": ["fine hairlines (they fill in)", "many colors"],
        },
        "layout": {
            "grid": "Poster layouts with large flat color areas and overprinted shapes.",
            "alignment": "Free.",
            "negative_space": "Moderate.",
            "layouts": ["typographic-poster", "asymmetric-balance", "diagonal-band", "event-poster"],
        },
        "imagery": {
            "advice": "Use risograph or duotone looks; multiply blend; add halftone and grain.",
            "looks": ["risograph", "duotone", "halftone", "grain"], "effects": ["halftone", "grain", "duotone"],
            "avoid": ["smooth gradients", "more than three inks"],
        },
        "do": ["Limit to 2-3 inks", "Use multiply overprint", "Add grain and halftone"],
        "dont": ["Use smooth gradients", "Use many colors"],
        "checks": [
            R("max_colors", "Two or three inks plus paper (4 colors or fewer)", "Limit to spot colors", max=4, distance=45),
            R("gradients", "No smooth gradients", "Use halftone instead", mode="none"),
            R("effects", "Has grain or halftone", "Apply the risograph or grain look",
              require_any=["grain", "noise", "halftone", "duotone"]),
        ],
    },
    "data-viz": {
        "title": "Data visualization / technical",
        "summary": "Clarity for numbers: a restrained categorical palette, direct labels, tabular type, light grids, "
                   "consistent scales and no chart junk.",
        "era": "Tufte, Few, Cleveland, modern dashboard design",
        "keywords": ["chart", "dashboard", "infographic", "technical", "graph", "tabular", "clarity"],
        "best_for": ["dashboards", "reports", "infographics", "scientific figures", "slides"],
        "principles": [
            "Maximize the data-ink ratio: remove decoration that carries no data.",
            "Use a restrained palette with one highlight color and neutral grays for context.",
            "Label directly; keep text at least 12 px (or 8 pt) and left-aligned.",
            "Use tabular or monospace numerals for numbers; align decimals.",
            "Consistent scales, light gridlines, and meaningful ordering.",
        ],
        "palettes": [
            P("Highlight", "Grays plus one accent", "#ffffff", "#2b2b2b", "#9aa0a6", "#d9dce0", "#e4572e"),
            P("Categorical", "Colorblind-aware set", "#ffffff", "#1b1f24", "#0072b2", "#e69f00", "#009e73", "#cc79a7"),
        ],
        "palette_names": ["accessible-blue", "slate", "mono"],
        "type": {
            "categories": ["sans-serif", "monospace"],
            "families": ["IBM Plex Sans", "IBM Plex Mono", "Inter", "Roboto Mono", "JetBrains Mono", "Source Sans 3"],
            "pairings": ["ibm-plex-mono-sans", "jetbrains-mono-inter-docs", "inter-single-ui", "roboto-material",
                         "geist-dev"],
            "weights": "Regular and medium; bold only for the key number.",
            "case": "Sentence case; units in lower case.",
            "avoid": ["decorative type", "all-caps paragraphs"],
        },
        "layout": {
            "grid": "A tidy grid of panels with consistent margins.",
            "alignment": "Left aligned; numbers aligned on decimals.",
            "negative_space": "Moderate.",
            "layouts": ["bento-grid", "big-number", "slide-content", "f-pattern"],
        },
        "imagery": {
            "advice": "Flat shapes for marks; light grids; one highlight color; no 3D effects.",
            "looks": [], "effects": [],
            "avoid": ["3D", "shadows", "gradients", "chart junk"],
        },
        "do": ["Use one highlight color", "Label directly", "Use tabular numerals"],
        "dont": ["Use 3D or shadows", "Add decoration", "Use more than ~6 categories"],
        "checks": [
            R("max_colors", "A restrained palette (6 colors or fewer)", "Group categories or use grays for context",
              max=6, distance=35),
            R("min_text_size", "Text at least 12 px tall", "Increase text size", size=12),
            R("shadows", "No shadows or glows", "Remove layer styles", mode="none"),
            R("gradients", "Flat fills", "Replace gradients with flat colors", mode="none"),
            R("text_align", "Text is left aligned", "Set text align to left", allowed=["left"], scope="all"),
        ],
    },
    "art-nouveau": {
        "title": "Art Nouveau",
        "summary": "Flowing organic ornament: whiplash curves, botanical and female forms, decorative borders, "
                   "earthy gold-and-green palettes and elegant custom lettering.",
        "era": "1890-1910 (Mucha, Beardsley, Klimt)",
        "keywords": ["whiplash", "botanical", "ornamental", "mucha", "curves", "decorative", "gold"],
        "best_for": ["posters", "invitations", "packaging", "tea and perfume brands", "book covers"],
        "principles": [
            "Sinuous, asymmetric whiplash curves and plant forms as structure and ornament.",
            "Decorative frames and halos that enclose the focal figure.",
            "Muted earthy palette with gold and soft pastels.",
            "Custom-feeling lettering integrated into the composition.",
            "Flat areas outlined in dark line, like lithographs.",
        ],
        "palettes": [
            P("Mucha", "Sage, ochre, rose, cream", "#f1e6c8", "#3a3a2a", "#a3a380", "#d1a054", "#c98b7a"),
            P("Peacock", "Teal and gold", "#efe4c6", "#1c3b3a", "#2a7f7a", "#c9a227", "#8a4b6a"),
        ],
        "palette_names": ["sage", "earth", "gold"],
        "type": {
            "categories": ["display", "serif", "handwriting"],
            "families": ["Cormorant Garamond", "Marcellus", "Great Vibes", "Playfair Display", "Cinzel"],
            "pairings": ["cormorant-jost", "great-vibes-eb-garamond", "playfair-lato", "marcellus-lato"],
            "weights": "Elegant regular; display for the title.",
            "case": "Mixed case; flowing display lines.",
            "avoid": ["rigid grotesques", "neon colors"],
        },
        "layout": {
            "grid": "A central figure inside an ornamental frame or halo; curved borders.",
            "alignment": "Centered with organic asymmetry.",
            "negative_space": "Filled with ornament.",
            "layouts": ["framed", "centered-axis", "emblem", "quote-card"],
        },
        "imagery": {
            "advice": "Use the organic operation for flowers, vines and leaves; frame figures with circles or arches.",
            "looks": ["paper", "outline"], "effects": [],
            "avoid": ["hard-edged tech motifs", "neon"],
        },
        "do": ["Use flowing botanical curves", "Frame the focal figure", "Use earthy gold and sage"],
        "dont": ["Use harsh geometry only", "Use neon colors"],
        "checks": [
            R("saturation", "Muted, earthy colors (average saturation 65% or less)", "Tone down the palette", max=0.65),
            R("type_categories", "Serif, display or script type", "Use an elegant serif or display face",
              allowed=["serif", "display", "handwriting"]),
            R("glow", "No neon glow", "Remove outer glows", mode="none"),
        ],
    },
    "pixel-art": {
        "title": "Pixel art / 8-bit",
        "summary": "Hand-placed squares: a tiny fixed palette, crisp unsmoothed edges, limited resolution, bitmap "
                   "type and arcade or console-era motifs.",
        "era": "1980s-90s games; indie revival",
        "keywords": ["8-bit", "16-bit", "sprite", "retro game", "bitmap", "arcade", "crisp"],
        "best_for": ["game art", "avatars", "stickers", "retro posters", "animation"],
        "principles": [
            "Work on a small pixel grid and scale up by whole numbers with nearest-neighbor sampling.",
            "A fixed palette of 4-16 colors; avoid anti-aliasing and smooth gradients.",
            "Clean 1-pixel outlines and consistent light direction.",
            "Bitmap type on the same grid; align everything to whole pixels.",
            "Animate with few frames and simple loops.",
        ],
        "palettes": [
            P("Arcade", "Bright arcade colors", "#0f0f1b", "#ff004d", "#ffa300", "#ffec27", "#00e436", "#29adff", "#ffffff"),
            P("Gameboy", "Four greens", "#0f380f", "#306230", "#8bac0f", "#9bbc0f"),
        ],
        "palette_names": ["retro", "neon"],
        "type": {
            "categories": ["display", "monospace"],
            "families": ["Press Start 2P", "Space Mono", "DM Mono"],
            "pairings": ["press-start-space-mono"],
            "weights": "Bitmap regular.",
            "case": "Upper case.",
            "avoid": ["smooth anti-aliased display faces at tiny sizes"],
        },
        "layout": {
            "grid": "Pixel grid; scale by integers.",
            "alignment": "Grid aligned.",
            "negative_space": "Moderate.",
            "layouts": ["thumbnail-bold", "hero-statement", "app-icon"],
        },
        "imagery": {
            "advice": "Use pixel-art, pixel-draw and pixel-palette operations; export with sampling nearest.",
            "looks": [], "effects": ["pixelate", "posterize"],
            "avoid": ["blur", "smooth gradients", "soft shadows"],
        },
        "do": ["Limit the palette", "Scale by whole numbers", "Use nearest-neighbor sampling"],
        "dont": ["Anti-alias", "Use blur or gradients"],
        "checks": [
            R("max_colors", "A small fixed palette (16 colors or fewer)", "Reduce the palette", max=16, distance=20),
            R("gradients", "No smooth gradients", "Use flat colors", mode="none"),
            R("shadows", "No soft shadows or glows", "Remove layer styles", mode="none"),
        ],
    },
}
